//<MStar Software>
//******************************************************************************
// MStar Software
// Copyright (c) 2010 - 2012 MStar Semiconductor, Inc. All rights reserved.
// All software, firmware and related documentation herein ("MStar Software") are
// intellectual property of MStar Semiconductor, Inc. ("MStar") and protected by
// law, including, but not limited to, copyright law and international treaties.
// Any use, modification, reproduction, retransmission, or republication of all 
// or part of MStar Software is expressly prohibited, unless prior written 
// permission has been granted by MStar. 
//
// By accessing, browsing and/or using MStar Software, you acknowledge that you
// have read, understood, and agree, to be bound by below terms ("Terms") and to
// comply with all applicable laws and regulations:
//
// 1. MStar shall retain any and all right, ownership and interest to MStar
//    Software and any modification/derivatives thereof.
//    No right, ownership, or interest to MStar Software and any
//    modification/derivatives thereof is transferred to you under Terms.
//
// 2. You understand that MStar Software might include, incorporate or be
//    supplied together with third party`s software and the use of MStar
//    Software may require additional licenses from third parties.  
//    Therefore, you hereby agree it is your sole responsibility to separately
//    obtain any and all third party right and license necessary for your use of
//    such third party`s software. 
//
// 3. MStar Software and any modification/derivatives thereof shall be deemed as
//    MStar`s confidential information and you agree to keep MStar`s 
//    confidential information in strictest confidence and not disclose to any
//    third party.  
//
// 4. MStar Software is provided on an "AS IS" basis without warranties of any
//    kind. Any warranties are hereby expressly disclaimed by MStar, including
//    without limitation, any warranties of merchantability, non-infringement of
//    intellectual property rights, fitness for a particular purpose, error free
//    and in conformity with any international standard.  You agree to waive any
//    claim against MStar for any loss, damage, cost or expense that you may
//    incur related to your use of MStar Software.
//    In no event shall MStar be liable for any direct, indirect, incidental or
//    consequential damages, including without limitation, lost of profit or
//    revenues, lost or damage of data, and unauthorized system use.
//    You agree that this Section 4 shall still apply without being affected
//    even if MStar Software has been modified by MStar in accordance with your
//    request or instruction for your use, except otherwise agreed by both
//    parties in writing.
//
// 5. If requested, MStar may from time to time provide technical supports or
//    services in relation with MStar Software to you for your use of
//    MStar Software in conjunction with your or your customer`s product
//    ("Services").
//    You understand and agree that, except otherwise agreed by both parties in
//    writing, Services are provided on an "AS IS" basis and the warranty
//    disclaimer set forth in Section 4 above shall apply.  
//
// 6. Nothing contained herein shall be construed as by implication, estoppels
//    or otherwise:
//    (a) conferring any license or right to use MStar name, trademark, service
//        mark, symbol or any other identification;
//    (b) obligating MStar or any of its affiliates to furnish any person,
//        including without limitation, you and your customers, any assistance
//        of any kind whatsoever, or any information; or 
//    (c) conferring any license or right under any intellectual property right.
//
// 7. These terms shall be governed by and construed in accordance with the laws
//    of Taiwan, R.O.C., excluding its conflict of law rules.
//    Any and all dispute arising out hereof or related hereto shall be finally
//    settled by arbitration referred to the Chinese Arbitration Association,
//    Taipei in accordance with the ROC Arbitration Law and the Arbitration
//    Rules of the Association by three (3) arbitrators appointed in accordance
//    with the said Rules.
//    The place of arbitration shall be in Taipei, Taiwan and the language shall
//    be English.  
//    The arbitration award shall be final and binding to both parties.
//
//******************************************************************************
//<MStar Software>

// This file is generated by script, please do not edit it directly
#ifndef _MST6500JL_H_
#define _MST6500JL_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PIN_1 PAD_HOTPLUGB
#define PAD_HOTPLUGB 21
#define GPIO_PAD_21 GPIO20
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO PIN_1_IS_GPIO
#endif

#define PIN_9 PAD_DDCDB_DA
#define PAD_DDCDB_DA 27
#define GPIO_PAD_27 GPIO26
#ifndef PIN_9_IS_GPIO
#define PIN_9_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO PIN_9_IS_GPIO
#endif

#define PIN_12 PAD_DDCDB_CK
#define PAD_DDCDB_CK 26
#define GPIO_PAD_26 GPIO25
#ifndef PIN_12_IS_GPIO
#define PIN_12_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO PIN_12_IS_GPIO
#endif

#define PIN_17 PAD_DDCDA_DA
#define PAD_DDCDA_DA 25
#define GPIO_PAD_25 GPIO24
#ifndef PIN_17_IS_GPIO
#define PIN_17_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO PIN_17_IS_GPIO
#endif

#define PIN_20 PAD_DDCDA_CK
#define PAD_DDCDA_CK 24
#define GPIO_PAD_24 GPIO23
#ifndef PIN_20_IS_GPIO
#define PIN_20_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO PIN_20_IS_GPIO
#endif

#define PIN_91 PAD_TGPIO0
#define PAD_TGPIO0 74
#define GPIO_PAD_74 GPIO73
#ifndef PIN_91_IS_GPIO
#define PIN_91_IS_GPIO 0
#endif
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO PIN_91_IS_GPIO
#endif

#define PAD_TGPIO1 9999
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO 0
#endif

#define PIN_92 PAD_TGPIO2
#define PAD_TGPIO2 76
#define GPIO_PAD_76 GPIO75
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO 0
#endif
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO PIN_92_IS_GPIO
#endif

#define PIN_93 PAD_TGPIO3
#define PAD_TGPIO3 77
#define GPIO_PAD_77 GPIO76
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO 0
#endif
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO PIN_93_IS_GPIO
#endif

#define PIN_97 PAD_TS0_D0
#define PAD_TS0_D0 78
#define GPIO_PAD_78 GPIO77
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO PIN_97_IS_GPIO
#endif

#define PAD_TS0_D1 9999
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO 0
#endif

#define PAD_TS1_CLK 9999
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO 0
#endif

#define PIN_98 PAD_TS0_D2
#define PAD_TS0_D2 80
#define GPIO_PAD_80 GPIO79
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO PIN_98_IS_GPIO
#endif

#define PAD_TS1_SYNC 9999
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO 0
#endif

#define PAD_TS0_D3 9999
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO 0
#endif

#define PAD_TS1_VLD 9999
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO 0
#endif

#define PIN_99 PAD_TS0_D4
#define PAD_TS0_D4 82
#define GPIO_PAD_82 GPIO81
#ifndef PIN_99_IS_GPIO
#define PIN_99_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO PIN_99_IS_GPIO
#endif

#define PAD_TS0_D5 9999
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO 0
#endif

#define PAD_TS1_D7 9999
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO 0
#endif

#define PAD_TS0_D6 9999
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO 0
#endif

#define PAD_TS0_D7 9999
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO 0
#endif

#define PAD_TS1_D6 9999
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO 0
#endif

#define PIN_100 PAD_TS0_VLD
#define PAD_TS0_VLD 86
#define GPIO_PAD_86 GPIO85
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO PIN_100_IS_GPIO
#endif

#define PAD_TS1_D5 9999
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO 0
#endif

#define PIN_101 PAD_TS0_SYNC
#define PAD_TS0_SYNC 87
#define GPIO_PAD_87 GPIO86
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO PIN_101_IS_GPIO
#endif

#define PAD_TS1_D4 9999
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO 0
#endif

#define PIN_102 PAD_TS0_CLK
#define PAD_TS0_CLK 88
#define GPIO_PAD_88 GPIO87
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO PIN_102_IS_GPIO
#endif

#define PAD_TS1_D3 9999
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO 0
#endif

#define PAD_TS1_D2 9999
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO 0
#endif

#define PIN_103 PAD_DDCDC_DA
#define PAD_DDCDC_DA 29
#define GPIO_PAD_29 GPIO28
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO PIN_103_IS_GPIO
#endif

#define PAD_TS1_D1 9999
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO 0
#endif

#define PIN_104 PAD_DDCDC_CK
#define PAD_DDCDC_CK 28
#define GPIO_PAD_28 GPIO27
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO PIN_104_IS_GPIO
#endif

#define PAD_TS1_D0 9999
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO 0
#endif

#define PIN_112 PAD_HOTPLUGC
#define PAD_HOTPLUGC 22
#define GPIO_PAD_22 GPIO21
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO PIN_112_IS_GPIO
#endif

#define PIN_118 PAD_B_ODD0
#define PAD_B_ODD0 187
#define GPIO_PAD_187 GPIO186
#ifndef PIN_118_IS_GPIO
#define PIN_118_IS_GPIO 0
#endif
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO PIN_118_IS_GPIO
#endif

#define PIN_119 PAD_B_ODD1
#define PAD_B_ODD1 188
#define GPIO_PAD_188 GPIO187
#ifndef PIN_119_IS_GPIO
#define PIN_119_IS_GPIO 0
#endif
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO PIN_119_IS_GPIO
#endif

#define PIN_120 PAD_B_ODD2
#define PAD_B_ODD2 189
#define GPIO_PAD_189 GPIO188
#ifndef PIN_120_IS_GPIO
#define PIN_120_IS_GPIO 0
#endif
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_120_IS_GPIO
#endif

#define PIN_121 PAD_B_ODD3
#define PAD_B_ODD3 190
#define GPIO_PAD_190 GPIO189
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_121_IS_GPIO
#endif

#define PIN_122 PAD_B_ODD4
#define PAD_B_ODD4 191
#define GPIO_PAD_191 GPIO190
#ifndef PIN_122_IS_GPIO
#define PIN_122_IS_GPIO 0
#endif
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO PIN_122_IS_GPIO
#endif

#define PIN_123 PAD_B_ODD5
#define PAD_B_ODD5 192
#define GPIO_PAD_192 GPIO191
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO PIN_123_IS_GPIO
#endif

#define PIN_124 PAD_B_ODD6
#define PAD_B_ODD6 193
#define GPIO_PAD_193 GPIO192
#ifndef PIN_124_IS_GPIO
#define PIN_124_IS_GPIO 0
#endif
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_124_IS_GPIO
#endif

#define PIN_125 PAD_B_ODD7
#define PAD_B_ODD7 194
#define GPIO_PAD_194 GPIO193
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_125_IS_GPIO
#endif

#define PIN_126 PAD_G_ODD0
#define PAD_G_ODD0 195
#define GPIO_PAD_195 GPIO194
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_126_IS_GPIO
#endif

#define PIN_127 PAD_G_ODD1
#define PAD_G_ODD1 196
#define GPIO_PAD_196 GPIO195
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_127_IS_GPIO
#endif

#define PIN_128 PAD_G_ODD2
#define PAD_G_ODD2 197
#define GPIO_PAD_197 GPIO196
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_128_IS_GPIO
#endif

#define PIN_129 PAD_G_ODD3
#define PAD_G_ODD3 198
#define GPIO_PAD_198 GPIO197
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_129_IS_GPIO
#endif

#define PIN_131 PAD_G_ODD4
#define PAD_G_ODD4 199
#define GPIO_PAD_199 GPIO198
#ifndef PIN_131_IS_GPIO
#define PIN_131_IS_GPIO 0
#endif
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_131_IS_GPIO
#endif

#define PIN_132 PAD_G_ODD5
#define PAD_G_ODD5 200
#define GPIO_PAD_200 GPIO199
#ifndef PIN_132_IS_GPIO
#define PIN_132_IS_GPIO 0
#endif
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_132_IS_GPIO
#endif

#define PIN_133 PAD_G_ODD6
#define PAD_G_ODD6 201
#define GPIO_PAD_201 GPIO200
#ifndef PIN_133_IS_GPIO
#define PIN_133_IS_GPIO 0
#endif
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO PIN_133_IS_GPIO
#endif

#define PIN_134 PAD_G_ODD7
#define PAD_G_ODD7 202
#define GPIO_PAD_202 GPIO201
#ifndef PIN_134_IS_GPIO
#define PIN_134_IS_GPIO 0
#endif
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO PIN_134_IS_GPIO
#endif

#define PIN_135 PAD_R_ODD0
#define PAD_R_ODD0 203
#define GPIO_PAD_203 GPIO202
#ifndef PIN_135_IS_GPIO
#define PIN_135_IS_GPIO 0
#endif
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_135_IS_GPIO
#endif

#define PIN_136 PAD_R_ODD1
#define PAD_R_ODD1 204
#define GPIO_PAD_204 GPIO203
#ifndef PIN_136_IS_GPIO
#define PIN_136_IS_GPIO 0
#endif
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_136_IS_GPIO
#endif

#define PIN_137 PAD_R_ODD2
#define PAD_R_ODD2 205
#define GPIO_PAD_205 GPIO204
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO PIN_137_IS_GPIO
#endif

#define PIN_138 PAD_R_ODD3
#define PAD_R_ODD3 206
#define GPIO_PAD_206 GPIO205
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO PIN_138_IS_GPIO
#endif

#define PIN_139 PAD_R_ODD4
#define PAD_R_ODD4 207
#define GPIO_PAD_207 GPIO206
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO PIN_139_IS_GPIO
#endif

#define PIN_140 PAD_R_ODD5
#define PAD_R_ODD5 208
#define GPIO_PAD_208 GPIO207
#ifndef PIN_140_IS_GPIO
#define PIN_140_IS_GPIO 0
#endif
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO PIN_140_IS_GPIO
#endif

#define PIN_141 PAD_R_ODD6
#define PAD_R_ODD6 209
#define GPIO_PAD_209 GPIO208
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO PIN_141_IS_GPIO
#endif

#define PIN_142 PAD_R_ODD7
#define PAD_R_ODD7 210
#define GPIO_PAD_210 GPIO209
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO PIN_142_IS_GPIO
#endif

#define PAD_mini_LVDS0 9999
#ifndef PAD_mini_LVDS0_IS_GPIO
#define PAD_mini_LVDS0_IS_GPIO 0
#endif

#define PAD_mini_LVDS1 9999
#ifndef PAD_mini_LVDS1_IS_GPIO
#define PAD_mini_LVDS1_IS_GPIO 0
#endif

#define PAD_mini_LVDS2 9999
#ifndef PAD_mini_LVDS2_IS_GPIO
#define PAD_mini_LVDS2_IS_GPIO 0
#endif

#define PAD_mini_LVDS3 9999
#ifndef PAD_mini_LVDS3_IS_GPIO
#define PAD_mini_LVDS3_IS_GPIO 0
#endif

#define PAD_mini_LVDS4 9999
#ifndef PAD_mini_LVDS4_IS_GPIO
#define PAD_mini_LVDS4_IS_GPIO 0
#endif

#define PAD_mini_LVDS5 9999
#ifndef PAD_mini_LVDS5_IS_GPIO
#define PAD_mini_LVDS5_IS_GPIO 0
#endif

#define PAD_mini_LVDS6 9999
#ifndef PAD_mini_LVDS6_IS_GPIO
#define PAD_mini_LVDS6_IS_GPIO 0
#endif

#define PAD_mini_LVDS7 9999
#ifndef PAD_mini_LVDS7_IS_GPIO
#define PAD_mini_LVDS7_IS_GPIO 0
#endif

#define PAD_LCK 9999
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO 0
#endif

#define PAD_LDE 9999
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO 0
#endif

#define PAD_LHSYNC 9999
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO 0
#endif

#define PAD_LVSYNC 9999
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO 0
#endif

#define PAD_TCON8 9999
#ifndef PAD_TCON8_IS_GPIO
#define PAD_TCON8_IS_GPIO 0
#endif

#define PIN_144 PAD_TCON0
#define PAD_TCON0 144
#define GPIO_PAD_144 GPIO143
#ifndef PIN_144_IS_GPIO
#define PIN_144_IS_GPIO 0
#endif
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO PIN_144_IS_GPIO
#endif

#define PAD_TCON9 9999
#ifndef PAD_TCON9_IS_GPIO
#define PAD_TCON9_IS_GPIO 0
#endif

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif

#define PAD_TCON10 9999
#ifndef PAD_TCON10_IS_GPIO
#define PAD_TCON10_IS_GPIO 0
#endif

#define PIN_145 PAD_TCON2
#define PAD_TCON2 146
#define GPIO_PAD_146 GPIO145
#ifndef PIN_145_IS_GPIO
#define PIN_145_IS_GPIO 0
#endif
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO PIN_145_IS_GPIO
#endif

#define PAD_TCON11 9999
#ifndef PAD_TCON11_IS_GPIO
#define PAD_TCON11_IS_GPIO 0
#endif

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif

#define PAD_TCON12 9999
#ifndef PAD_TCON12_IS_GPIO
#define PAD_TCON12_IS_GPIO 0
#endif

#define PIN_146 PAD_TCON4
#define PAD_TCON4 148
#define GPIO_PAD_148 GPIO147
#ifndef PIN_146_IS_GPIO
#define PIN_146_IS_GPIO 0
#endif
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO PIN_146_IS_GPIO
#endif

#define PAD_TCON13 9999
#ifndef PAD_TCON13_IS_GPIO
#define PAD_TCON13_IS_GPIO 0
#endif

#define PAD_TCON5 9999
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO 0
#endif

#define PAD_TCON14 9999
#ifndef PAD_TCON14_IS_GPIO
#define PAD_TCON14_IS_GPIO 0
#endif

#define PIN_148 PAD_TCON6
#define PAD_TCON6 150
#define GPIO_PAD_150 GPIO149
#ifndef PIN_148_IS_GPIO
#define PIN_148_IS_GPIO 0
#endif
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO PIN_148_IS_GPIO
#endif

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif

#define PAD_TCON15 9999
#ifndef PAD_TCON15_IS_GPIO
#define PAD_TCON15_IS_GPIO 0
#endif

#define PIN_149 PAD_PWM0
#define PAD_PWM0 67
#define GPIO_PAD_67 GPIO66
#ifndef PIN_149_IS_GPIO
#define PIN_149_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_149_IS_GPIO
#endif

#define PAD_TCON16 9999
#ifndef PAD_TCON16_IS_GPIO
#define PAD_TCON16_IS_GPIO 0
#endif

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif

#define PAD_TCON17 9999
#ifndef PAD_TCON17_IS_GPIO
#define PAD_TCON17_IS_GPIO 0
#endif

#define PIN_150 PAD_PWM1
#define PAD_PWM1 68
#define GPIO_PAD_68 GPIO67
#ifndef PIN_150_IS_GPIO
#define PIN_150_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_150_IS_GPIO
#endif

#define PAD_TCON18 9999
#ifndef PAD_TCON18_IS_GPIO
#define PAD_TCON18_IS_GPIO 0
#endif

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif

#define PIN_151 PAD_PWM2
#define PAD_PWM2 69
#define GPIO_PAD_69 GPIO68
#ifndef PIN_151_IS_GPIO
#define PIN_151_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO PIN_151_IS_GPIO
#endif

#define PAD_TCON19 9999
#ifndef PAD_TCON19_IS_GPIO
#define PAD_TCON19_IS_GPIO 0
#endif

#define PAD_PCM_A10 9999
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO 0
#endif

#define PAD_TCON20 9999
#ifndef PAD_TCON20_IS_GPIO
#define PAD_TCON20_IS_GPIO 0
#endif

#define PAD_PCM_OE_N 9999
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO 0
#endif

#define PAD_TCON21 9999
#ifndef PAD_TCON21_IS_GPIO
#define PAD_TCON21_IS_GPIO 0
#endif

#define PIN_152 PAD_DDCR_CK
#define PAD_DDCR_CK 73
#define GPIO_PAD_73 GPIO72
#ifndef PIN_152_IS_GPIO
#define PIN_152_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO PIN_152_IS_GPIO
#endif

#define PAD_PCM_D3 9999
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO 0
#endif

#define PAD_PCM_D4 9999
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO 0
#endif

#define PAD_PCM2_IRQA_N 9999
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#endif

#define PAD_PCM_D5 9999
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO 0
#endif

#define PIN_153 PAD_DDCR_DA
#define PAD_DDCR_DA 72
#define GPIO_PAD_72 GPIO71
#ifndef PIN_153_IS_GPIO
#define PIN_153_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO PIN_153_IS_GPIO
#endif

#define PAD_PCM_D6 9999
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO 0
#endif

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif

#define PAD_PCM_D7 9999
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO 0
#endif

#define PIN_154 PAD_PF_AD15
#define PAD_PF_AD15 137
#define GPIO_PAD_137 GPIO136
#ifndef PIN_154_IS_GPIO
#define PIN_154_IS_GPIO 0
#endif
#ifndef PAD_PF_AD15_IS_GPIO
#define PAD_PF_AD15_IS_GPIO PIN_154_IS_GPIO
#endif

#define PAD_PCM_CE_N 9999
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO 0
#endif

#define PAD_PF_ALE 9999
#ifndef PAD_PF_ALE_IS_GPIO
#define PAD_PF_ALE_IS_GPIO 0
#endif

#define PIN_155 PAD_PF_CE0Z
#define PAD_PF_CE0Z 138
#define GPIO_PAD_138 GPIO137
#ifndef PIN_155_IS_GPIO
#define PIN_155_IS_GPIO 0
#endif
#ifndef PAD_PF_CE0Z_IS_GPIO
#define PAD_PF_CE0Z_IS_GPIO PIN_155_IS_GPIO
#endif

#define PAD_PCM_A11 9999
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO 0
#endif

#define PAD_PF_CE1Z 9999
#ifndef PAD_PF_CE1Z_IS_GPIO
#define PAD_PF_CE1Z_IS_GPIO 0
#endif

#define PAD_PCM_IORD_N 9999
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO 0
#endif

#define PIN_156 PAD_PF_OEZ
#define PAD_PF_OEZ 140
#define GPIO_PAD_140 GPIO139
#ifndef PIN_156_IS_GPIO
#define PIN_156_IS_GPIO 0
#endif
#ifndef PAD_PF_OEZ_IS_GPIO
#define PAD_PF_OEZ_IS_GPIO PIN_156_IS_GPIO
#endif

#define PAD_PCM_A9 9999
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO 0
#endif

#define PAD_PCM_IOWR_N 9999
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO 0
#endif

#define PAD_PF_WEZ 9999
#ifndef PAD_PF_WEZ_IS_GPIO
#define PAD_PF_WEZ_IS_GPIO 0
#endif

#define PAD_PCM_A8 9999
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO 0
#endif

#define PIN_157 PAD_F_RBZ
#define PAD_F_RBZ 143
#define GPIO_PAD_143 GPIO142
#ifndef PIN_157_IS_GPIO
#define PIN_157_IS_GPIO 0
#endif
#ifndef PAD_F_RBZ_IS_GPIO
#define PAD_F_RBZ_IS_GPIO PIN_157_IS_GPIO
#endif

#define PAD_PCM_A3 9999
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO 0
#endif

#define PIN_158 PAD_PCM_A2
#define PAD_PCM_A2 123
#define GPIO_PAD_123 GPIO122
#ifndef PIN_158_IS_GPIO
#define PIN_158_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO PIN_158_IS_GPIO
#endif

#define PAD_PCM_A13 9999
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO 0
#endif

#define PAD_PCM_REG_N 9999
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO 0
#endif

#define PAD_PCM_A14 9999
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO 0
#endif

#define PIN_159 PAD_PCM_A1
#define PAD_PCM_A1 125
#define GPIO_PAD_125 GPIO124
#ifndef PIN_159_IS_GPIO
#define PIN_159_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO PIN_159_IS_GPIO
#endif

#define PAD_PCM_WE_N 9999
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO 0
#endif

#define PAD_PCM_A0 9999
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO 0
#endif

#define PAD_PCM_IRQA_N 9999
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO 0
#endif

#define PIN_160 PAD_PCM_D0
#define PAD_PCM_D0 127
#define GPIO_PAD_127 GPIO126
#ifndef PIN_160_IS_GPIO
#define PIN_160_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO PIN_160_IS_GPIO
#endif

#define PAD_PCM_A12 9999
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO 0
#endif

#define PAD_PCM_D1 9999
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO 0
#endif

#define PAD_PCM_A7 9999
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO 0
#endif

#define PIN_161 PAD_PCM_D2
#define PAD_PCM_D2 129
#define GPIO_PAD_129 GPIO128
#ifndef PIN_161_IS_GPIO
#define PIN_161_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO PIN_161_IS_GPIO
#endif

#define PAD_PCM_A6 9999
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO 0
#endif

#define PAD_PCM_A5 9999
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO 0
#endif

#define PIN_164 PAD_PCM_RESET
#define PAD_PCM_RESET 130
#define GPIO_PAD_130 GPIO129
#ifndef PIN_164_IS_GPIO
#define PIN_164_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO PIN_164_IS_GPIO
#endif

#define PAD_PCM_WAIT_N 9999
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO 0
#endif

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif

#define PAD_PCM_A4 9999
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO 0
#endif

#define PAD_UART_RX2 9999
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO 0
#endif

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif

#define PAD_UART_TX2 9999
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO 0
#endif

#define PAD_PCM_CD_N 9999
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO 0
#endif

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif

#define PAD_ET_MDC 9999
#ifndef PAD_ET_MDC_IS_GPIO
#define PAD_ET_MDC_IS_GPIO 0
#endif

#define PIN_223 PAD_ET_COL
#define PAD_ET_COL 166
#define GPIO_PAD_166 GPIO165
#ifndef PIN_223_IS_GPIO
#define PIN_223_IS_GPIO 0
#endif
#ifndef PAD_ET_COL_IS_GPIO
#define PAD_ET_COL_IS_GPIO PIN_223_IS_GPIO
#endif

#define PAD_ET_MDIO 9999
#ifndef PAD_ET_MDIO_IS_GPIO
#define PAD_ET_MDIO_IS_GPIO 0
#endif

#define PAD_ET_TXD1 9999
#ifndef PAD_ET_TXD1_IS_GPIO
#define PAD_ET_TXD1_IS_GPIO 0
#endif

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif

#define PAD_ET_TXD0 9999
#ifndef PAD_ET_TXD0_IS_GPIO
#define PAD_ET_TXD0_IS_GPIO 0
#endif

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif

#define PAD_ET_TX_EN 9999
#ifndef PAD_ET_TX_EN_IS_GPIO
#define PAD_ET_TX_EN_IS_GPIO 0
#endif

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif

#define PAD_ET_TX_CLK 9999
#ifndef PAD_ET_TX_CLK_IS_GPIO
#define PAD_ET_TX_CLK_IS_GPIO 0
#endif

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif

#define PAD_ET_RXD0 9999
#ifndef PAD_ET_RXD0_IS_GPIO
#define PAD_ET_RXD0_IS_GPIO 0
#endif

#define PAD_ET_RXD1 9999
#ifndef PAD_ET_RXD1_IS_GPIO
#define PAD_ET_RXD1_IS_GPIO 0
#endif

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif

#define PIN_224 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 175
#define GPIO_PAD_175 GPIO174
#ifndef PIN_224_IS_GPIO
#define PIN_224_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO PIN_224_IS_GPIO
#endif

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif

#define PAD_I2S_IN_BCK 9999
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO 0
#endif

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif

#define PIN_225 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 177
#define GPIO_PAD_177 GPIO176
#ifndef PIN_225_IS_GPIO
#define PIN_225_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO PIN_225_IS_GPIO
#endif

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif

#define PIN_226 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 180
#define GPIO_PAD_180 GPIO179
#ifndef PIN_226_IS_GPIO
#define PIN_226_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO PIN_226_IS_GPIO
#endif

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif

#define PAD_SPDIF_IN 9999
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO 0
#endif

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif

#define PIN_227 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 181
#define GPIO_PAD_181 GPIO180
#ifndef PIN_227_IS_GPIO
#define PIN_227_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO PIN_227_IS_GPIO
#endif

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif

#define PIN_228 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 182
#define GPIO_PAD_182 GPIO181
#ifndef PIN_228_IS_GPIO
#define PIN_228_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO PIN_228_IS_GPIO
#endif

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif

#define PIN_230 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 183
#define GPIO_PAD_183 GPIO182
#ifndef PIN_230_IS_GPIO
#define PIN_230_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO PIN_230_IS_GPIO
#endif

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif

#define PIN_231 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 179
#define GPIO_PAD_179 GPIO178
#ifndef PIN_231_IS_GPIO
#define PIN_231_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO PIN_231_IS_GPIO
#endif

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif

#define PIN_239 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 2
#define GPIO_PAD_2 GPIO1
#ifndef PIN_239_IS_GPIO
#define PIN_239_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO PIN_239_IS_GPIO
#endif

#define PIN_240 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef PIN_240_IS_GPIO
#define PIN_240_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO PIN_240_IS_GPIO
#endif

#define PIN_241 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 4
#define GPIO_PAD_4 GPIO3
#ifndef PIN_241_IS_GPIO
#define PIN_241_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO PIN_241_IS_GPIO
#endif

#define PIN_242 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 1
#define GPIO_PAD_1 GPIO0
#ifndef PIN_242_IS_GPIO
#define PIN_242_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO PIN_242_IS_GPIO
#endif

#define PIN_243 PAD_SAR0
#define PAD_SAR0 32
#define GPIO_PAD_32 GPIO31
#ifndef PIN_243_IS_GPIO
#define PIN_243_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_243_IS_GPIO
#endif

#define PIN_244 PAD_SAR1
#define PAD_SAR1 33
#define GPIO_PAD_33 GPIO32
#ifndef PIN_244_IS_GPIO
#define PIN_244_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_244_IS_GPIO
#endif

#define PIN_245 PAD_SAR2
#define PAD_SAR2 34
#define GPIO_PAD_34 GPIO33
#ifndef PIN_245_IS_GPIO
#define PIN_245_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO PIN_245_IS_GPIO
#endif

#define PIN_246 PAD_SAR3
#define PAD_SAR3 35
#define GPIO_PAD_35 GPIO34
#ifndef PIN_246_IS_GPIO
#define PIN_246_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO PIN_246_IS_GPIO
#endif

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif

#define PIN_247 PAD_HOTPLUGA
#define PAD_HOTPLUGA 20
#define GPIO_PAD_20 GPIO19
#ifndef PIN_247_IS_GPIO
#define PIN_247_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO PIN_247_IS_GPIO
#endif

#define PAD_HOTPLUGD 9999
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO 0
#endif

#define PAD_GPIO_PM0 9999
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO 0
#endif

#define PAD_GPIO_PM11 9999
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO 0
#endif

#define PIN_250 PAD_GPIO_PM1
#define PAD_GPIO_PM1 8
#define GPIO_PAD_8 GPIO7
#ifndef PIN_250_IS_GPIO
#define PIN_250_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO PIN_250_IS_GPIO
#endif

#define PAD_GPIO_PM2 9999
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO 0
#endif

#define PIN_251 PAD_GPIO_PM4
#define PAD_GPIO_PM4 11
#define GPIO_PAD_11 GPIO10
#ifndef PIN_251_IS_GPIO
#define PIN_251_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO PIN_251_IS_GPIO
#endif

#define PAD_GPIO_PM12 9999
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO 0
#endif

#define PIN_252 PAD_GPIO_PM5
#define PAD_GPIO_PM5 12
#define GPIO_PAD_12 GPIO11
#ifndef PIN_252_IS_GPIO
#define PIN_252_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO PIN_252_IS_GPIO
#endif

#define PAD_GPIO_PM3 9999
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO 0
#endif

#define PIN_253 PAD_GPIO_PM6
#define PAD_GPIO_PM6 13
#define GPIO_PAD_13 GPIO12
#ifndef PIN_253_IS_GPIO
#define PIN_253_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO PIN_253_IS_GPIO
#endif

#define PAD_GPIO_PM7 9999
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO 0
#endif

#define PIN_254 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef PIN_254_IS_GPIO
#define PIN_254_IS_GPIO 0
#endif
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO PIN_254_IS_GPIO
#endif

#define PAD_GPIO_PM8 9999
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO 0
#endif

#define PIN_255 PAD_CEC
#define PAD_CEC 6
#define GPIO_PAD_6 GPIO5
#ifndef PIN_255_IS_GPIO
#define PIN_255_IS_GPIO 0
#endif
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO PIN_255_IS_GPIO
#endif

#define PAD_GPIO_PM9 9999
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO 0
#endif

#define PAD_GPIO_PM10 9999
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO 0
#endif

#define PAD_DDCDD_DA 9999
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO 0
#endif

#define PAD_DDCDD_CK 9999
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO 0
#endif


// specify case
#define PAD_MPIF_D3 9999
#ifndef PAD_MPIF_D3_IS_GPIO
#define PAD_MPIF_D3_IS_GPIO 0
#endif

#define PAD_DDCA_DA 9999
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO 0
#endif

#define PAD_DDCA_CK 9999
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_Ck_IS_GPIO 0
#endif



// PADS group name to index
#define PADS_PCMCONFIG_MODE1 1223
#define PADS_PCMCONFIG_MODE2 1224
#define PADS_PCMCONFIG1_MODE1 1225
#define PADS_PCMCONFIG1_MODE2 1226
#define PADS_PCMCONFIG1_MODE3 1227
#define PADS_PCM2CONFIG_MODE1 1228
#define PADS_PCM2CONFIG_MODE2 1229
#define PADS_PCM2CONFIG_MODE3 1230
#define PADS_PCM2CONFIG1_MODE1 1231
#define PADS_PCM2CONFIG1_MODE2 1232
#define PADS_ET_MODE1   1233
#define PADS_ET_MODE2   1234
#define PADS_DDCR       1235
#define PADS_DDCR2      1236
#define PADS_PCM        1237

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             0
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            0
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7

#endif /* _MST6500JL_H_*/
