////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD7C77_H_
#define _MSD7C77_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_J1 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_J1_IS_GPIO
#endif 

#define BALL_H3 PAD_I2S_OUT_MUTE
#define PAD_I2S_OUT_MUTE 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO BALL_H3_IS_GPIO
#endif 

#define BALL_K5 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_K5_IS_GPIO
#endif 

#define BALL_J2 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_J2_IS_GPIO
#endif 

#define BALL_K4 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_K4_IS_GPIO
#define BALL_K4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_K4_IS_GPIO
#endif 

#define BALL_K1 PAD_I2S_OUT_SDO
#define PAD_I2S_OUT_SDO 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_K1_IS_GPIO
#define BALL_K1_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SDO_IS_GPIO
#define PAD_I2S_OUT_SDO_IS_GPIO BALL_K1_IS_GPIO
#endif 

#define BALL_H2 PAD_GPIO0
#define PAD_GPIO0 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_H2_IS_GPIO
#endif 

#define BALL_J3 PAD_GPIO1
#define PAD_GPIO1 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_J3_IS_GPIO
#endif 

#define BALL_K3 PAD_PM_GPIO0
#define PAD_PM_GPIO0 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_K3_IS_GPIO
#endif 

#define BALL_J5 PAD_PM_GPIO1
#define PAD_PM_GPIO1 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define BALL_K2 PAD_PM_GPIO2
#define PAD_PM_GPIO2 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO BALL_K2_IS_GPIO
#endif 

#define BALL_L3 PAD_PM_GPIO3
#define PAD_PM_GPIO3 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO BALL_L3_IS_GPIO
#endif 

#define BALL_J4 PAD_PM_GPIO4
#define PAD_PM_GPIO4 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_J4_IS_GPIO
#endif 

#define BALL_L2 PAD_PM_GPIO5
#define PAD_PM_GPIO5 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_L2_IS_GPIO
#define BALL_L2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO BALL_L2_IS_GPIO
#endif 

#define BALL_Y17 PAD_SM0_CLK
#define PAD_SM0_CLK 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_Y17_IS_GPIO
#define BALL_Y17_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO BALL_Y17_IS_GPIO
#endif 

#define BALL_Y18 PAD_SM0_RST
#define PAD_SM0_RST 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO BALL_Y18_IS_GPIO
#endif 

#define BALL_AA17 PAD_SM0_C4
#define PAD_SM0_C4 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO BALL_AA17_IS_GPIO
#endif 

#define BALL_AB17 PAD_SM0_IO
#define PAD_SM0_IO 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_AB17_IS_GPIO
#define BALL_AB17_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO BALL_AB17_IS_GPIO
#endif 

#define BALL_AA16 PAD_SM0_C8
#define PAD_SM0_C8 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO BALL_AA16_IS_GPIO
#endif 

#define BALL_AB16 PAD_SM0_CD
#define PAD_SM0_CD 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_AB16_IS_GPIO
#define BALL_AB16_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO BALL_AB16_IS_GPIO
#endif 

#define BALL_AC16 PAD_SM0_GPIO
#define PAD_SM0_GPIO 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif 
#ifndef PAD_SM0_GPIO_IS_GPIO
#define PAD_SM0_GPIO_IS_GPIO BALL_AC16_IS_GPIO
#endif 

#define BALL_AA15 PAD_SM0_PCT
#define PAD_SM0_PCT 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_AA15_IS_GPIO
#define BALL_AA15_IS_GPIO 0
#endif 
#ifndef PAD_SM0_PCT_IS_GPIO
#define PAD_SM0_PCT_IS_GPIO BALL_AA15_IS_GPIO
#endif 

#define BALL_H18 PAD_T_GPIO0
#define PAD_T_GPIO0 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_H18_IS_GPIO
#define BALL_H18_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO0_IS_GPIO
#define PAD_T_GPIO0_IS_GPIO BALL_H18_IS_GPIO
#endif 

#define BALL_H19 PAD_T_GPIO1
#define PAD_T_GPIO1 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_H19_IS_GPIO
#define BALL_H19_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO1_IS_GPIO
#define PAD_T_GPIO1_IS_GPIO BALL_H19_IS_GPIO
#endif 

#define BALL_F20 PAD_T_GPIO2
#define PAD_T_GPIO2 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_F20_IS_GPIO
#define BALL_F20_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO2_IS_GPIO
#define PAD_T_GPIO2_IS_GPIO BALL_F20_IS_GPIO
#endif 

#define BALL_G19 PAD_T_GPIO3
#define PAD_T_GPIO3 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_G19_IS_GPIO
#define BALL_G19_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO3_IS_GPIO
#define PAD_T_GPIO3_IS_GPIO BALL_G19_IS_GPIO
#endif 

#define BALL_H20 PAD_T_GPIO4
#define PAD_T_GPIO4 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_H20_IS_GPIO
#define BALL_H20_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO4_IS_GPIO
#define PAD_T_GPIO4_IS_GPIO BALL_H20_IS_GPIO
#endif 

#define BALL_G18 PAD_T_GPIO5
#define PAD_T_GPIO5 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_G18_IS_GPIO
#define BALL_G18_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO5_IS_GPIO
#define PAD_T_GPIO5_IS_GPIO BALL_G18_IS_GPIO
#endif 

#define BALL_W18 PAD_FUART_RX
#define PAD_FUART_RX 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_W18_IS_GPIO
#define BALL_W18_IS_GPIO 0
#endif 
#ifndef PAD_FUART_RX_IS_GPIO
#define PAD_FUART_RX_IS_GPIO BALL_W18_IS_GPIO
#endif 

#define BALL_W17 PAD_FUART_TX
#define PAD_FUART_TX 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_W17_IS_GPIO
#define BALL_W17_IS_GPIO 0
#endif 
#ifndef PAD_FUART_TX_IS_GPIO
#define PAD_FUART_TX_IS_GPIO BALL_W17_IS_GPIO
#endif 

#define BALL_W19 PAD_FUART_CTS
#define PAD_FUART_CTS 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_W19_IS_GPIO
#define BALL_W19_IS_GPIO 0
#endif 
#ifndef PAD_FUART_CTS_IS_GPIO
#define PAD_FUART_CTS_IS_GPIO BALL_W19_IS_GPIO
#endif 

#define BALL_W20 PAD_FUART_RTS
#define PAD_FUART_RTS 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_W20_IS_GPIO
#define BALL_W20_IS_GPIO 0
#endif 
#ifndef PAD_FUART_RTS_IS_GPIO
#define PAD_FUART_RTS_IS_GPIO BALL_W20_IS_GPIO
#endif 

#define BALL_AB19 PAD_GPIO2
#define PAD_GPIO2 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_AB19_IS_GPIO
#endif 

#define BALL_Y20 PAD_GPIO3
#define PAD_GPIO3 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_Y20_IS_GPIO
#define BALL_Y20_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_Y20_IS_GPIO
#endif 

#define BALL_AA21 PAD_GPIO4
#define PAD_GPIO4 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_AA21_IS_GPIO
#define BALL_AA21_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_AA21_IS_GPIO
#endif 

#define BALL_AB22 PAD_GPIO5
#define PAD_GPIO5 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_AB22_IS_GPIO
#endif 

#define BALL_AA23 PAD_GPIO6
#define PAD_GPIO6 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_AA23_IS_GPIO
#define BALL_AA23_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO BALL_AA23_IS_GPIO
#endif 

#define BALL_AB21 PAD_GPIO9
#define PAD_GPIO9 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_AB21_IS_GPIO
#endif 

#define BALL_AB20 PAD_GPIO10
#define PAD_GPIO10 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_AB20_IS_GPIO
#define BALL_AB20_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO BALL_AB20_IS_GPIO
#endif 

#define BALL_AA20 PAD_GPIO11
#define PAD_GPIO11 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO BALL_AA20_IS_GPIO
#endif 

#define BALL_AA19 PAD_GPIO12
#define PAD_GPIO12 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_AA19_IS_GPIO
#endif 

#define BALL_AC19 PAD_GPIO13
#define PAD_GPIO13 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif 
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO BALL_AC19_IS_GPIO
#endif 

#define BALL_AA18 PAD_GPIO14
#define PAD_GPIO14 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_AA18_IS_GPIO
#define BALL_AA18_IS_GPIO 0
#endif 
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO BALL_AA18_IS_GPIO
#endif 

#define BALL_AC18 PAD_GPIO15
#define PAD_GPIO15 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif 
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO BALL_AC18_IS_GPIO
#endif 

#define BALL_AB18 PAD_GPIO16
#define PAD_GPIO16 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_AB18_IS_GPIO
#define BALL_AB18_IS_GPIO 0
#endif 
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO BALL_AB18_IS_GPIO
#endif 

#define BALL_U23 PAD_CI_A4
#define PAD_CI_A4 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_U23_IS_GPIO
#define BALL_U23_IS_GPIO 0
#endif 
#ifndef PAD_CI_A4_IS_GPIO
#define PAD_CI_A4_IS_GPIO BALL_U23_IS_GPIO
#endif 

#define BALL_U22 PAD_CI_A3
#define PAD_CI_A3 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_U22_IS_GPIO
#define BALL_U22_IS_GPIO 0
#endif 
#ifndef PAD_CI_A3_IS_GPIO
#define PAD_CI_A3_IS_GPIO BALL_U22_IS_GPIO
#endif 

#define BALL_V21 PAD_CI_A6
#define PAD_CI_A6 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif 
#ifndef PAD_CI_A6_IS_GPIO
#define PAD_CI_A6_IS_GPIO BALL_V21_IS_GPIO
#endif 

#define BALL_V23 PAD_CI_A5
#define PAD_CI_A5 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_V23_IS_GPIO
#define BALL_V23_IS_GPIO 0
#endif 
#ifndef PAD_CI_A5_IS_GPIO
#define PAD_CI_A5_IS_GPIO BALL_V23_IS_GPIO
#endif 

#define BALL_R22 PAD_CI_A0
#define PAD_CI_A0 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_R22_IS_GPIO
#define BALL_R22_IS_GPIO 0
#endif 
#ifndef PAD_CI_A0_IS_GPIO
#define PAD_CI_A0_IS_GPIO BALL_R22_IS_GPIO
#endif 

#define BALL_R21 PAD_CI_A1
#define PAD_CI_A1 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_R21_IS_GPIO
#define BALL_R21_IS_GPIO 0
#endif 
#ifndef PAD_CI_A1_IS_GPIO
#define PAD_CI_A1_IS_GPIO BALL_R21_IS_GPIO
#endif 

#define BALL_T22 PAD_CI_A2
#define PAD_CI_A2 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_T22_IS_GPIO
#define BALL_T22_IS_GPIO 0
#endif 
#ifndef PAD_CI_A2_IS_GPIO
#define PAD_CI_A2_IS_GPIO BALL_T22_IS_GPIO
#endif 

#define BALL_W22 PAD_CI_A7
#define PAD_CI_A7 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_W22_IS_GPIO
#define BALL_W22_IS_GPIO 0
#endif 
#ifndef PAD_CI_A7_IS_GPIO
#define PAD_CI_A7_IS_GPIO BALL_W22_IS_GPIO
#endif 

#define BALL_R20 PAD_CI_A8
#define PAD_CI_A8 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_R20_IS_GPIO
#define BALL_R20_IS_GPIO 0
#endif 
#ifndef PAD_CI_A8_IS_GPIO
#define PAD_CI_A8_IS_GPIO BALL_R20_IS_GPIO
#endif 

#define BALL_R19 PAD_CI_A9
#define PAD_CI_A9 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_R19_IS_GPIO
#define BALL_R19_IS_GPIO 0
#endif 
#ifndef PAD_CI_A9_IS_GPIO
#define PAD_CI_A9_IS_GPIO BALL_R19_IS_GPIO
#endif 

#define BALL_AC21 PAD_GPIO7
#define PAD_GPIO7 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_AC21_IS_GPIO
#define BALL_AC21_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_AC21_IS_GPIO
#endif 

#define BALL_AA22 PAD_GPIO8
#define PAD_GPIO8 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_AA22_IS_GPIO
#define BALL_AA22_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_AA22_IS_GPIO
#endif 

#define BALL_U20 PAD_CI_A10
#define PAD_CI_A10 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif 
#ifndef PAD_CI_A10_IS_GPIO
#define PAD_CI_A10_IS_GPIO BALL_U20_IS_GPIO
#endif 

#define BALL_T18 PAD_CI_A11
#define PAD_CI_A11 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_T18_IS_GPIO
#define BALL_T18_IS_GPIO 0
#endif 
#ifndef PAD_CI_A11_IS_GPIO
#define PAD_CI_A11_IS_GPIO BALL_T18_IS_GPIO
#endif 

#define BALL_W21 PAD_CI_A12
#define PAD_CI_A12 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif 
#ifndef PAD_CI_A12_IS_GPIO
#define PAD_CI_A12_IS_GPIO BALL_W21_IS_GPIO
#endif 

#define BALL_P18 PAD_CI_A13
#define PAD_CI_A13 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_P18_IS_GPIO
#define BALL_P18_IS_GPIO 0
#endif 
#ifndef PAD_CI_A13_IS_GPIO
#define PAD_CI_A13_IS_GPIO BALL_P18_IS_GPIO
#endif 

#define BALL_Y21 PAD_CI_A14
#define PAD_CI_A14 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif 
#ifndef PAD_CI_A14_IS_GPIO
#define PAD_CI_A14_IS_GPIO BALL_Y21_IS_GPIO
#endif 

#define BALL_Y19 PAD_CI_CDZ
#define PAD_CI_CDZ 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif 
#ifndef PAD_CI_CDZ_IS_GPIO
#define PAD_CI_CDZ_IS_GPIO BALL_Y19_IS_GPIO
#endif 

#define BALL_V17 PAD_CI_D3
#define PAD_CI_D3 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_V17_IS_GPIO
#define BALL_V17_IS_GPIO 0
#endif 
#ifndef PAD_CI_D3_IS_GPIO
#define PAD_CI_D3_IS_GPIO BALL_V17_IS_GPIO
#endif 

#define BALL_U18 PAD_CI_D4
#define PAD_CI_D4 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_U18_IS_GPIO
#define BALL_U18_IS_GPIO 0
#endif 
#ifndef PAD_CI_D4_IS_GPIO
#define PAD_CI_D4_IS_GPIO BALL_U18_IS_GPIO
#endif 

#define BALL_V18 PAD_CI_D5
#define PAD_CI_D5 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_V18_IS_GPIO
#define BALL_V18_IS_GPIO 0
#endif 
#ifndef PAD_CI_D5_IS_GPIO
#define PAD_CI_D5_IS_GPIO BALL_V18_IS_GPIO
#endif 

#define BALL_V19 PAD_CI_D6
#define PAD_CI_D6 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_V19_IS_GPIO
#define BALL_V19_IS_GPIO 0
#endif 
#ifndef PAD_CI_D6_IS_GPIO
#define PAD_CI_D6_IS_GPIO BALL_V19_IS_GPIO
#endif 

#define BALL_V20 PAD_CI_D7
#define PAD_CI_D7 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_V20_IS_GPIO
#define BALL_V20_IS_GPIO 0
#endif 
#ifndef PAD_CI_D7_IS_GPIO
#define PAD_CI_D7_IS_GPIO BALL_V20_IS_GPIO
#endif 

#define BALL_U17 PAD_CI_CEZ
#define PAD_CI_CEZ 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_U17_IS_GPIO
#define BALL_U17_IS_GPIO 0
#endif 
#ifndef PAD_CI_CEZ_IS_GPIO
#define PAD_CI_CEZ_IS_GPIO BALL_U17_IS_GPIO
#endif 

#define BALL_U19 PAD_CI_OEZ
#define PAD_CI_OEZ 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_U19_IS_GPIO
#define BALL_U19_IS_GPIO 0
#endif 
#ifndef PAD_CI_OEZ_IS_GPIO
#define PAD_CI_OEZ_IS_GPIO BALL_U19_IS_GPIO
#endif 

#define BALL_T19 PAD_CI_IORDZ
#define PAD_CI_IORDZ 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_T19_IS_GPIO
#define BALL_T19_IS_GPIO 0
#endif 
#ifndef PAD_CI_IORDZ_IS_GPIO
#define PAD_CI_IORDZ_IS_GPIO BALL_T19_IS_GPIO
#endif 

#define BALL_R18 PAD_CI_IOWRZ
#define PAD_CI_IOWRZ 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_R18_IS_GPIO
#define BALL_R18_IS_GPIO 0
#endif 
#ifndef PAD_CI_IOWRZ_IS_GPIO
#define PAD_CI_IOWRZ_IS_GPIO BALL_R18_IS_GPIO
#endif 

#define BALL_Y23 PAD_CI_WEZ
#define PAD_CI_WEZ 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_Y23_IS_GPIO
#define BALL_Y23_IS_GPIO 0
#endif 
#ifndef PAD_CI_WEZ_IS_GPIO
#define PAD_CI_WEZ_IS_GPIO BALL_Y23_IS_GPIO
#endif 

#define BALL_Y22 PAD_CI_IRQAZ
#define PAD_CI_IRQAZ 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif 
#ifndef PAD_CI_IRQAZ_IS_GPIO
#define PAD_CI_IRQAZ_IS_GPIO BALL_Y22_IS_GPIO
#endif 

#define BALL_V22 PAD_CI_RST
#define PAD_CI_RST 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_V22_IS_GPIO
#define BALL_V22_IS_GPIO 0
#endif 
#ifndef PAD_CI_RST_IS_GPIO
#define PAD_CI_RST_IS_GPIO BALL_V22_IS_GPIO
#endif 

#define BALL_U21 PAD_CI_WAITZ
#define PAD_CI_WAITZ 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_U21_IS_GPIO
#define BALL_U21_IS_GPIO 0
#endif 
#ifndef PAD_CI_WAITZ_IS_GPIO
#define PAD_CI_WAITZ_IS_GPIO BALL_U21_IS_GPIO
#endif 

#define BALL_T21 PAD_CI_REGZ
#define PAD_CI_REGZ 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_T21_IS_GPIO
#define BALL_T21_IS_GPIO 0
#endif 
#ifndef PAD_CI_REGZ_IS_GPIO
#define PAD_CI_REGZ_IS_GPIO BALL_T21_IS_GPIO
#endif 

#define BALL_R23 PAD_CI_D0
#define PAD_CI_D0 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_R23_IS_GPIO
#define BALL_R23_IS_GPIO 0
#endif 
#ifndef PAD_CI_D0_IS_GPIO
#define PAD_CI_D0_IS_GPIO BALL_R23_IS_GPIO
#endif 

#define BALL_P21 PAD_CI_D1
#define PAD_CI_D1 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_P21_IS_GPIO
#define BALL_P21_IS_GPIO 0
#endif 
#ifndef PAD_CI_D1_IS_GPIO
#define PAD_CI_D1_IS_GPIO BALL_P21_IS_GPIO
#endif 

#define BALL_P23 PAD_CI_D2
#define PAD_CI_D2 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_P23_IS_GPIO
#define BALL_P23_IS_GPIO 0
#endif 
#ifndef PAD_CI_D2_IS_GPIO
#define PAD_CI_D2_IS_GPIO BALL_P23_IS_GPIO
#endif 

#define BALL_M22 PAD_TS0_SYNC
#define PAD_TS0_SYNC 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_M22_IS_GPIO
#define BALL_M22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_M22_IS_GPIO
#endif 

#define BALL_M23 PAD_TS0_VLD
#define PAD_TS0_VLD 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_M23_IS_GPIO
#define BALL_M23_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_M23_IS_GPIO
#endif 

#define BALL_M21 PAD_TS0_D0
#define PAD_TS0_D0 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_M21_IS_GPIO
#define BALL_M21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_M21_IS_GPIO
#endif 

#define BALL_N21 PAD_TS0_D1
#define PAD_TS0_D1 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_N21_IS_GPIO
#define BALL_N21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_N21_IS_GPIO
#endif 

#define BALL_N22 PAD_TS0_D2
#define PAD_TS0_D2 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_N22_IS_GPIO
#define BALL_N22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_N22_IS_GPIO
#endif 

#define BALL_K22 PAD_TS0_D3
#define PAD_TS0_D3 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_K22_IS_GPIO
#define BALL_K22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_K22_IS_GPIO
#endif 

#define BALL_K21 PAD_TS0_D4
#define PAD_TS0_D4 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_K21_IS_GPIO
#define BALL_K21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_K21_IS_GPIO
#endif 

#define BALL_L22 PAD_TS0_D5
#define PAD_TS0_D5 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_L22_IS_GPIO
#define BALL_L22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_L22_IS_GPIO
#endif 

#define BALL_L23 PAD_TS0_D6
#define PAD_TS0_D6 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_L23_IS_GPIO
#define BALL_L23_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_L23_IS_GPIO
#endif 

#define BALL_L21 PAD_TS0_D7
#define PAD_TS0_D7 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_L21_IS_GPIO
#define BALL_L21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_L21_IS_GPIO
#endif 

#define BALL_P22 PAD_TS0_CLK
#define PAD_TS0_CLK 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_P22_IS_GPIO
#define BALL_P22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_P22_IS_GPIO
#endif 

#define BALL_K19 PAD_TS1_SYNC
#define PAD_TS1_SYNC 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_K19_IS_GPIO
#define BALL_K19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_K19_IS_GPIO
#endif 

#define BALL_M18 PAD_TS1_VLD
#define PAD_TS1_VLD 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_M18_IS_GPIO
#define BALL_M18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_M18_IS_GPIO
#endif 

#define BALL_L19 PAD_TS1_D0
#define PAD_TS1_D0 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_L19_IS_GPIO
#define BALL_L19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_L19_IS_GPIO
#endif 

#define BALL_L20 PAD_TS1_D1
#define PAD_TS1_D1 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_L20_IS_GPIO
#define BALL_L20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_L20_IS_GPIO
#endif 

#define BALL_L18 PAD_TS1_D2
#define PAD_TS1_D2 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_L18_IS_GPIO
#define BALL_L18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_L18_IS_GPIO
#endif 

#define BALL_M20 PAD_TS1_D3
#define PAD_TS1_D3 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_M20_IS_GPIO
#define BALL_M20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_M20_IS_GPIO
#endif 

#define BALL_M19 PAD_TS1_D4
#define PAD_TS1_D4 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_M19_IS_GPIO
#define BALL_M19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_M19_IS_GPIO
#endif 

#define BALL_N18 PAD_TS1_D5
#define PAD_TS1_D5 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_N18_IS_GPIO
#define BALL_N18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_N18_IS_GPIO
#endif 

#define BALL_P19 PAD_TS1_D6
#define PAD_TS1_D6 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_P19_IS_GPIO
#define BALL_P19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_P19_IS_GPIO
#endif 

#define BALL_P20 PAD_TS1_D7
#define PAD_TS1_D7 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_P20_IS_GPIO
#define BALL_P20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_P20_IS_GPIO
#endif 

#define BALL_N19 PAD_TS1_CLK
#define PAD_TS1_CLK 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_N19_IS_GPIO
#define BALL_N19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_N19_IS_GPIO
#endif 

#define BALL_J22 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_J22_IS_GPIO
#define BALL_J22_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO BALL_J22_IS_GPIO
#endif 

#define BALL_J21 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_J21_IS_GPIO
#define BALL_J21_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO BALL_J21_IS_GPIO
#endif 

#define BALL_H21 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_H21_IS_GPIO
#define BALL_H21_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO BALL_H21_IS_GPIO
#endif 

#define BALL_J23 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_J23_IS_GPIO
#define BALL_J23_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO BALL_J23_IS_GPIO
#endif 

#define PAD_GT0_MDIO 9999
#ifndef PAD_GT0_MDIO_IS_GPIO
#define PAD_GT0_MDIO_IS_GPIO 0
#endif 

#define PAD_GT0_MDC 9999
#ifndef PAD_GT0_MDC_IS_GPIO
#define PAD_GT0_MDC_IS_GPIO 0
#endif 

#define PAD_GT0_TX_CTL 9999
#ifndef PAD_GT0_TX_CTL_IS_GPIO
#define PAD_GT0_TX_CTL_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D3 9999
#ifndef PAD_GT0_TX_D3_IS_GPIO
#define PAD_GT0_TX_D3_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D2 9999
#ifndef PAD_GT0_TX_D2_IS_GPIO
#define PAD_GT0_TX_D2_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D1 9999
#ifndef PAD_GT0_TX_D1_IS_GPIO
#define PAD_GT0_TX_D1_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D0 9999
#ifndef PAD_GT0_TX_D0_IS_GPIO
#define PAD_GT0_TX_D0_IS_GPIO 0
#endif 

#define PAD_GT0_TX_CLK 9999
#ifndef PAD_GT0_TX_CLK_IS_GPIO
#define PAD_GT0_TX_CLK_IS_GPIO 0
#endif 

#define PAD_GT0_RX_CLK 9999
#ifndef PAD_GT0_RX_CLK_IS_GPIO
#define PAD_GT0_RX_CLK_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D3 9999
#ifndef PAD_GT0_RX_D3_IS_GPIO
#define PAD_GT0_RX_D3_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D2 9999
#ifndef PAD_GT0_RX_D2_IS_GPIO
#define PAD_GT0_RX_D2_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D1 9999
#ifndef PAD_GT0_RX_D1_IS_GPIO
#define PAD_GT0_RX_D1_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D0 9999
#ifndef PAD_GT0_RX_D0_IS_GPIO
#define PAD_GT0_RX_D0_IS_GPIO 0
#endif 

#define PAD_GT0_RX_CTL 9999
#ifndef PAD_GT0_RX_CTL_IS_GPIO
#define PAD_GT0_RX_CTL_IS_GPIO 0
#endif 

#define BALL_G20 PAD_PM_GPIO6
#define PAD_PM_GPIO6 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_G20_IS_GPIO
#define BALL_G20_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO BALL_G20_IS_GPIO
#endif 

#define BALL_H22 PAD_PM_GPIO7
#define PAD_PM_GPIO7 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_H22_IS_GPIO
#define BALL_H22_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO BALL_H22_IS_GPIO
#endif 

#define BALL_H23 PAD_PM_GPIO8
#define PAD_PM_GPIO8 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_H23_IS_GPIO
#define BALL_H23_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO8_IS_GPIO
#define PAD_PM_GPIO8_IS_GPIO BALL_H23_IS_GPIO
#endif 

#define BALL_E22 PAD_PM_GPIO9
#define PAD_PM_GPIO9 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_E22_IS_GPIO
#define BALL_E22_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO BALL_E22_IS_GPIO
#endif 

#define BALL_E21 PAD_PM_GPIO10
#define PAD_PM_GPIO10 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_E21_IS_GPIO
#define BALL_E21_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO BALL_E21_IS_GPIO
#endif 

#define BALL_B16 PAD_PM_GPIO11
#define PAD_PM_GPIO11 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO11_IS_GPIO
#define PAD_PM_GPIO11_IS_GPIO BALL_B16_IS_GPIO
#endif 

#define BALL_D20 PAD_PM_GPIO12
#define PAD_PM_GPIO12 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_D20_IS_GPIO
#define BALL_D20_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO BALL_D20_IS_GPIO
#endif 

#define BALL_B22 PAD_PM_GPIO13
#define PAD_PM_GPIO13 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_B22_IS_GPIO
#define BALL_B22_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO BALL_B22_IS_GPIO
#endif 

#define BALL_A21 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_A21_IS_GPIO
#define BALL_A21_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_A21_IS_GPIO
#endif 

#define BALL_B21 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_B21_IS_GPIO
#define BALL_B21_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_B21_IS_GPIO
#endif 

#define BALL_D21 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_D21_IS_GPIO
#define BALL_D21_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_D21_IS_GPIO
#endif 

#define BALL_C20 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_C20_IS_GPIO
#define BALL_C20_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_C20_IS_GPIO
#endif 

#define BALL_B18 PAD_PM_SPI_RSTZ
#define PAD_PM_SPI_RSTZ 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_B18_IS_GPIO
#define BALL_B18_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_RSTZ_IS_GPIO
#define PAD_PM_SPI_RSTZ_IS_GPIO BALL_B18_IS_GPIO
#endif 

#define BALL_A15 PAD_PM_GPIO14
#define PAD_PM_GPIO14 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_A15_IS_GPIO
#define BALL_A15_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO BALL_A15_IS_GPIO
#endif 

#define BALL_C8 PAD_PM_GPIO15
#define PAD_PM_GPIO15 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO15_IS_GPIO
#define PAD_PM_GPIO15_IS_GPIO BALL_C8_IS_GPIO
#endif 

#define BALL_B8 PAD_PM_GPIO16
#define PAD_PM_GPIO16 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_B8_IS_GPIO
#define BALL_B8_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO16_IS_GPIO
#define PAD_PM_GPIO16_IS_GPIO BALL_B8_IS_GPIO
#endif 

#define BALL_C21 PAD_PM_IRIN
#define PAD_PM_IRIN 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_C21_IS_GPIO
#define BALL_C21_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_C21_IS_GPIO
#endif 

#define BALL_D6 PAD_PM_HDMI_CEC
#define PAD_PM_HDMI_CEC 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_CEC_IS_GPIO
#define PAD_PM_HDMI_CEC_IS_GPIO BALL_D6_IS_GPIO
#endif 

#define BALL_C6 PAD_PM_HDMI_HPD
#define PAD_PM_HDMI_HPD 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_HPD_IS_GPIO
#define PAD_PM_HDMI_HPD_IS_GPIO BALL_C6_IS_GPIO
#endif 

#define BALL_C18 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_C18_IS_GPIO
#define BALL_C18_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_C18_IS_GPIO
#endif 

#define BALL_A19 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_A19_IS_GPIO
#define BALL_A19_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_A19_IS_GPIO
#endif 

#define BALL_B19 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_B19_IS_GPIO
#define BALL_B19_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B19_IS_GPIO
#endif 

#define BALL_A18 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_A18_IS_GPIO
#define BALL_A18_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_A18_IS_GPIO
#endif 

#define BALL_B20 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_B20_IS_GPIO
#define BALL_B20_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO BALL_B20_IS_GPIO
#endif 

#define BALL_C19 PAD_PM_SPI_HOLDZ
#define PAD_PM_SPI_HOLDZ 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_C19_IS_GPIO
#define BALL_C19_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_HOLDZ_IS_GPIO
#define PAD_PM_SPI_HOLDZ_IS_GPIO BALL_C19_IS_GPIO
#endif 

#define BALL_A16 PAD_GT1_MDIO
#define PAD_GT1_MDIO 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_A16_IS_GPIO
#define BALL_A16_IS_GPIO 0
#endif 
#ifndef PAD_GT1_MDIO_IS_GPIO
#define PAD_GT1_MDIO_IS_GPIO BALL_A16_IS_GPIO
#endif 

#define BALL_C15 PAD_GT1_MDC
#define PAD_GT1_MDC 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_C15_IS_GPIO
#define BALL_C15_IS_GPIO 0
#endif 
#ifndef PAD_GT1_MDC_IS_GPIO
#define PAD_GT1_MDC_IS_GPIO BALL_C15_IS_GPIO
#endif 

#define BALL_B15 PAD_GT1_TX_CTL
#define PAD_GT1_TX_CTL 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_CTL_IS_GPIO
#define PAD_GT1_TX_CTL_IS_GPIO BALL_B15_IS_GPIO
#endif 

#define BALL_C14 PAD_GT1_TX_D3
#define PAD_GT1_TX_D3 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D3_IS_GPIO
#define PAD_GT1_TX_D3_IS_GPIO BALL_C14_IS_GPIO
#endif 

#define BALL_B14 PAD_GT1_TX_D2
#define PAD_GT1_TX_D2 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D2_IS_GPIO
#define PAD_GT1_TX_D2_IS_GPIO BALL_B14_IS_GPIO
#endif 

#define BALL_C13 PAD_GT1_TX_D1
#define PAD_GT1_TX_D1 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D1_IS_GPIO
#define PAD_GT1_TX_D1_IS_GPIO BALL_C13_IS_GPIO
#endif 

#define BALL_B13 PAD_GT1_TX_D0
#define PAD_GT1_TX_D0 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D0_IS_GPIO
#define PAD_GT1_TX_D0_IS_GPIO BALL_B13_IS_GPIO
#endif 

#define BALL_A13 PAD_GT1_TX_CLK
#define PAD_GT1_TX_CLK 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_A13_IS_GPIO
#define BALL_A13_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_CLK_IS_GPIO
#define PAD_GT1_TX_CLK_IS_GPIO BALL_A13_IS_GPIO
#endif 

#define BALL_A12 PAD_GT1_RX_CLK
#define PAD_GT1_RX_CLK 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_CLK_IS_GPIO
#define PAD_GT1_RX_CLK_IS_GPIO BALL_A12_IS_GPIO
#endif 

#define BALL_B12 PAD_GT1_RX_D3
#define PAD_GT1_RX_D3 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_B12_IS_GPIO
#define BALL_B12_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D3_IS_GPIO
#define PAD_GT1_RX_D3_IS_GPIO BALL_B12_IS_GPIO
#endif 

#define BALL_C11 PAD_GT1_RX_D2
#define PAD_GT1_RX_D2 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D2_IS_GPIO
#define PAD_GT1_RX_D2_IS_GPIO BALL_C11_IS_GPIO
#endif 

#define BALL_B11 PAD_GT1_RX_D1
#define PAD_GT1_RX_D1 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D1_IS_GPIO
#define PAD_GT1_RX_D1_IS_GPIO BALL_B11_IS_GPIO
#endif 

#define BALL_C10 PAD_GT1_RX_D0
#define PAD_GT1_RX_D0 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_C10_IS_GPIO
#define BALL_C10_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D0_IS_GPIO
#define PAD_GT1_RX_D0_IS_GPIO BALL_C10_IS_GPIO
#endif 

#define BALL_B10 PAD_GT1_RX_CTL
#define PAD_GT1_RX_CTL 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_B10_IS_GPIO
#define BALL_B10_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_CTL_IS_GPIO
#define PAD_GT1_RX_CTL_IS_GPIO BALL_B10_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            0
#define CHIP_HAS_I2S_OUT           0
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         0
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSD7C77_H_*/
