////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSO9380AM_H_
#define _MSO9380AM_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_D5 PAD_SD_D1
#define PAD_SD_D1 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_SD_D1_IS_GPIO
#define PAD_SD_D1_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_D4 PAD_SD_D0
#define PAD_SD_D0 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_SD_D0_IS_GPIO
#define PAD_SD_D0_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_C3 PAD_SD_CLK
#define PAD_SD_CLK 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif 
#ifndef PAD_SD_CLK_IS_GPIO
#define PAD_SD_CLK_IS_GPIO BALL_C3_IS_GPIO
#endif 

#define BALL_C4 PAD_SD_CMD
#define PAD_SD_CMD 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_C4_IS_GPIO
#define BALL_C4_IS_GPIO 0
#endif 
#ifndef PAD_SD_CMD_IS_GPIO
#define PAD_SD_CMD_IS_GPIO BALL_C4_IS_GPIO
#endif 

#define BALL_D3 PAD_SD_D3
#define PAD_SD_D3 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif 
#ifndef PAD_SD_D3_IS_GPIO
#define PAD_SD_D3_IS_GPIO BALL_D3_IS_GPIO
#endif 

#define BALL_E5 PAD_SD_D2
#define PAD_SD_D2 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_SD_D2_IS_GPIO
#define PAD_SD_D2_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_F2 PAD_GPIO4
#define PAD_GPIO4 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_F2_IS_GPIO
#endif 

#define BALL_F1 PAD_GPIO3
#define PAD_GPIO3 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_F1_IS_GPIO
#define BALL_F1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_F1_IS_GPIO
#endif 

#define BALL_B4 PAD_GPIO2
#define PAD_GPIO2 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_B4_IS_GPIO
#endif 

#define BALL_B3 PAD_GPIO1
#define PAD_GPIO1 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_B3_IS_GPIO
#endif 

#define BALL_A3 PAD_GPIO0
#define PAD_GPIO0 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_A3_IS_GPIO
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_MUTE 9999
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD0 9999
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_WS 9999
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_BCK 9999
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_MCK 9999
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO 0
#endif 

#define BALL_M17 PAD_EMMC_IO17
#define PAD_EMMC_IO17 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_M17_IS_GPIO
#define BALL_M17_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO17_IS_GPIO
#define PAD_EMMC_IO17_IS_GPIO BALL_M17_IS_GPIO
#endif 

#define BALL_M18 PAD_EMMC_IO16
#define PAD_EMMC_IO16 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_M18_IS_GPIO
#define BALL_M18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO16_IS_GPIO
#define PAD_EMMC_IO16_IS_GPIO BALL_M18_IS_GPIO
#endif 

#define BALL_N17 PAD_EMMC_IO15
#define PAD_EMMC_IO15 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_N17_IS_GPIO
#define BALL_N17_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO15_IS_GPIO
#define PAD_EMMC_IO15_IS_GPIO BALL_N17_IS_GPIO
#endif 

#define BALL_N18 PAD_EMMC_IO14
#define PAD_EMMC_IO14 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_N18_IS_GPIO
#define BALL_N18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO14_IS_GPIO
#define PAD_EMMC_IO14_IS_GPIO BALL_N18_IS_GPIO
#endif 

#define BALL_P17 PAD_EMMC_IO12
#define PAD_EMMC_IO12 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_P17_IS_GPIO
#define BALL_P17_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO12_IS_GPIO
#define PAD_EMMC_IO12_IS_GPIO BALL_P17_IS_GPIO
#endif 

#define PAD_SPDIF_OUT 9999
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO 0
#endif 

#define BALL_K18 PAD_TS_D7
#define PAD_TS_D7 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_K18_IS_GPIO
#define BALL_K18_IS_GPIO 0
#endif 
#ifndef PAD_TS_D7_IS_GPIO
#define PAD_TS_D7_IS_GPIO BALL_K18_IS_GPIO
#endif 

#define BALL_H18 PAD_TS_D3
#define PAD_TS_D3 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_H18_IS_GPIO
#define BALL_H18_IS_GPIO 0
#endif 
#ifndef PAD_TS_D3_IS_GPIO
#define PAD_TS_D3_IS_GPIO BALL_H18_IS_GPIO
#endif 

#define BALL_K17 PAD_TS_D6
#define PAD_TS_D6 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_K17_IS_GPIO
#define BALL_K17_IS_GPIO 0
#endif 
#ifndef PAD_TS_D6_IS_GPIO
#define PAD_TS_D6_IS_GPIO BALL_K17_IS_GPIO
#endif 

#define BALL_J18 PAD_TS_D5
#define PAD_TS_D5 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_J18_IS_GPIO
#define BALL_J18_IS_GPIO 0
#endif 
#ifndef PAD_TS_D5_IS_GPIO
#define PAD_TS_D5_IS_GPIO BALL_J18_IS_GPIO
#endif 

#define BALL_G18 PAD_TS_D1
#define PAD_TS_D1 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_G18_IS_GPIO
#define BALL_G18_IS_GPIO 0
#endif 
#ifndef PAD_TS_D1_IS_GPIO
#define PAD_TS_D1_IS_GPIO BALL_G18_IS_GPIO
#endif 

#define BALL_J17 PAD_TS_D4
#define PAD_TS_D4 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_J17_IS_GPIO
#define BALL_J17_IS_GPIO 0
#endif 
#ifndef PAD_TS_D4_IS_GPIO
#define PAD_TS_D4_IS_GPIO BALL_J17_IS_GPIO
#endif 

#define BALL_H17 PAD_TS_D2
#define PAD_TS_D2 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_H17_IS_GPIO
#define BALL_H17_IS_GPIO 0
#endif 
#ifndef PAD_TS_D2_IS_GPIO
#define PAD_TS_D2_IS_GPIO BALL_H17_IS_GPIO
#endif 

#define BALL_G15 PAD_TS_CLK
#define PAD_TS_CLK 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_G15_IS_GPIO
#define BALL_G15_IS_GPIO 0
#endif 
#ifndef PAD_TS_CLK_IS_GPIO
#define PAD_TS_CLK_IS_GPIO BALL_G15_IS_GPIO
#endif 

#define BALL_H16 PAD_TS_VLD
#define PAD_TS_VLD 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_H16_IS_GPIO
#define BALL_H16_IS_GPIO 0
#endif 
#ifndef PAD_TS_VLD_IS_GPIO
#define PAD_TS_VLD_IS_GPIO BALL_H16_IS_GPIO
#endif 

#define BALL_G16 PAD_TS_SYNC
#define PAD_TS_SYNC 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_G16_IS_GPIO
#define BALL_G16_IS_GPIO 0
#endif 
#ifndef PAD_TS_SYNC_IS_GPIO
#define PAD_TS_SYNC_IS_GPIO BALL_G16_IS_GPIO
#endif 

#define BALL_G17 PAD_TS_D0
#define PAD_TS_D0 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_G17_IS_GPIO
#define BALL_G17_IS_GPIO 0
#endif 
#ifndef PAD_TS_D0_IS_GPIO
#define PAD_TS_D0_IS_GPIO BALL_G17_IS_GPIO
#endif 

#define BALL_F18 PAD_GT0_MDIO
#define PAD_GT0_MDIO 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_F18_IS_GPIO
#define BALL_F18_IS_GPIO 0
#endif 
#ifndef PAD_GT0_MDIO_IS_GPIO
#define PAD_GT0_MDIO_IS_GPIO BALL_F18_IS_GPIO
#endif 

#define BALL_F17 PAD_GT0_MDC
#define PAD_GT0_MDC 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_F17_IS_GPIO
#define BALL_F17_IS_GPIO 0
#endif 
#ifndef PAD_GT0_MDC_IS_GPIO
#define PAD_GT0_MDC_IS_GPIO BALL_F17_IS_GPIO
#endif 

#define BALL_D16 PAD_GT0_RX_D1
#define PAD_GT0_RX_D1 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_D16_IS_GPIO
#define BALL_D16_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D1_IS_GPIO
#define PAD_GT0_RX_D1_IS_GPIO BALL_D16_IS_GPIO
#endif 

#define BALL_D18 PAD_GT0_TX_D2
#define PAD_GT0_TX_D2 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_D18_IS_GPIO
#define BALL_D18_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D2_IS_GPIO
#define PAD_GT0_TX_D2_IS_GPIO BALL_D18_IS_GPIO
#endif 

#define BALL_E16 PAD_GT0_RX_D2
#define PAD_GT0_RX_D2 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_E16_IS_GPIO
#define BALL_E16_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D2_IS_GPIO
#define PAD_GT0_RX_D2_IS_GPIO BALL_E16_IS_GPIO
#endif 

#define BALL_D17 PAD_GT0_TX_D1
#define PAD_GT0_TX_D1 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_D17_IS_GPIO
#define BALL_D17_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D1_IS_GPIO
#define PAD_GT0_TX_D1_IS_GPIO BALL_D17_IS_GPIO
#endif 

#define BALL_D15 PAD_GT0_RX_D0
#define PAD_GT0_RX_D0 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_D15_IS_GPIO
#define BALL_D15_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D0_IS_GPIO
#define PAD_GT0_RX_D0_IS_GPIO BALL_D15_IS_GPIO
#endif 

#define BALL_E17 PAD_GT0_TX_D3
#define PAD_GT0_TX_D3 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D3_IS_GPIO
#define PAD_GT0_TX_D3_IS_GPIO BALL_E17_IS_GPIO
#endif 

#define BALL_E14 PAD_GT0_RX_CLK
#define PAD_GT0_RX_CLK 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_E14_IS_GPIO
#define BALL_E14_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_CLK_IS_GPIO
#define PAD_GT0_RX_CLK_IS_GPIO BALL_E14_IS_GPIO
#endif 

#define BALL_E18 PAD_GT0_TX_CTL
#define PAD_GT0_TX_CTL 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_E18_IS_GPIO
#define BALL_E18_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_CTL_IS_GPIO
#define PAD_GT0_TX_CTL_IS_GPIO BALL_E18_IS_GPIO
#endif 

#define BALL_E15 PAD_GT0_RX_D3
#define PAD_GT0_RX_D3 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D3_IS_GPIO
#define PAD_GT0_RX_D3_IS_GPIO BALL_E15_IS_GPIO
#endif 

#define BALL_F15 PAD_GT0_TX_CLK
#define PAD_GT0_TX_CLK 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_F15_IS_GPIO
#define BALL_F15_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_CLK_IS_GPIO
#define PAD_GT0_TX_CLK_IS_GPIO BALL_F15_IS_GPIO
#endif 

#define BALL_D14 PAD_GT0_RX_CTL
#define PAD_GT0_RX_CTL 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_D14_IS_GPIO
#define BALL_D14_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_CTL_IS_GPIO
#define PAD_GT0_RX_CTL_IS_GPIO BALL_D14_IS_GPIO
#endif 

#define BALL_F16 PAD_GT0_TX_D0
#define PAD_GT0_TX_D0 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_F16_IS_GPIO
#define BALL_F16_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D0_IS_GPIO
#define PAD_GT0_TX_D0_IS_GPIO BALL_F16_IS_GPIO
#endif 

#define BALL_D11 PAD_SAR_GPIO4
#define PAD_SAR_GPIO4 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_D11_IS_GPIO
#define BALL_D11_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO4_IS_GPIO
#define PAD_SAR_GPIO4_IS_GPIO BALL_D11_IS_GPIO
#endif 

#define BALL_D13 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_D13_IS_GPIO
#define BALL_D13_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_D13_IS_GPIO
#endif 

#define BALL_C14 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_C14_IS_GPIO
#endif 

#define BALL_E13 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_E13_IS_GPIO
#define BALL_E13_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_E13_IS_GPIO
#endif 

#define BALL_D12 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_D12_IS_GPIO
#define BALL_D12_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_D12_IS_GPIO
#endif 

#define BALL_A13 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_A13_IS_GPIO
#define BALL_A13_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_A13_IS_GPIO
#endif 

#define BALL_C17 PAD_PM_GPIO3
#define PAD_PM_GPIO3 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_C17_IS_GPIO
#define BALL_C17_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO BALL_C17_IS_GPIO
#endif 

#define BALL_A16 PAD_PM_IRIN
#define PAD_PM_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_A16_IS_GPIO
#define BALL_A16_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_A16_IS_GPIO
#endif 

#define BALL_C16 PAD_PM_GPIO4
#define PAD_PM_GPIO4 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_C16_IS_GPIO
#define BALL_C16_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_C16_IS_GPIO
#endif 

#define BALL_B16 PAD_PM_GPIO0
#define PAD_PM_GPIO0 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_B16_IS_GPIO
#endif 

#define BALL_C18 PAD_PM_GPIO1
#define PAD_PM_GPIO1 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_C18_IS_GPIO
#define BALL_C18_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_C18_IS_GPIO
#endif 

#define BALL_B14 PAD_PM_GPIO2
#define PAD_PM_GPIO2 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO BALL_B14_IS_GPIO
#endif 

#define BALL_B13 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B13_IS_GPIO
#endif 

#define BALL_C13 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_C13_IS_GPIO
#endif 

#define PAD_PM_GPIO5 9999
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO 0
#endif 

#define PAD_PM_GPIO6 9999
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO 0
#endif 

#define PAD_PM_GPIO7 9999
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO 0
#endif 

#define BALL_E10 PAD_VID0
#define PAD_VID0 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_E10_IS_GPIO
#endif 

#define BALL_E9 PAD_VID1
#define PAD_VID1 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define BALL_B12 PAD_PM_LED0
#define PAD_PM_LED0 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_B12_IS_GPIO
#define BALL_B12_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED0_IS_GPIO
#define PAD_PM_LED0_IS_GPIO BALL_B12_IS_GPIO
#endif 

#define BALL_C12 PAD_PM_LED1
#define PAD_PM_LED1 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_C12_IS_GPIO
#define BALL_C12_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED1_IS_GPIO
#define PAD_PM_LED1_IS_GPIO BALL_C12_IS_GPIO
#endif 

#define BALL_A12 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_A12_IS_GPIO
#endif 

#define BALL_E6 PAD_PM_CEC
#define PAD_PM_CEC 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_PM_CEC_IS_GPIO
#define PAD_PM_CEC_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_E7 PAD_HDMITX_HPD
#define PAD_HDMITX_HPD 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_HPD_IS_GPIO
#define PAD_HDMITX_HPD_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_D9 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_D9_IS_GPIO
#define BALL_D9_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO BALL_D9_IS_GPIO
#endif 

#define BALL_E8 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_D10 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_D10_IS_GPIO
#define BALL_D10_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO BALL_D10_IS_GPIO
#endif 

#define BALL_D8 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO BALL_D8_IS_GPIO
#endif 

#define BALL_D6 PAD_HDMITX_SCL
#define PAD_HDMITX_SCL 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SCL_IS_GPIO
#define PAD_HDMITX_SCL_IS_GPIO BALL_D6_IS_GPIO
#endif 

#define BALL_D7 PAD_HDMITX_SDA
#define PAD_HDMITX_SDA 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SDA_IS_GPIO
#define PAD_HDMITX_SDA_IS_GPIO BALL_D7_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSO9380AM_H_*/
