////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSO9380AS_H_
#define _MSO9380AS_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PAD_SD_D1 9999
#ifndef PAD_SD_D1_IS_GPIO
#define PAD_SD_D1_IS_GPIO 0
#endif 

#define PAD_SD_D0 9999
#ifndef PAD_SD_D0_IS_GPIO
#define PAD_SD_D0_IS_GPIO 0
#endif 

#define PAD_SD_CLK 9999
#ifndef PAD_SD_CLK_IS_GPIO
#define PAD_SD_CLK_IS_GPIO 0
#endif 

#define PAD_SD_CMD 9999
#ifndef PAD_SD_CMD_IS_GPIO
#define PAD_SD_CMD_IS_GPIO 0
#endif 

#define PAD_SD_D3 9999
#ifndef PAD_SD_D3_IS_GPIO
#define PAD_SD_D3_IS_GPIO 0
#endif 

#define PAD_SD_D2 9999
#ifndef PAD_SD_D2_IS_GPIO
#define PAD_SD_D2_IS_GPIO 0
#endif 

#define BALL_A5 PAD_GPIO4
#define PAD_GPIO4 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_A5_IS_GPIO
#define BALL_A5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_A5_IS_GPIO
#endif 

#define BALL_B5 PAD_GPIO3
#define PAD_GPIO3 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_B5_IS_GPIO
#endif 

#define BALL_D2 PAD_GPIO2
#define PAD_GPIO2 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_D2_IS_GPIO
#endif 

#define BALL_D1 PAD_GPIO1
#define PAD_GPIO1 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_D1_IS_GPIO
#define BALL_D1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_D1_IS_GPIO
#endif 

#define BALL_C2 PAD_GPIO0
#define PAD_GPIO0 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_C2_IS_GPIO
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_MUTE 9999
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD0 9999
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_WS 9999
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_BCK 9999
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_MCK 9999
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO 0
#endif 

#define BALL_J18 PAD_EMMC_IO17
#define PAD_EMMC_IO17 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_J18_IS_GPIO
#define BALL_J18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO17_IS_GPIO
#define PAD_EMMC_IO17_IS_GPIO BALL_J18_IS_GPIO
#endif 

#define BALL_K17 PAD_EMMC_IO16
#define PAD_EMMC_IO16 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_K17_IS_GPIO
#define BALL_K17_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO16_IS_GPIO
#define PAD_EMMC_IO16_IS_GPIO BALL_K17_IS_GPIO
#endif 

#define BALL_K18 PAD_EMMC_IO15
#define PAD_EMMC_IO15 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_K18_IS_GPIO
#define BALL_K18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO15_IS_GPIO
#define PAD_EMMC_IO15_IS_GPIO BALL_K18_IS_GPIO
#endif 

#define BALL_K19 PAD_EMMC_IO14
#define PAD_EMMC_IO14 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_K19_IS_GPIO
#define BALL_K19_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO14_IS_GPIO
#define PAD_EMMC_IO14_IS_GPIO BALL_K19_IS_GPIO
#endif 

#define BALL_L17 PAD_EMMC_IO12
#define PAD_EMMC_IO12 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_L17_IS_GPIO
#define BALL_L17_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO12_IS_GPIO
#define PAD_EMMC_IO12_IS_GPIO BALL_L17_IS_GPIO
#endif 

#define PAD_SPDIF_OUT 9999
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO 0
#endif 

#define PAD_TS_D7 9999
#ifndef PAD_TS_D7_IS_GPIO
#define PAD_TS_D7_IS_GPIO 0
#endif 

#define PAD_TS_D3 9999
#ifndef PAD_TS_D3_IS_GPIO
#define PAD_TS_D3_IS_GPIO 0
#endif 

#define PAD_TS_D6 9999
#ifndef PAD_TS_D6_IS_GPIO
#define PAD_TS_D6_IS_GPIO 0
#endif 

#define PAD_TS_D5 9999
#ifndef PAD_TS_D5_IS_GPIO
#define PAD_TS_D5_IS_GPIO 0
#endif 

#define PAD_TS_D1 9999
#ifndef PAD_TS_D1_IS_GPIO
#define PAD_TS_D1_IS_GPIO 0
#endif 

#define PAD_TS_D4 9999
#ifndef PAD_TS_D4_IS_GPIO
#define PAD_TS_D4_IS_GPIO 0
#endif 

#define PAD_TS_D2 9999
#ifndef PAD_TS_D2_IS_GPIO
#define PAD_TS_D2_IS_GPIO 0
#endif 

#define PAD_TS_CLK 9999
#ifndef PAD_TS_CLK_IS_GPIO
#define PAD_TS_CLK_IS_GPIO 0
#endif 

#define PAD_TS_VLD 9999
#ifndef PAD_TS_VLD_IS_GPIO
#define PAD_TS_VLD_IS_GPIO 0
#endif 

#define PAD_TS_SYNC 9999
#ifndef PAD_TS_SYNC_IS_GPIO
#define PAD_TS_SYNC_IS_GPIO 0
#endif 

#define PAD_TS_D0 9999
#ifndef PAD_TS_D0_IS_GPIO
#define PAD_TS_D0_IS_GPIO 0
#endif 

#define PAD_GT0_MDIO 9999
#ifndef PAD_GT0_MDIO_IS_GPIO
#define PAD_GT0_MDIO_IS_GPIO 0
#endif 

#define PAD_GT0_MDC 9999
#ifndef PAD_GT0_MDC_IS_GPIO
#define PAD_GT0_MDC_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D1 9999
#ifndef PAD_GT0_RX_D1_IS_GPIO
#define PAD_GT0_RX_D1_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D2 9999
#ifndef PAD_GT0_TX_D2_IS_GPIO
#define PAD_GT0_TX_D2_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D2 9999
#ifndef PAD_GT0_RX_D2_IS_GPIO
#define PAD_GT0_RX_D2_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D1 9999
#ifndef PAD_GT0_TX_D1_IS_GPIO
#define PAD_GT0_TX_D1_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D0 9999
#ifndef PAD_GT0_RX_D0_IS_GPIO
#define PAD_GT0_RX_D0_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D3 9999
#ifndef PAD_GT0_TX_D3_IS_GPIO
#define PAD_GT0_TX_D3_IS_GPIO 0
#endif 

#define PAD_GT0_RX_CLK 9999
#ifndef PAD_GT0_RX_CLK_IS_GPIO
#define PAD_GT0_RX_CLK_IS_GPIO 0
#endif 

#define PAD_GT0_TX_CTL 9999
#ifndef PAD_GT0_TX_CTL_IS_GPIO
#define PAD_GT0_TX_CTL_IS_GPIO 0
#endif 

#define PAD_GT0_RX_D3 9999
#ifndef PAD_GT0_RX_D3_IS_GPIO
#define PAD_GT0_RX_D3_IS_GPIO 0
#endif 

#define PAD_GT0_TX_CLK 9999
#ifndef PAD_GT0_TX_CLK_IS_GPIO
#define PAD_GT0_TX_CLK_IS_GPIO 0
#endif 

#define PAD_GT0_RX_CTL 9999
#ifndef PAD_GT0_RX_CTL_IS_GPIO
#define PAD_GT0_RX_CTL_IS_GPIO 0
#endif 

#define PAD_GT0_TX_D0 9999
#ifndef PAD_GT0_TX_D0_IS_GPIO
#define PAD_GT0_TX_D0_IS_GPIO 0
#endif 

#define BALL_C16 PAD_SAR_GPIO4
#define PAD_SAR_GPIO4 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_C16_IS_GPIO
#define BALL_C16_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO4_IS_GPIO
#define PAD_SAR_GPIO4_IS_GPIO BALL_C16_IS_GPIO
#endif 

#define BALL_E17 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_E17_IS_GPIO
#endif 

#define BALL_F15 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_F15_IS_GPIO
#define BALL_F15_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_F15_IS_GPIO
#endif 

#define BALL_G15 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_G15_IS_GPIO
#define BALL_G15_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_G15_IS_GPIO
#endif 

#define BALL_D18 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_D18_IS_GPIO
#define BALL_D18_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_D18_IS_GPIO
#endif 

#define BALL_A16 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_A16_IS_GPIO
#define BALL_A16_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_A16_IS_GPIO
#endif 

#define BALL_C17 PAD_PM_GPIO3
#define PAD_PM_GPIO3 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_C17_IS_GPIO
#define BALL_C17_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO BALL_C17_IS_GPIO
#endif 

#define BALL_D17 PAD_PM_IRIN
#define PAD_PM_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_D17_IS_GPIO
#define BALL_D17_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_D17_IS_GPIO
#endif 

#define BALL_C18 PAD_PM_GPIO4
#define PAD_PM_GPIO4 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_C18_IS_GPIO
#define BALL_C18_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_C18_IS_GPIO
#endif 

#define BALL_C19 PAD_PM_GPIO0
#define PAD_PM_GPIO0 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_C19_IS_GPIO
#define BALL_C19_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_C19_IS_GPIO
#endif 

#define BALL_A17 PAD_PM_GPIO1
#define PAD_PM_GPIO1 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_A17_IS_GPIO
#define BALL_A17_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_A17_IS_GPIO
#endif 

#define BALL_B17 PAD_PM_GPIO2
#define PAD_PM_GPIO2 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_B17_IS_GPIO
#define BALL_B17_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO BALL_B17_IS_GPIO
#endif 

#define BALL_B16 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B16_IS_GPIO
#endif 

#define BALL_B15 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_B15_IS_GPIO
#endif 

#define PAD_PM_GPIO5 9999
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO 0
#endif 

#define PAD_PM_GPIO6 9999
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO 0
#endif 

#define PAD_PM_GPIO7 9999
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO 0
#endif 

#define BALL_E15 PAD_VID0
#define PAD_VID0 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_E15_IS_GPIO
#endif 

#define BALL_D15 PAD_VID1
#define PAD_VID1 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_D15_IS_GPIO
#define BALL_D15_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_D15_IS_GPIO
#endif 

#define BALL_C13 PAD_PM_LED0
#define PAD_PM_LED0 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED0_IS_GPIO
#define PAD_PM_LED0_IS_GPIO BALL_C13_IS_GPIO
#endif 

#define BALL_A14 PAD_PM_LED1
#define PAD_PM_LED1 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_A14_IS_GPIO
#define BALL_A14_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED1_IS_GPIO
#define PAD_PM_LED1_IS_GPIO BALL_A14_IS_GPIO
#endif 

#define BALL_C15 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_C15_IS_GPIO
#define BALL_C15_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_C15_IS_GPIO
#endif 

#define BALL_C14 PAD_PM_CEC
#define PAD_PM_CEC 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif 
#ifndef PAD_PM_CEC_IS_GPIO
#define PAD_PM_CEC_IS_GPIO BALL_C14_IS_GPIO
#endif 

#define BALL_B14 PAD_HDMITX_HPD
#define PAD_HDMITX_HPD 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_HPD_IS_GPIO
#define PAD_HDMITX_HPD_IS_GPIO BALL_B14_IS_GPIO
#endif 

#define PAD_I2CM1_SCL 9999
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO 0
#endif 

#define PAD_I2CM0_SCL 9999
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO 0
#endif 

#define PAD_I2CM1_SDA 9999
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO 0
#endif 

#define PAD_I2CM0_SDA 9999
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO 0
#endif 

#define BALL_B11 PAD_HDMITX_SCL
#define PAD_HDMITX_SCL 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SCL_IS_GPIO
#define PAD_HDMITX_SCL_IS_GPIO BALL_B11_IS_GPIO
#endif 

#define BALL_C11 PAD_HDMITX_SDA
#define PAD_HDMITX_SDA 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SDA_IS_GPIO
#define PAD_HDMITX_SDA_IS_GPIO BALL_C11_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSO9380AS_H_*/
