////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly
#ifndef _MSA6Z17_H_
#define _MSA6Z17_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_E4 PAD_GPIO3
#define PAD_GPIO3 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_E4_IS_GPIO
#endif

#define BALL_D4 PAD_GPIO5
#define PAD_GPIO5 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_D4_IS_GPIO
#endif

#define BALL_F3 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_F3_IS_GPIO
#endif

#define BALL_G5 PAD_GPIO7
#define PAD_GPIO7 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_G5_IS_GPIO
#endif

#define BALL_D5 PAD_GPIO1
#define PAD_GPIO1 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_D5_IS_GPIO
#endif

#define BALL_J5 PAD_SD_D2
#define PAD_SD_D2 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif
#ifndef PAD_SD_D2_IS_GPIO
#define PAD_SD_D2_IS_GPIO BALL_J5_IS_GPIO
#endif

#define BALL_H2 PAD_SD_CLK
#define PAD_SD_CLK 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif
#ifndef PAD_SD_CLK_IS_GPIO
#define PAD_SD_CLK_IS_GPIO BALL_H2_IS_GPIO
#endif

#define BALL_D6 PAD_GPIO2
#define PAD_GPIO2 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_D6_IS_GPIO
#endif

#define BALL_E5 PAD_GPIO0
#define PAD_GPIO0 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_E5_IS_GPIO
#endif

#define BALL_G3 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_G3_IS_GPIO
#define BALL_G3_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_G3_IS_GPIO
#endif

#define BALL_F6 PAD_GPIO4
#define PAD_GPIO4 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_F6_IS_GPIO
#endif

#define BALL_F2 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_F2_IS_GPIO
#endif

#define BALL_G4 PAD_GPIO6
#define PAD_GPIO6 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO BALL_G4_IS_GPIO
#endif

#define BALL_E3 PAD_I2S_OUT_MUTE
#define PAD_I2S_OUT_MUTE 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO BALL_E3_IS_GPIO
#endif

#define BALL_H5 PAD_GPIO9
#define PAD_GPIO9 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_H5_IS_GPIO
#endif

#define BALL_H4 PAD_SD_D1
#define PAD_SD_D1 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_H4_IS_GPIO
#define BALL_H4_IS_GPIO 0
#endif
#ifndef PAD_SD_D1_IS_GPIO
#define PAD_SD_D1_IS_GPIO BALL_H4_IS_GPIO
#endif

#define BALL_F1 PAD_I2S_OUT_SD0
#define PAD_I2S_OUT_SD0 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_F1_IS_GPIO
#define BALL_F1_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO BALL_F1_IS_GPIO
#endif

#define BALL_J2 PAD_SD_D3
#define PAD_SD_D3 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif
#ifndef PAD_SD_D3_IS_GPIO
#define PAD_SD_D3_IS_GPIO BALL_J2_IS_GPIO
#endif

#define BALL_G1 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_G1_IS_GPIO
#define BALL_G1_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_G1_IS_GPIO
#endif

#define BALL_E2 PAD_I2S_OUT_SD3
#define PAD_I2S_OUT_SD3 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO BALL_E2_IS_GPIO
#endif

#define BALL_E6 PAD_GPIO8
#define PAD_GPIO8 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_E6_IS_GPIO
#endif

#define BALL_H3 PAD_SD_D0
#define PAD_SD_D0 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif
#ifndef PAD_SD_D0_IS_GPIO
#define PAD_SD_D0_IS_GPIO BALL_H3_IS_GPIO
#endif

#define BALL_J3 PAD_SD_CMD
#define PAD_SD_CMD 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif
#ifndef PAD_SD_CMD_IS_GPIO
#define PAD_SD_CMD_IS_GPIO BALL_J3_IS_GPIO
#endif

#define BALL_G2 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_G2_IS_GPIO
#define BALL_G2_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_G2_IS_GPIO
#endif

#define BALL_AB21 PAD_CI_D1
#define PAD_CI_D1 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif
#ifndef PAD_CI_D1_IS_GPIO
#define PAD_CI_D1_IS_GPIO BALL_AB21_IS_GPIO
#endif

#define BALL_AC21 PAD_CI_D3
#define PAD_CI_D3 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_AC21_IS_GPIO
#define BALL_AC21_IS_GPIO 0
#endif
#ifndef PAD_CI_D3_IS_GPIO
#define PAD_CI_D3_IS_GPIO BALL_AC21_IS_GPIO
#endif

#define BALL_AC22 PAD_CI_D0
#define PAD_CI_D0 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_AC22_IS_GPIO
#define BALL_AC22_IS_GPIO 0
#endif
#ifndef PAD_CI_D0_IS_GPIO
#define PAD_CI_D0_IS_GPIO BALL_AC22_IS_GPIO
#endif

#define BALL_AB22 PAD_CI_D4
#define PAD_CI_D4 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif
#ifndef PAD_CI_D4_IS_GPIO
#define PAD_CI_D4_IS_GPIO BALL_AB22_IS_GPIO
#endif

#define BALL_AB23 PAD_CI_D2
#define PAD_CI_D2 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif
#ifndef PAD_CI_D2_IS_GPIO
#define PAD_CI_D2_IS_GPIO BALL_AB23_IS_GPIO
#endif

#define BALL_AD22 PAD_SDIO_IO3
#define PAD_SDIO_IO3 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_AD22_IS_GPIO
#define BALL_AD22_IS_GPIO 0
#endif
#ifndef PAD_SDIO_IO3_IS_GPIO
#define PAD_SDIO_IO3_IS_GPIO BALL_AD22_IS_GPIO
#endif

#define BALL_AE22 PAD_SDIO_IO4
#define PAD_SDIO_IO4 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_AE22_IS_GPIO
#define BALL_AE22_IS_GPIO 0
#endif
#ifndef PAD_SDIO_IO4_IS_GPIO
#define PAD_SDIO_IO4_IS_GPIO BALL_AE22_IS_GPIO
#endif

#define BALL_AE23 PAD_SDIO_IO2
#define PAD_SDIO_IO2 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif
#ifndef PAD_SDIO_IO2_IS_GPIO
#define PAD_SDIO_IO2_IS_GPIO BALL_AE23_IS_GPIO
#endif

#define BALL_AD20 PAD_SDIO_IO0
#define PAD_SDIO_IO0 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif
#ifndef PAD_SDIO_IO0_IS_GPIO
#define PAD_SDIO_IO0_IS_GPIO BALL_AD20_IS_GPIO
#endif

#define BALL_AE21 PAD_SDIO_IO5
#define PAD_SDIO_IO5 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif
#ifndef PAD_SDIO_IO5_IS_GPIO
#define PAD_SDIO_IO5_IS_GPIO BALL_AE21_IS_GPIO
#endif

#define BALL_AF20 PAD_SDIO_IO1
#define PAD_SDIO_IO1 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_AF20_IS_GPIO
#define BALL_AF20_IS_GPIO 0
#endif
#ifndef PAD_SDIO_IO1_IS_GPIO
#define PAD_SDIO_IO1_IS_GPIO BALL_AF20_IS_GPIO
#endif

#define BALL_AD25 PAD_EMMC_IO3
#define PAD_EMMC_IO3 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_AD25_IS_GPIO
#define BALL_AD25_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO3_IS_GPIO
#define PAD_EMMC_IO3_IS_GPIO BALL_AD25_IS_GPIO
#endif

#define BALL_AB25 PAD_EMMC_IO10
#define PAD_EMMC_IO10 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_AB25_IS_GPIO
#define BALL_AB25_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO10_IS_GPIO
#define PAD_EMMC_IO10_IS_GPIO BALL_AB25_IS_GPIO
#endif

#define BALL_AC26 PAD_EMMC_IO2
#define PAD_EMMC_IO2 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_AC26_IS_GPIO
#define BALL_AC26_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO2_IS_GPIO
#define PAD_EMMC_IO2_IS_GPIO BALL_AC26_IS_GPIO
#endif

#define BALL_AA26 PAD_EMMC_IO11
#define PAD_EMMC_IO11 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AA26_IS_GPIO
#define BALL_AA26_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO11_IS_GPIO
#define PAD_EMMC_IO11_IS_GPIO BALL_AA26_IS_GPIO
#endif

#define BALL_AF23 PAD_EMMC_IO16
#define PAD_EMMC_IO16 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_AF23_IS_GPIO
#define BALL_AF23_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO16_IS_GPIO
#define PAD_EMMC_IO16_IS_GPIO BALL_AF23_IS_GPIO
#endif

#define BALL_AB24 PAD_EMMC_IO14
#define PAD_EMMC_IO14 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_AB24_IS_GPIO
#define BALL_AB24_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO14_IS_GPIO
#define PAD_EMMC_IO14_IS_GPIO BALL_AB24_IS_GPIO
#endif

#define BALL_AA25 PAD_EMMC_IO15
#define PAD_EMMC_IO15 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_AA25_IS_GPIO
#define BALL_AA25_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO15_IS_GPIO
#define PAD_EMMC_IO15_IS_GPIO BALL_AA25_IS_GPIO
#endif

#define BALL_AD24 PAD_EMMC_IO1
#define PAD_EMMC_IO1 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_AD24_IS_GPIO
#define BALL_AD24_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO1_IS_GPIO
#define PAD_EMMC_IO1_IS_GPIO BALL_AD24_IS_GPIO
#endif

#define BALL_AE24 PAD_EMMC_IO5
#define PAD_EMMC_IO5 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_AE24_IS_GPIO
#define BALL_AE24_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO5_IS_GPIO
#define PAD_EMMC_IO5_IS_GPIO BALL_AE24_IS_GPIO
#endif

#define BALL_AE25 PAD_EMMC_IO4
#define PAD_EMMC_IO4 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_AE25_IS_GPIO
#define BALL_AE25_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO4_IS_GPIO
#define PAD_EMMC_IO4_IS_GPIO BALL_AE25_IS_GPIO
#endif

#define BALL_AD26 PAD_EMMC_IO0
#define PAD_EMMC_IO0 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_AD26_IS_GPIO
#define BALL_AD26_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO0_IS_GPIO
#define PAD_EMMC_IO0_IS_GPIO BALL_AD26_IS_GPIO
#endif

#define BALL_AE26 PAD_EMMC_IO8
#define PAD_EMMC_IO8 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_AE26_IS_GPIO
#define BALL_AE26_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO8_IS_GPIO
#define PAD_EMMC_IO8_IS_GPIO BALL_AE26_IS_GPIO
#endif

#define BALL_AF24 PAD_EMMC_IO12
#define PAD_EMMC_IO12 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_AF24_IS_GPIO
#define BALL_AF24_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO12_IS_GPIO
#define PAD_EMMC_IO12_IS_GPIO BALL_AF24_IS_GPIO
#endif

#define BALL_AC25 PAD_EMMC_IO9
#define PAD_EMMC_IO9 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_AC25_IS_GPIO
#define BALL_AC25_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO9_IS_GPIO
#define PAD_EMMC_IO9_IS_GPIO BALL_AC25_IS_GPIO
#endif

#define BALL_AC24 PAD_EMMC_IO13
#define PAD_EMMC_IO13 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_AC24_IS_GPIO
#define BALL_AC24_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO13_IS_GPIO
#define PAD_EMMC_IO13_IS_GPIO BALL_AC24_IS_GPIO
#endif

#define BALL_AF25 PAD_EMMC_IO7
#define PAD_EMMC_IO7 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_AF25_IS_GPIO
#define BALL_AF25_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO7_IS_GPIO
#define PAD_EMMC_IO7_IS_GPIO BALL_AF25_IS_GPIO
#endif

#define BALL_AD23 PAD_EMMC_IO6
#define PAD_EMMC_IO6 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_AD23_IS_GPIO
#define BALL_AD23_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO6_IS_GPIO
#define PAD_EMMC_IO6_IS_GPIO BALL_AD23_IS_GPIO
#endif

#define BALL_P23 PAD_SM0_IO
#define PAD_SM0_IO 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_P23_IS_GPIO
#define BALL_P23_IS_GPIO 0
#endif
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO BALL_P23_IS_GPIO
#endif

#define BALL_P21 PAD_SM0_VCC
#define PAD_SM0_VCC 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_P21_IS_GPIO
#define BALL_P21_IS_GPIO 0
#endif
#ifndef PAD_SM0_VCC_IS_GPIO
#define PAD_SM0_VCC_IS_GPIO BALL_P21_IS_GPIO
#endif

#define BALL_R23 PAD_SM0_C4
#define PAD_SM0_C4 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_R23_IS_GPIO
#define BALL_R23_IS_GPIO 0
#endif
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO BALL_R23_IS_GPIO
#endif

#define BALL_L24 PAD_TS2_D5
#define PAD_TS2_D5 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_L24_IS_GPIO
#define BALL_L24_IS_GPIO 0
#endif
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO BALL_L24_IS_GPIO
#endif

#define BALL_P22 PAD_SM0_C8
#define PAD_SM0_C8 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_P22_IS_GPIO
#define BALL_P22_IS_GPIO 0
#endif
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO BALL_P22_IS_GPIO
#endif

#define BALL_M23 PAD_SM0_VSEL
#define PAD_SM0_VSEL 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_M23_IS_GPIO
#define BALL_M23_IS_GPIO 0
#endif
#ifndef PAD_SM0_VSEL_IS_GPIO
#define PAD_SM0_VSEL_IS_GPIO BALL_M23_IS_GPIO
#endif

#define BALL_R21 PAD_SM0_CLK
#define PAD_SM0_CLK 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_R21_IS_GPIO
#define BALL_R21_IS_GPIO 0
#endif
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO BALL_R21_IS_GPIO
#endif

#define BALL_K25 PAD_TS2_D7
#define PAD_TS2_D7 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_K25_IS_GPIO
#define BALL_K25_IS_GPIO 0
#endif
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO BALL_K25_IS_GPIO
#endif

#define BALL_R22 PAD_SM0_RST
#define PAD_SM0_RST 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_R22_IS_GPIO
#define BALL_R22_IS_GPIO 0
#endif
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO BALL_R22_IS_GPIO
#endif

#define BALL_P24 PAD_SM0_CD
#define PAD_SM0_CD 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_P24_IS_GPIO
#define BALL_P24_IS_GPIO 0
#endif
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO BALL_P24_IS_GPIO
#endif

#define BALL_N24 PAD_TS2_D0
#define PAD_TS2_D0 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_N24_IS_GPIO
#define BALL_N24_IS_GPIO 0
#endif
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_N24_IS_GPIO
#endif

#define BALL_M25 PAD_TS2_D1
#define PAD_TS2_D1 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_M25_IS_GPIO
#define BALL_M25_IS_GPIO 0
#endif
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO BALL_M25_IS_GPIO
#endif

#define BALL_N21 PAD_TS2_SYNC
#define PAD_TS2_SYNC 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_N21_IS_GPIO
#define BALL_N21_IS_GPIO 0
#endif
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_N21_IS_GPIO
#endif

#define BALL_M24 PAD_TS2_D2
#define PAD_TS2_D2 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_M24_IS_GPIO
#define BALL_M24_IS_GPIO 0
#endif
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO BALL_M24_IS_GPIO
#endif

#define BALL_M22 PAD_TS2_VLD
#define PAD_TS2_VLD 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_M22_IS_GPIO
#define BALL_M22_IS_GPIO 0
#endif
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_M22_IS_GPIO
#endif

#define BALL_L26 PAD_TS2_D4
#define PAD_TS2_D4 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_L26_IS_GPIO
#define BALL_L26_IS_GPIO 0
#endif
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO BALL_L26_IS_GPIO
#endif

#define BALL_K26 PAD_TS2_D6
#define PAD_TS2_D6 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_K26_IS_GPIO
#define BALL_K26_IS_GPIO 0
#endif
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO BALL_K26_IS_GPIO
#endif

#define BALL_L25 PAD_TS2_D3
#define PAD_TS2_D3 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_L25_IS_GPIO
#define BALL_L25_IS_GPIO 0
#endif
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO BALL_L25_IS_GPIO
#endif

#define BALL_K24 PAD_TS2_CLK
#define PAD_TS2_CLK 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_K24_IS_GPIO
#define BALL_K24_IS_GPIO 0
#endif
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_K24_IS_GPIO
#endif

#define BALL_M21 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_M21_IS_GPIO
#define BALL_M21_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_M21_IS_GPIO
#endif

#define BALL_K22 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_K22_IS_GPIO
#define BALL_K22_IS_GPIO 0
#endif
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO BALL_K22_IS_GPIO
#endif

#define BALL_L22 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_L22_IS_GPIO
#define BALL_L22_IS_GPIO 0
#endif
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO BALL_L22_IS_GPIO
#endif

#define BALL_L21 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_L21_IS_GPIO
#define BALL_L21_IS_GPIO 0
#endif
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO BALL_L21_IS_GPIO
#endif

#define BALL_L23 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_L23_IS_GPIO
#define BALL_L23_IS_GPIO 0
#endif
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO BALL_L23_IS_GPIO
#endif

#define BALL_F24 PAD_GT0_RX_D2
#define PAD_GT0_RX_D2 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_F24_IS_GPIO
#define BALL_F24_IS_GPIO 0
#endif
#ifndef PAD_GT0_RX_D2_IS_GPIO
#define PAD_GT0_RX_D2_IS_GPIO BALL_F24_IS_GPIO
#endif

#define BALL_G24 PAD_GT0_RX_CLK
#define PAD_GT0_RX_CLK 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_G24_IS_GPIO
#define BALL_G24_IS_GPIO 0
#endif
#ifndef PAD_GT0_RX_CLK_IS_GPIO
#define PAD_GT0_RX_CLK_IS_GPIO BALL_G24_IS_GPIO
#endif

#define BALL_F25 PAD_GT0_RX_D3
#define PAD_GT0_RX_D3 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_F25_IS_GPIO
#define BALL_F25_IS_GPIO 0
#endif
#ifndef PAD_GT0_RX_D3_IS_GPIO
#define PAD_GT0_RX_D3_IS_GPIO BALL_F25_IS_GPIO
#endif

#define BALL_J25 PAD_GT0_TX_CTL
#define PAD_GT0_TX_CTL 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_J25_IS_GPIO
#define BALL_J25_IS_GPIO 0
#endif
#ifndef PAD_GT0_TX_CTL_IS_GPIO
#define PAD_GT0_TX_CTL_IS_GPIO BALL_J25_IS_GPIO
#endif

#define BALL_J23 PAD_GT0_MDC
#define PAD_GT0_MDC 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_J23_IS_GPIO
#define BALL_J23_IS_GPIO 0
#endif
#ifndef PAD_GT0_MDC_IS_GPIO
#define PAD_GT0_MDC_IS_GPIO BALL_J23_IS_GPIO
#endif

#define BALL_H25 PAD_GT0_TX_D2
#define PAD_GT0_TX_D2 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_H25_IS_GPIO
#define BALL_H25_IS_GPIO 0
#endif
#ifndef PAD_GT0_TX_D2_IS_GPIO
#define PAD_GT0_TX_D2_IS_GPIO BALL_H25_IS_GPIO
#endif

#define BALL_E26 PAD_GT0_RX_D0
#define PAD_GT0_RX_D0 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_E26_IS_GPIO
#define BALL_E26_IS_GPIO 0
#endif
#ifndef PAD_GT0_RX_D0_IS_GPIO
#define PAD_GT0_RX_D0_IS_GPIO BALL_E26_IS_GPIO
#endif

#define BALL_J24 PAD_GT0_TX_D3
#define PAD_GT0_TX_D3 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_J24_IS_GPIO
#define BALL_J24_IS_GPIO 0
#endif
#ifndef PAD_GT0_TX_D3_IS_GPIO
#define PAD_GT0_TX_D3_IS_GPIO BALL_J24_IS_GPIO
#endif

#define BALL_E24 PAD_GT0_RX_CTL
#define PAD_GT0_RX_CTL 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_E24_IS_GPIO
#define BALL_E24_IS_GPIO 0
#endif
#ifndef PAD_GT0_RX_CTL_IS_GPIO
#define PAD_GT0_RX_CTL_IS_GPIO BALL_E24_IS_GPIO
#endif

#define BALL_H26 PAD_GT0_TX_D1
#define PAD_GT0_TX_D1 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_H26_IS_GPIO
#define BALL_H26_IS_GPIO 0
#endif
#ifndef PAD_GT0_TX_D1_IS_GPIO
#define PAD_GT0_TX_D1_IS_GPIO BALL_H26_IS_GPIO
#endif

#define BALL_H23 PAD_GT0_MDIO
#define PAD_GT0_MDIO 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_H23_IS_GPIO
#define BALL_H23_IS_GPIO 0
#endif
#ifndef PAD_GT0_MDIO_IS_GPIO
#define PAD_GT0_MDIO_IS_GPIO BALL_H23_IS_GPIO
#endif

#define BALL_G26 PAD_GT0_TX_CLK
#define PAD_GT0_TX_CLK 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_G26_IS_GPIO
#define BALL_G26_IS_GPIO 0
#endif
#ifndef PAD_GT0_TX_CLK_IS_GPIO
#define PAD_GT0_TX_CLK_IS_GPIO BALL_G26_IS_GPIO
#endif

#define BALL_E25 PAD_GT0_RX_D1
#define PAD_GT0_RX_D1 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_E25_IS_GPIO
#define BALL_E25_IS_GPIO 0
#endif
#ifndef PAD_GT0_RX_D1_IS_GPIO
#define PAD_GT0_RX_D1_IS_GPIO BALL_E25_IS_GPIO
#endif

#define BALL_H24 PAD_GT0_TX_D0
#define PAD_GT0_TX_D0 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_H24_IS_GPIO
#define BALL_H24_IS_GPIO 0
#endif
#ifndef PAD_GT0_TX_D0_IS_GPIO
#define PAD_GT0_TX_D0_IS_GPIO BALL_H24_IS_GPIO
#endif

#define BALL_E23 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_E23_IS_GPIO
#define BALL_E23_IS_GPIO 0
#endif
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_E23_IS_GPIO
#endif

#define BALL_D23 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_D23_IS_GPIO
#define BALL_D23_IS_GPIO 0
#endif
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_D23_IS_GPIO
#endif

#define BALL_E21 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_E21_IS_GPIO
#define BALL_E21_IS_GPIO 0
#endif
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_E21_IS_GPIO
#endif

#define BALL_D22 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_D22_IS_GPIO
#define BALL_D22_IS_GPIO 0
#endif
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_D22_IS_GPIO
#endif

#define BALL_E22 PAD_SAR_GPIO4
#define PAD_SAR_GPIO4 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_E22_IS_GPIO
#define BALL_E22_IS_GPIO 0
#endif
#ifndef PAD_SAR_GPIO4_IS_GPIO
#define PAD_SAR_GPIO4_IS_GPIO BALL_E22_IS_GPIO
#endif

#define BALL_F22 PAD_PM_GPIO2
#define PAD_PM_GPIO2 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_F22_IS_GPIO
#define BALL_F22_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO BALL_F22_IS_GPIO
#endif

#define BALL_B23 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_B23_IS_GPIO
#define BALL_B23_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B23_IS_GPIO
#endif

#define BALL_G21 PAD_PM_GPIO4
#define PAD_PM_GPIO4 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_G21_IS_GPIO
#define BALL_G21_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_G21_IS_GPIO
#endif

#define BALL_G22 PAD_PM_GPIO3
#define PAD_PM_GPIO3 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_G22_IS_GPIO
#define BALL_G22_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO BALL_G22_IS_GPIO
#endif

#define BALL_B24 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_B24_IS_GPIO
#define BALL_B24_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO BALL_B24_IS_GPIO
#endif

#define BALL_F21 PAD_PM_GPIO1
#define PAD_PM_GPIO1 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_F21_IS_GPIO
#define BALL_F21_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_F21_IS_GPIO
#endif

#define BALL_D24 PAD_PM_GPIO0
#define PAD_PM_GPIO0 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_D24_IS_GPIO
#define BALL_D24_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_D24_IS_GPIO
#endif

#define BALL_E17 PAD_PM_GPIO15
#define PAD_PM_GPIO15 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO15_IS_GPIO
#define PAD_PM_GPIO15_IS_GPIO BALL_E17_IS_GPIO
#endif

#define BALL_B22 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_B22_IS_GPIO
#define BALL_B22_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_B22_IS_GPIO
#endif

#define BALL_F23 PAD_PM_GPIO5
#define PAD_PM_GPIO5 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_F23_IS_GPIO
#define BALL_F23_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO BALL_F23_IS_GPIO
#endif

#define BALL_A24 PAD_PM_SPI_RSTZ
#define PAD_PM_SPI_RSTZ 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_A24_IS_GPIO
#define BALL_A24_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_RSTZ_IS_GPIO
#define PAD_PM_SPI_RSTZ_IS_GPIO BALL_A24_IS_GPIO
#endif

#define BALL_E15 PAD_PM_GPIO13
#define PAD_PM_GPIO13 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO BALL_E15_IS_GPIO
#endif

#define BALL_C24 PAD_PM_SPI_HOLDZ
#define PAD_PM_SPI_HOLDZ 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_C24_IS_GPIO
#define BALL_C24_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_HOLDZ_IS_GPIO
#define PAD_PM_SPI_HOLDZ_IS_GPIO BALL_C24_IS_GPIO
#endif

#define BALL_E18 PAD_PM_GPIO7
#define PAD_PM_GPIO7 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_E18_IS_GPIO
#define BALL_E18_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO BALL_E18_IS_GPIO
#endif

#define BALL_C23 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_C23_IS_GPIO
#define BALL_C23_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_C23_IS_GPIO
#endif

#define BALL_D15 PAD_PM_GPIO14
#define PAD_PM_GPIO14 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_D15_IS_GPIO
#define BALL_D15_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO BALL_D15_IS_GPIO
#endif

#define BALL_H22 PAD_PM_GPIO6
#define PAD_PM_GPIO6 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_H22_IS_GPIO
#define BALL_H22_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO BALL_H22_IS_GPIO
#endif

#define BALL_D18 PAD_PM_GPIO8
#define PAD_PM_GPIO8 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_D18_IS_GPIO
#define BALL_D18_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO8_IS_GPIO
#define PAD_PM_GPIO8_IS_GPIO BALL_D18_IS_GPIO
#endif

#define BALL_F18 PAD_PM_GPIO12
#define PAD_PM_GPIO12 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_F18_IS_GPIO
#define BALL_F18_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO BALL_F18_IS_GPIO
#endif

#define BALL_E16 PAD_PM_GPIO11
#define PAD_PM_GPIO11 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_E16_IS_GPIO
#define BALL_E16_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO11_IS_GPIO
#define PAD_PM_GPIO11_IS_GPIO BALL_E16_IS_GPIO
#endif

#define BALL_A22 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_A22_IS_GPIO
#define BALL_A22_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_A22_IS_GPIO
#endif

#define BALL_C22 PAD_PM_LED0
#define PAD_PM_LED0 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_C22_IS_GPIO
#define BALL_C22_IS_GPIO 0
#endif
#ifndef PAD_PM_LED0_IS_GPIO
#define PAD_PM_LED0_IS_GPIO BALL_C22_IS_GPIO
#endif

#define BALL_F16 PAD_PM_GPIO9
#define PAD_PM_GPIO9 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_F16_IS_GPIO
#define BALL_F16_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO BALL_F16_IS_GPIO
#endif

#define BALL_H21 PAD_PM_LED1
#define PAD_PM_LED1 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_H21_IS_GPIO
#define BALL_H21_IS_GPIO 0
#endif
#ifndef PAD_PM_LED1_IS_GPIO
#define PAD_PM_LED1_IS_GPIO BALL_H21_IS_GPIO
#endif

#define BALL_E10 PAD_RX_DDCDA_CK
#define PAD_RX_DDCDA_CK 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif
#ifndef PAD_RX_DDCDA_CK_IS_GPIO
#define PAD_RX_DDCDA_CK_IS_GPIO BALL_E10_IS_GPIO
#endif

#define BALL_J22 PAD_VID1
#define PAD_VID1 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_J22_IS_GPIO
#define BALL_J22_IS_GPIO 0
#endif
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_J22_IS_GPIO
#endif

#define BALL_D11 PAD_PM_CEC
#define PAD_PM_CEC 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_D11_IS_GPIO
#define BALL_D11_IS_GPIO 0
#endif
#ifndef PAD_PM_CEC_IS_GPIO
#define PAD_PM_CEC_IS_GPIO BALL_D11_IS_GPIO
#endif

#define BALL_J6 PAD_PM_SD_CDZ
#define PAD_PM_SD_CDZ 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif
#ifndef PAD_PM_SD_CDZ_IS_GPIO
#define PAD_PM_SD_CDZ_IS_GPIO BALL_J6_IS_GPIO
#endif

#define BALL_F17 PAD_PM_GPIO10
#define PAD_PM_GPIO10 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_F17_IS_GPIO
#define BALL_F17_IS_GPIO 0
#endif
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO BALL_F17_IS_GPIO
#endif

#define BALL_F11 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_F11_IS_GPIO
#define BALL_F11_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_F11_IS_GPIO
#endif

#define BALL_K21 PAD_VID0
#define PAD_VID0 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_K21_IS_GPIO
#define BALL_K21_IS_GPIO 0
#endif
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_K21_IS_GPIO
#endif

#define BALL_J21 PAD_PM_IRIN
#define PAD_PM_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_J21_IS_GPIO
#define BALL_J21_IS_GPIO 0
#endif
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_J21_IS_GPIO
#endif

#define BALL_F13 PAD_HDMITX_HPD
#define PAD_HDMITX_HPD 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_F13_IS_GPIO
#define BALL_F13_IS_GPIO 0
#endif
#ifndef PAD_HDMITX_HPD_IS_GPIO
#define PAD_HDMITX_HPD_IS_GPIO BALL_F13_IS_GPIO
#endif

#define BALL_E11 PAD_HDMIRX_HPD
#define PAD_HDMIRX_HPD 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_E11_IS_GPIO
#define BALL_E11_IS_GPIO 0
#endif
#ifndef PAD_HDMIRX_HPD_IS_GPIO
#define PAD_HDMIRX_HPD_IS_GPIO BALL_E11_IS_GPIO
#endif

#define BALL_F10 PAD_RX_DDCDA_DA
#define PAD_RX_DDCDA_DA 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_F10_IS_GPIO
#define BALL_F10_IS_GPIO 0
#endif
#ifndef PAD_RX_DDCDA_DA_IS_GPIO
#define PAD_RX_DDCDA_DA_IS_GPIO BALL_F10_IS_GPIO
#endif

#define BALL_E12 PAD_HDMITX_ARC
#define PAD_HDMITX_ARC 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_E12_IS_GPIO
#define BALL_E12_IS_GPIO 0
#endif
#ifndef PAD_HDMITX_ARC_IS_GPIO
#define PAD_HDMITX_ARC_IS_GPIO BALL_E12_IS_GPIO
#endif

#define BALL_E12 PAD_HDMITX_ARC
#define PAD_HDMITX_ARC 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_E12_IS_GPIO
#define BALL_E12_IS_GPIO 0
#endif
#ifndef PAD_HDMITX_ARC_IS_GPIO
#define PAD_HDMITX_ARC_IS_GPIO BALL_E12_IS_GPIO
#endif

#define BALL_F12 PAD_HDMIRX_ARC
#define PAD_HDMIRX_ARC 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_F12_IS_GPIO
#define BALL_F12_IS_GPIO 0
#endif
#ifndef PAD_HDMIRX_ARC_IS_GPIO
#define PAD_HDMIRX_ARC_IS_GPIO BALL_F12_IS_GPIO
#endif

#define BALL_F12 PAD_HDMIRX_ARC
#define PAD_HDMIRX_ARC 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_F12_IS_GPIO
#define BALL_F12_IS_GPIO 0
#endif
#ifndef PAD_HDMIRX_ARC_IS_GPIO
#define PAD_HDMIRX_ARC_IS_GPIO BALL_F12_IS_GPIO
#endif

#define BALL_G6 PAD_HSYNC_OUT
#define PAD_HSYNC_OUT 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif
#ifndef PAD_HSYNC_OUT_IS_GPIO
#define PAD_HSYNC_OUT_IS_GPIO BALL_G6_IS_GPIO
#endif

#define BALL_E13 PAD_HDMITX_SDA
#define PAD_HDMITX_SDA 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_E13_IS_GPIO
#define BALL_E13_IS_GPIO 0
#endif
#ifndef PAD_HDMITX_SDA_IS_GPIO
#define PAD_HDMITX_SDA_IS_GPIO BALL_E13_IS_GPIO
#endif

#define BALL_D12 PAD_HDMITX_SCL
#define PAD_HDMITX_SCL 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_D12_IS_GPIO
#define BALL_D12_IS_GPIO 0
#endif
#ifndef PAD_HDMITX_SCL_IS_GPIO
#define PAD_HDMITX_SCL_IS_GPIO BALL_D12_IS_GPIO
#endif

#define BALL_F5 PAD_VSYNC_OUT
#define PAD_VSYNC_OUT 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif
#ifndef PAD_VSYNC_OUT_IS_GPIO
#define PAD_VSYNC_OUT_IS_GPIO BALL_F5_IS_GPIO
#endif


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSA6Z17_H_*/
