////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD7SX0_H_
#define _MSD7SX0_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_D2 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_D2_IS_GPIO
#endif 

#define PAD_I2S_OUT_MUTE 9999
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO 0
#endif 

#define BALL_D1 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_D1_IS_GPIO
#define BALL_D1_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_D1_IS_GPIO
#endif 

#define BALL_D3 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_D3_IS_GPIO
#endif 

#define BALL_E1 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_E1_IS_GPIO
#define BALL_E1_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_E1_IS_GPIO
#endif 

#define PAD_I2S_OUT_SDO 9999
#ifndef PAD_I2S_OUT_SDO_IS_GPIO
#define PAD_I2S_OUT_SDO_IS_GPIO 0
#endif 

#define BALL_E2 PAD_GPIO0
#define PAD_GPIO0 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_E2_IS_GPIO
#endif 

#define BALL_E3 PAD_GPIO1
#define PAD_GPIO1 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_E3_IS_GPIO
#endif 

#define PAD_PM_GPIO0 9999
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO 0
#endif 

#define PAD_PM_GPIO1 9999
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO 0
#endif 

#define PAD_PM_GPIO2 9999
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO 0
#endif 

#define PAD_PM_GPIO3 9999
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO 0
#endif 

#define BALL_F2 PAD_PM_GPIO4
#define PAD_PM_GPIO4 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_F2_IS_GPIO
#endif 

#define PAD_PM_GPIO5 9999
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO 0
#endif 

#define BALL_P12 PAD_SM0_CLK
#define PAD_SM0_CLK 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_P12_IS_GPIO
#define BALL_P12_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO BALL_P12_IS_GPIO
#endif 

#define BALL_R16 PAD_SM0_RST
#define PAD_SM0_RST 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_R16_IS_GPIO
#define BALL_R16_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO BALL_R16_IS_GPIO
#endif 

#define BALL_R15 PAD_SM0_C4
#define PAD_SM0_C4 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_R15_IS_GPIO
#define BALL_R15_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO BALL_R15_IS_GPIO
#endif 

#define BALL_T15 PAD_SM0_IO
#define PAD_SM0_IO 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_T15_IS_GPIO
#define BALL_T15_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO BALL_T15_IS_GPIO
#endif 

#define BALL_R14 PAD_SM0_C8
#define PAD_SM0_C8 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_R14_IS_GPIO
#define BALL_R14_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO BALL_R14_IS_GPIO
#endif 

#define BALL_T14 PAD_SM0_CD
#define PAD_SM0_CD 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_T14_IS_GPIO
#define BALL_T14_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO BALL_T14_IS_GPIO
#endif 

#define BALL_P13 PAD_SM0_GPIO
#define PAD_SM0_GPIO 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_P13_IS_GPIO
#define BALL_P13_IS_GPIO 0
#endif 
#ifndef PAD_SM0_GPIO_IS_GPIO
#define PAD_SM0_GPIO_IS_GPIO BALL_P13_IS_GPIO
#endif 

#define BALL_R13 PAD_SM0_PCT
#define PAD_SM0_PCT 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_R13_IS_GPIO
#define BALL_R13_IS_GPIO 0
#endif 
#ifndef PAD_SM0_PCT_IS_GPIO
#define PAD_SM0_PCT_IS_GPIO BALL_R13_IS_GPIO
#endif 

#define PAD_T_GPIO0 9999
#ifndef PAD_T_GPIO0_IS_GPIO
#define PAD_T_GPIO0_IS_GPIO 0
#endif 

#define PAD_T_GPIO1 9999
#ifndef PAD_T_GPIO1_IS_GPIO
#define PAD_T_GPIO1_IS_GPIO 0
#endif 

#define PAD_T_GPIO2 9999
#ifndef PAD_T_GPIO2_IS_GPIO
#define PAD_T_GPIO2_IS_GPIO 0
#endif 

#define BALL_E12 PAD_T_GPIO3
#define PAD_T_GPIO3 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_E12_IS_GPIO
#define BALL_E12_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO3_IS_GPIO
#define PAD_T_GPIO3_IS_GPIO BALL_E12_IS_GPIO
#endif 

#define BALL_G14 PAD_T_GPIO4
#define PAD_T_GPIO4 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_G14_IS_GPIO
#define BALL_G14_IS_GPIO 0
#endif 
#ifndef PAD_T_GPIO4_IS_GPIO
#define PAD_T_GPIO4_IS_GPIO BALL_G14_IS_GPIO
#endif 

#define PAD_T_GPIO5 9999
#ifndef PAD_T_GPIO5_IS_GPIO
#define PAD_T_GPIO5_IS_GPIO 0
#endif 

#define PAD_FUART_RX 9999
#ifndef PAD_FUART_RX_IS_GPIO
#define PAD_FUART_RX_IS_GPIO 0
#endif 

#define PAD_FUART_TX 9999
#ifndef PAD_FUART_TX_IS_GPIO
#define PAD_FUART_TX_IS_GPIO 0
#endif 

#define PAD_FUART_CTS 9999
#ifndef PAD_FUART_CTS_IS_GPIO
#define PAD_FUART_CTS_IS_GPIO 0
#endif 

#define PAD_FUART_RTS 9999
#ifndef PAD_FUART_RTS_IS_GPIO
#define PAD_FUART_RTS_IS_GPIO 0
#endif 

#define BALL_P16 PAD_GPIO2
#define PAD_GPIO2 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_P16_IS_GPIO
#define BALL_P16_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_P16_IS_GPIO
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define BALL_N14 PAD_GPIO4
#define PAD_GPIO4 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_N14_IS_GPIO
#define BALL_N14_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_N14_IS_GPIO
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_CI_A4 9999
#ifndef PAD_CI_A4_IS_GPIO
#define PAD_CI_A4_IS_GPIO 0
#endif 

#define PAD_CI_A3 9999
#ifndef PAD_CI_A3_IS_GPIO
#define PAD_CI_A3_IS_GPIO 0
#endif 

#define PAD_CI_A6 9999
#ifndef PAD_CI_A6_IS_GPIO
#define PAD_CI_A6_IS_GPIO 0
#endif 

#define PAD_CI_A5 9999
#ifndef PAD_CI_A5_IS_GPIO
#define PAD_CI_A5_IS_GPIO 0
#endif 

#define PAD_CI_A0 9999
#ifndef PAD_CI_A0_IS_GPIO
#define PAD_CI_A0_IS_GPIO 0
#endif 

#define PAD_CI_A1 9999
#ifndef PAD_CI_A1_IS_GPIO
#define PAD_CI_A1_IS_GPIO 0
#endif 

#define PAD_CI_A2 9999
#ifndef PAD_CI_A2_IS_GPIO
#define PAD_CI_A2_IS_GPIO 0
#endif 

#define PAD_CI_A7 9999
#ifndef PAD_CI_A7_IS_GPIO
#define PAD_CI_A7_IS_GPIO 0
#endif 

#define PAD_CI_A8 9999
#ifndef PAD_CI_A8_IS_GPIO
#define PAD_CI_A8_IS_GPIO 0
#endif 

#define PAD_CI_A9 9999
#ifndef PAD_CI_A9_IS_GPIO
#define PAD_CI_A9_IS_GPIO 0
#endif 

#define BALL_P15 PAD_GPIO7
#define PAD_GPIO7 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_P15_IS_GPIO
#define BALL_P15_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_P15_IS_GPIO
#endif 

#define BALL_J16 PAD_GPIO8
#define PAD_GPIO8 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_J16_IS_GPIO
#define BALL_J16_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_J16_IS_GPIO
#endif 

#define PAD_CI_A10 9999
#ifndef PAD_CI_A10_IS_GPIO
#define PAD_CI_A10_IS_GPIO 0
#endif 

#define BALL_J14 PAD_CI_A11
#define PAD_CI_A11 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_J14_IS_GPIO
#define BALL_J14_IS_GPIO 0
#endif 
#ifndef PAD_CI_A11_IS_GPIO
#define PAD_CI_A11_IS_GPIO BALL_J14_IS_GPIO
#endif 

#define BALL_L14 PAD_CI_A12
#define PAD_CI_A12 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_L14_IS_GPIO
#define BALL_L14_IS_GPIO 0
#endif 
#ifndef PAD_CI_A12_IS_GPIO
#define PAD_CI_A12_IS_GPIO BALL_L14_IS_GPIO
#endif 

#define BALL_J15 PAD_CI_A13
#define PAD_CI_A13 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_J15_IS_GPIO
#define BALL_J15_IS_GPIO 0
#endif 
#ifndef PAD_CI_A13_IS_GPIO
#define PAD_CI_A13_IS_GPIO BALL_J15_IS_GPIO
#endif 

#define BALL_K15 PAD_CI_A14
#define PAD_CI_A14 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_K15_IS_GPIO
#define BALL_K15_IS_GPIO 0
#endif 
#ifndef PAD_CI_A14_IS_GPIO
#define PAD_CI_A14_IS_GPIO BALL_K15_IS_GPIO
#endif 

#define BALL_L15 PAD_CI_CDZ
#define PAD_CI_CDZ 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_L15_IS_GPIO
#define BALL_L15_IS_GPIO 0
#endif 
#ifndef PAD_CI_CDZ_IS_GPIO
#define PAD_CI_CDZ_IS_GPIO BALL_L15_IS_GPIO
#endif 

#define BALL_K14 PAD_CI_D3
#define PAD_CI_D3 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_K14_IS_GPIO
#define BALL_K14_IS_GPIO 0
#endif 
#ifndef PAD_CI_D3_IS_GPIO
#define PAD_CI_D3_IS_GPIO BALL_K14_IS_GPIO
#endif 

#define BALL_L16 PAD_CI_D4
#define PAD_CI_D4 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_L16_IS_GPIO
#define BALL_L16_IS_GPIO 0
#endif 
#ifndef PAD_CI_D4_IS_GPIO
#define PAD_CI_D4_IS_GPIO BALL_L16_IS_GPIO
#endif 

#define BALL_M16 PAD_CI_D5
#define PAD_CI_D5 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_M16_IS_GPIO
#define BALL_M16_IS_GPIO 0
#endif 
#ifndef PAD_CI_D5_IS_GPIO
#define PAD_CI_D5_IS_GPIO BALL_M16_IS_GPIO
#endif 

#define BALL_M15 PAD_CI_D6
#define PAD_CI_D6 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_M15_IS_GPIO
#define BALL_M15_IS_GPIO 0
#endif 
#ifndef PAD_CI_D6_IS_GPIO
#define PAD_CI_D6_IS_GPIO BALL_M15_IS_GPIO
#endif 

#define BALL_M14 PAD_CI_D7
#define PAD_CI_D7 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_M14_IS_GPIO
#define BALL_M14_IS_GPIO 0
#endif 
#ifndef PAD_CI_D7_IS_GPIO
#define PAD_CI_D7_IS_GPIO BALL_M14_IS_GPIO
#endif 

#define BALL_N15 PAD_CI_CEZ
#define PAD_CI_CEZ 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_N15_IS_GPIO
#define BALL_N15_IS_GPIO 0
#endif 
#ifndef PAD_CI_CEZ_IS_GPIO
#define PAD_CI_CEZ_IS_GPIO BALL_N15_IS_GPIO
#endif 

#define PAD_CI_OEZ 9999
#ifndef PAD_CI_OEZ_IS_GPIO
#define PAD_CI_OEZ_IS_GPIO 0
#endif 

#define PAD_CI_IORDZ 9999
#ifndef PAD_CI_IORDZ_IS_GPIO
#define PAD_CI_IORDZ_IS_GPIO 0
#endif 

#define PAD_CI_IOWRZ 9999
#ifndef PAD_CI_IOWRZ_IS_GPIO
#define PAD_CI_IOWRZ_IS_GPIO 0
#endif 

#define PAD_CI_WEZ 9999
#ifndef PAD_CI_WEZ_IS_GPIO
#define PAD_CI_WEZ_IS_GPIO 0
#endif 

#define PAD_CI_IRQAZ 9999
#ifndef PAD_CI_IRQAZ_IS_GPIO
#define PAD_CI_IRQAZ_IS_GPIO 0
#endif 

#define PAD_CI_RST 9999
#ifndef PAD_CI_RST_IS_GPIO
#define PAD_CI_RST_IS_GPIO 0
#endif 

#define PAD_CI_WAITZ 9999
#ifndef PAD_CI_WAITZ_IS_GPIO
#define PAD_CI_WAITZ_IS_GPIO 0
#endif 

#define PAD_CI_REGZ 9999
#ifndef PAD_CI_REGZ_IS_GPIO
#define PAD_CI_REGZ_IS_GPIO 0
#endif 

#define PAD_CI_D0 9999
#ifndef PAD_CI_D0_IS_GPIO
#define PAD_CI_D0_IS_GPIO 0
#endif 

#define PAD_CI_D1 9999
#ifndef PAD_CI_D1_IS_GPIO
#define PAD_CI_D1_IS_GPIO 0
#endif 

#define PAD_CI_D2 9999
#ifndef PAD_CI_D2_IS_GPIO
#define PAD_CI_D2_IS_GPIO 0
#endif 

#define BALL_M12 PAD_TS0_SYNC
#define PAD_TS0_SYNC 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_M12_IS_GPIO
#define BALL_M12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_M12_IS_GPIO
#endif 

#define BALL_L13 PAD_TS0_VLD
#define PAD_TS0_VLD 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_L13_IS_GPIO
#define BALL_L13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_L13_IS_GPIO
#endif 

#define BALL_K13 PAD_TS0_D0
#define PAD_TS0_D0 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_K13_IS_GPIO
#define BALL_K13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_K13_IS_GPIO
#endif 

#define BALL_K12 PAD_TS0_D1
#define PAD_TS0_D1 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_K12_IS_GPIO
#define BALL_K12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_K12_IS_GPIO
#endif 

#define BALL_L12 PAD_TS0_D2
#define PAD_TS0_D2 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_L12_IS_GPIO
#define BALL_L12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_L12_IS_GPIO
#endif 

#define BALL_P14 PAD_TS0_D3
#define PAD_TS0_D3 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_P14_IS_GPIO
#define BALL_P14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_P14_IS_GPIO
#endif 

#define PAD_TS0_D4 9999
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO 0
#endif 

#define PAD_TS0_D5 9999
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO 0
#endif 

#define PAD_TS0_D6 9999
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO 0
#endif 

#define PAD_TS0_D7 9999
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO 0
#endif 

#define BALL_M13 PAD_TS0_CLK
#define PAD_TS0_CLK 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_M13_IS_GPIO
#define BALL_M13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_M13_IS_GPIO
#endif 

#define PAD_TS1_SYNC 9999
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO 0
#endif 

#define PAD_TS1_VLD 9999
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO 0
#endif 

#define PAD_TS1_D0 9999
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO 0
#endif 

#define PAD_TS1_D1 9999
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO 0
#endif 

#define PAD_TS1_D2 9999
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO 0
#endif 

#define PAD_TS1_D3 9999
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO 0
#endif 

#define PAD_TS1_D4 9999
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO 0
#endif 

#define PAD_TS1_D5 9999
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO 0
#endif 

#define PAD_TS1_D6 9999
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO 0
#endif 

#define PAD_TS1_D7 9999
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO 0
#endif 

#define PAD_TS1_CLK 9999
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO 0
#endif 

#define BALL_G12 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_G12_IS_GPIO
#define BALL_G12_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO BALL_G12_IS_GPIO
#endif 

#define BALL_G13 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_G13_IS_GPIO
#define BALL_G13_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO BALL_G13_IS_GPIO
#endif 

#define BALL_E13 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_E13_IS_GPIO
#define BALL_E13_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO BALL_E13_IS_GPIO
#endif 

#define BALL_F13 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_F13_IS_GPIO
#define BALL_F13_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO BALL_F13_IS_GPIO
#endif 

#define PAD_PM_GPIO6 9999
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO 0
#endif 

#define PAD_PM_GPIO7 9999
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO 0
#endif 

#define PAD_PM_GPIO8 9999
#ifndef PAD_PM_GPIO8_IS_GPIO
#define PAD_PM_GPIO8_IS_GPIO 0
#endif 

#define BALL_H16 PAD_PM_GPIO9
#define PAD_PM_GPIO9 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_H16_IS_GPIO
#define BALL_H16_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO BALL_H16_IS_GPIO
#endif 

#define BALL_H15 PAD_PM_GPIO10
#define PAD_PM_GPIO10 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_H15_IS_GPIO
#define BALL_H15_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO BALL_H15_IS_GPIO
#endif 

#define BALL_E16 PAD_PM_GPIO11
#define PAD_PM_GPIO11 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_E16_IS_GPIO
#define BALL_E16_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO11_IS_GPIO
#define PAD_PM_GPIO11_IS_GPIO BALL_E16_IS_GPIO
#endif 

#define BALL_D13 PAD_PM_GPIO12
#define PAD_PM_GPIO12 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_D13_IS_GPIO
#define BALL_D13_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO BALL_D13_IS_GPIO
#endif 

#define BALL_D14 PAD_PM_GPIO13
#define PAD_PM_GPIO13 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_D14_IS_GPIO
#define BALL_D14_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO BALL_D14_IS_GPIO
#endif 

#define BALL_B15 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_B15_IS_GPIO
#endif 

#define BALL_A15 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_A15_IS_GPIO
#define BALL_A15_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_A15_IS_GPIO
#endif 

#define BALL_C14 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_C14_IS_GPIO
#endif 

#define BALL_A14 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_A14_IS_GPIO
#define BALL_A14_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_A14_IS_GPIO
#endif 

#define BALL_B12 PAD_PM_SPI_RSTZ
#define PAD_PM_SPI_RSTZ 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_B12_IS_GPIO
#define BALL_B12_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_RSTZ_IS_GPIO
#define PAD_PM_SPI_RSTZ_IS_GPIO BALL_B12_IS_GPIO
#endif 

#define PAD_PM_GPIO14 9999
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO 0
#endif 

#define PAD_PM_GPIO15 9999
#ifndef PAD_PM_GPIO15_IS_GPIO
#define PAD_PM_GPIO15_IS_GPIO 0
#endif 

#define BALL_D12 PAD_PM_GPIO16
#define PAD_PM_GPIO16 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_D12_IS_GPIO
#define BALL_D12_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO16_IS_GPIO
#define PAD_PM_GPIO16_IS_GPIO BALL_D12_IS_GPIO
#endif 

#define BALL_D16 PAD_PM_IRIN
#define PAD_PM_IRIN 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_D16_IS_GPIO
#define BALL_D16_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_D16_IS_GPIO
#endif 

#define BALL_C8 PAD_PM_HDMI_CEC
#define PAD_PM_HDMI_CEC 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_CEC_IS_GPIO
#define PAD_PM_HDMI_CEC_IS_GPIO BALL_C8_IS_GPIO
#endif 

#define BALL_C9 PAD_PM_HDMI_HPD
#define PAD_PM_HDMI_HPD 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_C9_IS_GPIO
#define BALL_C9_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_HPD_IS_GPIO
#define PAD_PM_HDMI_HPD_IS_GPIO BALL_C9_IS_GPIO
#endif 

#define BALL_A11 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_A11_IS_GPIO
#define BALL_A11_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_A11_IS_GPIO
#endif 

#define BALL_C11 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_C11_IS_GPIO
#endif 

#define BALL_A12 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_A12_IS_GPIO
#endif 

#define BALL_B11 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_B11_IS_GPIO
#endif 

#define BALL_B13 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO BALL_B13_IS_GPIO
#endif 

#define BALL_C12 PAD_PM_SPI_HOLDZ
#define PAD_PM_SPI_HOLDZ 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_C12_IS_GPIO
#define BALL_C12_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_HOLDZ_IS_GPIO
#define PAD_PM_SPI_HOLDZ_IS_GPIO BALL_C12_IS_GPIO
#endif 

#define PAD_GT1_MDIO 9999
#ifndef PAD_GT1_MDIO_IS_GPIO
#define PAD_GT1_MDIO_IS_GPIO 0
#endif 

#define PAD_GT1_MDC 9999
#ifndef PAD_GT1_MDC_IS_GPIO
#define PAD_GT1_MDC_IS_GPIO 0
#endif 

#define PAD_GT1_TX_CTL 9999
#ifndef PAD_GT1_TX_CTL_IS_GPIO
#define PAD_GT1_TX_CTL_IS_GPIO 0
#endif 

#define PAD_GT1_TX_D3 9999
#ifndef PAD_GT1_TX_D3_IS_GPIO
#define PAD_GT1_TX_D3_IS_GPIO 0
#endif 

#define PAD_GT1_TX_D2 9999
#ifndef PAD_GT1_TX_D2_IS_GPIO
#define PAD_GT1_TX_D2_IS_GPIO 0
#endif 

#define PAD_GT1_TX_D1 9999
#ifndef PAD_GT1_TX_D1_IS_GPIO
#define PAD_GT1_TX_D1_IS_GPIO 0
#endif 

#define PAD_GT1_TX_D0 9999
#ifndef PAD_GT1_TX_D0_IS_GPIO
#define PAD_GT1_TX_D0_IS_GPIO 0
#endif 

#define PAD_GT1_TX_CLK 9999
#ifndef PAD_GT1_TX_CLK_IS_GPIO
#define PAD_GT1_TX_CLK_IS_GPIO 0
#endif 

#define PAD_GT1_RX_CLK 9999
#ifndef PAD_GT1_RX_CLK_IS_GPIO
#define PAD_GT1_RX_CLK_IS_GPIO 0
#endif 

#define PAD_GT1_RX_D3 9999
#ifndef PAD_GT1_RX_D3_IS_GPIO
#define PAD_GT1_RX_D3_IS_GPIO 0
#endif 

#define PAD_GT1_RX_D2 9999
#ifndef PAD_GT1_RX_D2_IS_GPIO
#define PAD_GT1_RX_D2_IS_GPIO 0
#endif 

#define PAD_GT1_RX_D1 9999
#ifndef PAD_GT1_RX_D1_IS_GPIO
#define PAD_GT1_RX_D1_IS_GPIO 0
#endif 

#define PAD_GT1_RX_D0 9999
#ifndef PAD_GT1_RX_D0_IS_GPIO
#define PAD_GT1_RX_D0_IS_GPIO 0
#endif 

#define PAD_GT1_RX_CTL 9999
#ifndef PAD_GT1_RX_CTL_IS_GPIO
#define PAD_GT1_RX_CTL_IS_GPIO 0
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSD7SX0_H_*/
