////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSA8Z17A_H_
#define _MSA8Z17A_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_H3 PAD_I2S_OUT_MUTE
#define PAD_I2S_OUT_MUTE 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO BALL_H3_IS_GPIO
#endif 

#define BALL_H2 PAD_I2S_OUT_SD3
#define PAD_I2S_OUT_SD3 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO BALL_H2_IS_GPIO
#endif 

#define BALL_J3 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_J3_IS_GPIO
#endif 

#define BALL_J2 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_J2_IS_GPIO
#endif 

#define BALL_J1 PAD_I2S_OUT_SD0
#define PAD_I2S_OUT_SD0 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO BALL_J1_IS_GPIO
#endif 

#define BALL_K2 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_K2_IS_GPIO
#endif 

#define BALL_K3 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_K3_IS_GPIO
#endif 

#define BALL_K1 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_K1_IS_GPIO
#define BALL_K1_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_K1_IS_GPIO
#endif 

#define BALL_H4 PAD_GPIO9
#define PAD_GPIO9 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_H4_IS_GPIO
#define BALL_H4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_H4_IS_GPIO
#endif 

#define BALL_G4 PAD_GPIO8
#define PAD_GPIO8 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_G4_IS_GPIO
#endif 

#define BALL_J5 PAD_GPIO7
#define PAD_GPIO7 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define BALL_H5 PAD_GPIO6
#define PAD_GPIO6 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO BALL_H5_IS_GPIO
#endif 

#define BALL_D4 PAD_SD_D1
#define PAD_SD_D1 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_SD_D1_IS_GPIO
#define PAD_SD_D1_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_E5 PAD_SD_D0
#define PAD_SD_D0 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_SD_D0_IS_GPIO
#define PAD_SD_D0_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_D5 PAD_SD_CLK
#define PAD_SD_CLK 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_SD_CLK_IS_GPIO
#define PAD_SD_CLK_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_F5 PAD_SD_CMD
#define PAD_SD_CMD 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_SD_CMD_IS_GPIO
#define PAD_SD_CMD_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_F6 PAD_SD_D3
#define PAD_SD_D3 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_SD_D3_IS_GPIO
#define PAD_SD_D3_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define BALL_G6 PAD_SD_D2
#define PAD_SD_D2 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif 
#ifndef PAD_SD_D2_IS_GPIO
#define PAD_SD_D2_IS_GPIO BALL_G6_IS_GPIO
#endif 

#define BALL_H6 PAD_GPIO5
#define PAD_GPIO5 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_H6_IS_GPIO
#endif 

#define BALL_G5 PAD_GPIO4
#define PAD_GPIO4 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_G5_IS_GPIO
#endif 

#define BALL_J4 PAD_GPIO3
#define PAD_GPIO3 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_J4_IS_GPIO
#endif 

#define BALL_G3 PAD_GPIO2
#define PAD_GPIO2 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_G3_IS_GPIO
#define BALL_G3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_G3_IS_GPIO
#endif 

#define BALL_G1 PAD_GPIO1
#define PAD_GPIO1 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_G1_IS_GPIO
#define BALL_G1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_G1_IS_GPIO
#endif 

#define BALL_G2 PAD_GPIO0
#define PAD_GPIO0 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_G2_IS_GPIO
#define BALL_G2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_G2_IS_GPIO
#endif 

#define BALL_AD26 PAD_CI_CDZ
#define PAD_CI_CDZ 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_AD26_IS_GPIO
#define BALL_AD26_IS_GPIO 0
#endif 
#ifndef PAD_CI_CDZ_IS_GPIO
#define PAD_CI_CDZ_IS_GPIO BALL_AD26_IS_GPIO
#endif 

#define BALL_AF24 PAD_CI_D3
#define PAD_CI_D3 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_AF24_IS_GPIO
#define BALL_AF24_IS_GPIO 0
#endif 
#ifndef PAD_CI_D3_IS_GPIO
#define PAD_CI_D3_IS_GPIO BALL_AF24_IS_GPIO
#endif 

#define BALL_AE23 PAD_CI_D4
#define PAD_CI_D4 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif 
#ifndef PAD_CI_D4_IS_GPIO
#define PAD_CI_D4_IS_GPIO BALL_AE23_IS_GPIO
#endif 

#define BALL_AD23 PAD_CI_D5
#define PAD_CI_D5 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AD23_IS_GPIO
#define BALL_AD23_IS_GPIO 0
#endif 
#ifndef PAD_CI_D5_IS_GPIO
#define PAD_CI_D5_IS_GPIO BALL_AD23_IS_GPIO
#endif 

#define BALL_AE24 PAD_CI_D6
#define PAD_CI_D6 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_AE24_IS_GPIO
#define BALL_AE24_IS_GPIO 0
#endif 
#ifndef PAD_CI_D6_IS_GPIO
#define PAD_CI_D6_IS_GPIO BALL_AE24_IS_GPIO
#endif 

#define BALL_AD24 PAD_CI_D7
#define PAD_CI_D7 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AD24_IS_GPIO
#define BALL_AD24_IS_GPIO 0
#endif 
#ifndef PAD_CI_D7_IS_GPIO
#define PAD_CI_D7_IS_GPIO BALL_AD24_IS_GPIO
#endif 

#define BALL_AG22 PAD_CI_CEZ
#define PAD_CI_CEZ 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_AG22_IS_GPIO
#define BALL_AG22_IS_GPIO 0
#endif 
#ifndef PAD_CI_CEZ_IS_GPIO
#define PAD_CI_CEZ_IS_GPIO BALL_AG22_IS_GPIO
#endif 

#define BALL_AJ22 PAD_CI_A10
#define PAD_CI_A10 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_AJ22_IS_GPIO
#define BALL_AJ22_IS_GPIO 0
#endif 
#ifndef PAD_CI_A10_IS_GPIO
#define PAD_CI_A10_IS_GPIO BALL_AJ22_IS_GPIO
#endif 

#define BALL_AH22 PAD_CI_OEZ
#define PAD_CI_OEZ 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_AH22_IS_GPIO
#define BALL_AH22_IS_GPIO 0
#endif 
#ifndef PAD_CI_OEZ_IS_GPIO
#define PAD_CI_OEZ_IS_GPIO BALL_AH22_IS_GPIO
#endif 

#define BALL_AE25 PAD_CI_IORDZ
#define PAD_CI_IORDZ 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_AE25_IS_GPIO
#define BALL_AE25_IS_GPIO 0
#endif 
#ifndef PAD_CI_IORDZ_IS_GPIO
#define PAD_CI_IORDZ_IS_GPIO BALL_AE25_IS_GPIO
#endif 

#define BALL_AG23 PAD_CI_A11
#define PAD_CI_A11 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_AG23_IS_GPIO
#define BALL_AG23_IS_GPIO 0
#endif 
#ifndef PAD_CI_A11_IS_GPIO
#define PAD_CI_A11_IS_GPIO BALL_AG23_IS_GPIO
#endif 

#define BALL_AF25 PAD_CI_IOWRZ
#define PAD_CI_IOWRZ 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_AF25_IS_GPIO
#define BALL_AF25_IS_GPIO 0
#endif 
#ifndef PAD_CI_IOWRZ_IS_GPIO
#define PAD_CI_IOWRZ_IS_GPIO BALL_AF25_IS_GPIO
#endif 

#define BALL_AH23 PAD_CI_A9
#define PAD_CI_A9 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_AH23_IS_GPIO
#define BALL_AH23_IS_GPIO 0
#endif 
#ifndef PAD_CI_A9_IS_GPIO
#define PAD_CI_A9_IS_GPIO BALL_AH23_IS_GPIO
#endif 

#define BALL_AG24 PAD_CI_A8
#define PAD_CI_A8 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_AG24_IS_GPIO
#define BALL_AG24_IS_GPIO 0
#endif 
#ifndef PAD_CI_A8_IS_GPIO
#define PAD_CI_A8_IS_GPIO BALL_AG24_IS_GPIO
#endif 

#define BALL_AH24 PAD_CI_A13
#define PAD_CI_A13 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_AH24_IS_GPIO
#define BALL_AH24_IS_GPIO 0
#endif 
#ifndef PAD_CI_A13_IS_GPIO
#define PAD_CI_A13_IS_GPIO BALL_AH24_IS_GPIO
#endif 

#define BALL_AJ24 PAD_CI_A14
#define PAD_CI_A14 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_AJ24_IS_GPIO
#define BALL_AJ24_IS_GPIO 0
#endif 
#ifndef PAD_CI_A14_IS_GPIO
#define PAD_CI_A14_IS_GPIO BALL_AJ24_IS_GPIO
#endif 

#define BALL_AG25 PAD_CI_WEZ
#define PAD_CI_WEZ 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_AG25_IS_GPIO
#define BALL_AG25_IS_GPIO 0
#endif 
#ifndef PAD_CI_WEZ_IS_GPIO
#define PAD_CI_WEZ_IS_GPIO BALL_AG25_IS_GPIO
#endif 

#define BALL_AJ25 PAD_CI_IRQAZ
#define PAD_CI_IRQAZ 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_AJ25_IS_GPIO
#define BALL_AJ25_IS_GPIO 0
#endif 
#ifndef PAD_CI_IRQAZ_IS_GPIO
#define PAD_CI_IRQAZ_IS_GPIO BALL_AJ25_IS_GPIO
#endif 

#define BALL_AG26 PAD_CI_A7
#define PAD_CI_A7 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_AG26_IS_GPIO
#define BALL_AG26_IS_GPIO 0
#endif 
#ifndef PAD_CI_A7_IS_GPIO
#define PAD_CI_A7_IS_GPIO BALL_AG26_IS_GPIO
#endif 

#define BALL_AH25 PAD_CI_A12
#define PAD_CI_A12 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_AH25_IS_GPIO
#define BALL_AH25_IS_GPIO 0
#endif 
#ifndef PAD_CI_A12_IS_GPIO
#define PAD_CI_A12_IS_GPIO BALL_AH25_IS_GPIO
#endif 

#define BALL_AH26 PAD_CI_A6
#define PAD_CI_A6 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_AH26_IS_GPIO
#define BALL_AH26_IS_GPIO 0
#endif 
#ifndef PAD_CI_A6_IS_GPIO
#define PAD_CI_A6_IS_GPIO BALL_AH26_IS_GPIO
#endif 

#define BALL_AH27 PAD_CI_A4
#define PAD_CI_A4 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_AH27_IS_GPIO
#define BALL_AH27_IS_GPIO 0
#endif 
#ifndef PAD_CI_A4_IS_GPIO
#define PAD_CI_A4_IS_GPIO BALL_AH27_IS_GPIO
#endif 

#define BALL_AF26 PAD_CI_WAITZ
#define PAD_CI_WAITZ 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_AF26_IS_GPIO
#define BALL_AF26_IS_GPIO 0
#endif 
#ifndef PAD_CI_WAITZ_IS_GPIO
#define PAD_CI_WAITZ_IS_GPIO BALL_AF26_IS_GPIO
#endif 

#define BALL_AG28 PAD_CI_A2
#define PAD_CI_A2 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_AG28_IS_GPIO
#define BALL_AG28_IS_GPIO 0
#endif 
#ifndef PAD_CI_A2_IS_GPIO
#define PAD_CI_A2_IS_GPIO BALL_AG28_IS_GPIO
#endif 

#define BALL_AD25 PAD_CI_RST
#define PAD_CI_RST 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_AD25_IS_GPIO
#define BALL_AD25_IS_GPIO 0
#endif 
#ifndef PAD_CI_RST_IS_GPIO
#define PAD_CI_RST_IS_GPIO BALL_AD25_IS_GPIO
#endif 

#define BALL_AG27 PAD_CI_A5
#define PAD_CI_A5 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_AG27_IS_GPIO
#define BALL_AG27_IS_GPIO 0
#endif 
#ifndef PAD_CI_A5_IS_GPIO
#define PAD_CI_A5_IS_GPIO BALL_AG27_IS_GPIO
#endif 

#define BALL_AJ27 PAD_CI_A3
#define PAD_CI_A3 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_AJ27_IS_GPIO
#define BALL_AJ27_IS_GPIO 0
#endif 
#ifndef PAD_CI_A3_IS_GPIO
#define PAD_CI_A3_IS_GPIO BALL_AJ27_IS_GPIO
#endif 

#define BALL_AE26 PAD_CI_REGZ
#define PAD_CI_REGZ 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_AE26_IS_GPIO
#define BALL_AE26_IS_GPIO 0
#endif 
#ifndef PAD_CI_REGZ_IS_GPIO
#define PAD_CI_REGZ_IS_GPIO BALL_AE26_IS_GPIO
#endif 

#define BALL_AJ28 PAD_CI_A1
#define PAD_CI_A1 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_AJ28_IS_GPIO
#define BALL_AJ28_IS_GPIO 0
#endif 
#ifndef PAD_CI_A1_IS_GPIO
#define PAD_CI_A1_IS_GPIO BALL_AJ28_IS_GPIO
#endif 

#define BALL_AH28 PAD_CI_A0
#define PAD_CI_A0 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_AH28_IS_GPIO
#define BALL_AH28_IS_GPIO 0
#endif 
#ifndef PAD_CI_A0_IS_GPIO
#define PAD_CI_A0_IS_GPIO BALL_AH28_IS_GPIO
#endif 

#define BALL_AG29 PAD_CI_D0
#define PAD_CI_D0 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AG29_IS_GPIO
#define BALL_AG29_IS_GPIO 0
#endif 
#ifndef PAD_CI_D0_IS_GPIO
#define PAD_CI_D0_IS_GPIO BALL_AG29_IS_GPIO
#endif 

#define BALL_AH29 PAD_CI_D1
#define PAD_CI_D1 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_AH29_IS_GPIO
#define BALL_AH29_IS_GPIO 0
#endif 
#ifndef PAD_CI_D1_IS_GPIO
#define PAD_CI_D1_IS_GPIO BALL_AH29_IS_GPIO
#endif 

#define BALL_AF27 PAD_CI_D2
#define PAD_CI_D2 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_AF27_IS_GPIO
#define BALL_AF27_IS_GPIO 0
#endif 
#ifndef PAD_CI_D2_IS_GPIO
#define PAD_CI_D2_IS_GPIO BALL_AF27_IS_GPIO
#endif 

#define BALL_Y25 PAD_SM0_IO
#define PAD_SM0_IO 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_Y25_IS_GPIO
#define BALL_Y25_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO BALL_Y25_IS_GPIO
#endif 

#define BALL_W25 PAD_SM0_RST
#define PAD_SM0_RST 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_W25_IS_GPIO
#define BALL_W25_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO BALL_W25_IS_GPIO
#endif 

#define BALL_V26 PAD_SM0_VSEL
#define PAD_SM0_VSEL 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_V26_IS_GPIO
#define BALL_V26_IS_GPIO 0
#endif 
#ifndef PAD_SM0_VSEL_IS_GPIO
#define PAD_SM0_VSEL_IS_GPIO BALL_V26_IS_GPIO
#endif 

#define BALL_V25 PAD_SM0_C4
#define PAD_SM0_C4 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_V25_IS_GPIO
#define BALL_V25_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO BALL_V25_IS_GPIO
#endif 

#define BALL_W26 PAD_SM0_CLK
#define PAD_SM0_CLK 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_W26_IS_GPIO
#define BALL_W26_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO BALL_W26_IS_GPIO
#endif 

#define BALL_U24 PAD_SM0_VCC
#define PAD_SM0_VCC 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_U24_IS_GPIO
#define BALL_U24_IS_GPIO 0
#endif 
#ifndef PAD_SM0_VCC_IS_GPIO
#define PAD_SM0_VCC_IS_GPIO BALL_U24_IS_GPIO
#endif 

#define BALL_V24 PAD_SM0_CD
#define PAD_SM0_CD 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_V24_IS_GPIO
#define BALL_V24_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO BALL_V24_IS_GPIO
#endif 

#define BALL_W24 PAD_SM0_C8
#define PAD_SM0_C8 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_W24_IS_GPIO
#define BALL_W24_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO BALL_W24_IS_GPIO
#endif 

#define BALL_U25 PAD_TS2_SYNC
#define PAD_TS2_SYNC 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_U25_IS_GPIO
#define BALL_U25_IS_GPIO 0
#endif 
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_U25_IS_GPIO
#endif 

#define BALL_T25 PAD_TS2_D0
#define PAD_TS2_D0 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_T25_IS_GPIO
#define BALL_T25_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_T25_IS_GPIO
#endif 

#define BALL_T26 PAD_TS2_VLD
#define PAD_TS2_VLD 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_T26_IS_GPIO
#define BALL_T26_IS_GPIO 0
#endif 
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_T26_IS_GPIO
#endif 

#define BALL_R26 PAD_TS2_D1
#define PAD_TS2_D1 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_R26_IS_GPIO
#define BALL_R26_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO BALL_R26_IS_GPIO
#endif 

#define BALL_R25 PAD_TS2_D3
#define PAD_TS2_D3 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_R25_IS_GPIO
#define BALL_R25_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO BALL_R25_IS_GPIO
#endif 

#define BALL_T24 PAD_TS2_D2
#define PAD_TS2_D2 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_T24_IS_GPIO
#define BALL_T24_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO BALL_T24_IS_GPIO
#endif 

#define BALL_P24 PAD_TS2_D5
#define PAD_TS2_D5 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_P24_IS_GPIO
#define BALL_P24_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO BALL_P24_IS_GPIO
#endif 

#define BALL_R24 PAD_TS2_D4
#define PAD_TS2_D4 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_R24_IS_GPIO
#define BALL_R24_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO BALL_R24_IS_GPIO
#endif 

#define BALL_N26 PAD_TS2_D7
#define PAD_TS2_D7 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_N26_IS_GPIO
#define BALL_N26_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO BALL_N26_IS_GPIO
#endif 

#define BALL_P25 PAD_TS2_D6
#define PAD_TS2_D6 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_P25_IS_GPIO
#define BALL_P25_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO BALL_P25_IS_GPIO
#endif 

#define BALL_A28 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_A28_IS_GPIO
#define BALL_A28_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_A28_IS_GPIO
#endif 

#define BALL_N25 PAD_TS2_CLK
#define PAD_TS2_CLK 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_N25_IS_GPIO
#define BALL_N25_IS_GPIO 0
#endif 
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_N25_IS_GPIO
#endif 

#define BALL_N24 PAD_TS1_VLD
#define PAD_TS1_VLD 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_N24_IS_GPIO
#define BALL_N24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_N24_IS_GPIO
#endif 

#define BALL_E24 PAD_TS1_SYNC
#define PAD_TS1_SYNC 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_E24_IS_GPIO
#define BALL_E24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_E24_IS_GPIO
#endif 

#define BALL_G25 PAD_TS1_D1
#define PAD_TS1_D1 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_G25_IS_GPIO
#define BALL_G25_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_G25_IS_GPIO
#endif 

#define BALL_D24 PAD_TS1_D0
#define PAD_TS1_D0 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_D24_IS_GPIO
#define BALL_D24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_D24_IS_GPIO
#endif 

#define BALL_G26 PAD_TS1_D3
#define PAD_TS1_D3 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_G26_IS_GPIO
#define BALL_G26_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_G26_IS_GPIO
#endif 

#define BALL_E25 PAD_TS1_D2
#define PAD_TS1_D2 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_E25_IS_GPIO
#define BALL_E25_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_E25_IS_GPIO
#endif 

#define BALL_G24 PAD_TS1_D5
#define PAD_TS1_D5 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_G24_IS_GPIO
#define BALL_G24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_G24_IS_GPIO
#endif 

#define BALL_F24 PAD_TS1_D4
#define PAD_TS1_D4 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_F24_IS_GPIO
#define BALL_F24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_F24_IS_GPIO
#endif 

#define BALL_H24 PAD_TS1_D7
#define PAD_TS1_D7 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_H24_IS_GPIO
#define BALL_H24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_H24_IS_GPIO
#endif 

#define BALL_F25 PAD_TS1_D6
#define PAD_TS1_D6 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_F25_IS_GPIO
#define BALL_F25_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_F25_IS_GPIO
#endif 

#define BALL_M28 PAD_TS0_SYNC
#define PAD_TS0_SYNC 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_M28_IS_GPIO
#define BALL_M28_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_M28_IS_GPIO
#endif 

#define BALL_D26 PAD_TS1_CLK
#define PAD_TS1_CLK 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_D26_IS_GPIO
#define BALL_D26_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_D26_IS_GPIO
#endif 

#define BALL_M27 PAD_TS0_D0
#define PAD_TS0_D0 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_M27_IS_GPIO
#define BALL_M27_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_M27_IS_GPIO
#endif 

#define BALL_M29 PAD_TS0_VLD
#define PAD_TS0_VLD 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_M29_IS_GPIO
#define BALL_M29_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_M29_IS_GPIO
#endif 

#define BALL_L28 PAD_TS0_D2
#define PAD_TS0_D2 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_L28_IS_GPIO
#define BALL_L28_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_L28_IS_GPIO
#endif 

#define BALL_L29 PAD_TS0_D1
#define PAD_TS0_D1 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_L29_IS_GPIO
#define BALL_L29_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_L29_IS_GPIO
#endif 

#define BALL_K28 PAD_TS0_D4
#define PAD_TS0_D4 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_K28_IS_GPIO
#define BALL_K28_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_K28_IS_GPIO
#endif 

#define BALL_L27 PAD_TS0_D3
#define PAD_TS0_D3 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_L27_IS_GPIO
#define BALL_L27_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_L27_IS_GPIO
#endif 

#define BALL_K27 PAD_TS0_D5
#define PAD_TS0_D5 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_K27_IS_GPIO
#define BALL_K27_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_K27_IS_GPIO
#endif 

#define BALL_J28 PAD_TS0_D6
#define PAD_TS0_D6 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_J28_IS_GPIO
#define BALL_J28_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_J28_IS_GPIO
#endif 

#define BALL_J29 PAD_TS0_D7
#define PAD_TS0_D7 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_J29_IS_GPIO
#define BALL_J29_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_J29_IS_GPIO
#endif 

#define BALL_J27 PAD_TS0_CLK
#define PAD_TS0_CLK 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_J27_IS_GPIO
#define BALL_J27_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_J27_IS_GPIO
#endif 

#define BALL_E26 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_E26_IS_GPIO
#define BALL_E26_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO BALL_E26_IS_GPIO
#endif 

#define BALL_J26 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_J26_IS_GPIO
#define BALL_J26_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO BALL_J26_IS_GPIO
#endif 

#define BALL_F26 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_F26_IS_GPIO
#define BALL_F26_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO BALL_F26_IS_GPIO
#endif 

#define BALL_H25 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_H25_IS_GPIO
#define BALL_H25_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO BALL_H25_IS_GPIO
#endif 

#define BALL_J25 PAD_GT0_MDIO
#define PAD_GT0_MDIO 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_J25_IS_GPIO
#define BALL_J25_IS_GPIO 0
#endif 
#ifndef PAD_GT0_MDIO_IS_GPIO
#define PAD_GT0_MDIO_IS_GPIO BALL_J25_IS_GPIO
#endif 

#define BALL_J24 PAD_GT0_MDC
#define PAD_GT0_MDC 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_J24_IS_GPIO
#define BALL_J24_IS_GPIO 0
#endif 
#ifndef PAD_GT0_MDC_IS_GPIO
#define PAD_GT0_MDC_IS_GPIO BALL_J24_IS_GPIO
#endif 

#define BALL_H29 PAD_GT0_TX_CTL
#define PAD_GT0_TX_CTL 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_H29_IS_GPIO
#define BALL_H29_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_CTL_IS_GPIO
#define PAD_GT0_TX_CTL_IS_GPIO BALL_H29_IS_GPIO
#endif 

#define BALL_H28 PAD_GT0_TX_D3
#define PAD_GT0_TX_D3 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_H28_IS_GPIO
#define BALL_H28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D3_IS_GPIO
#define PAD_GT0_TX_D3_IS_GPIO BALL_H28_IS_GPIO
#endif 

#define BALL_H27 PAD_GT0_TX_D2
#define PAD_GT0_TX_D2 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_H27_IS_GPIO
#define BALL_H27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D2_IS_GPIO
#define PAD_GT0_TX_D2_IS_GPIO BALL_H27_IS_GPIO
#endif 

#define BALL_G28 PAD_GT0_TX_D1
#define PAD_GT0_TX_D1 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_G28_IS_GPIO
#define BALL_G28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D1_IS_GPIO
#define PAD_GT0_TX_D1_IS_GPIO BALL_G28_IS_GPIO
#endif 

#define BALL_G27 PAD_GT0_TX_D0
#define PAD_GT0_TX_D0 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_G27_IS_GPIO
#define BALL_G27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D0_IS_GPIO
#define PAD_GT0_TX_D0_IS_GPIO BALL_G27_IS_GPIO
#endif 

#define BALL_F28 PAD_GT0_TX_CLK
#define PAD_GT0_TX_CLK 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_F28_IS_GPIO
#define BALL_F28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_CLK_IS_GPIO
#define PAD_GT0_TX_CLK_IS_GPIO BALL_F28_IS_GPIO
#endif 

#define BALL_F29 PAD_GT0_RX_CLK
#define PAD_GT0_RX_CLK 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_F29_IS_GPIO
#define BALL_F29_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_CLK_IS_GPIO
#define PAD_GT0_RX_CLK_IS_GPIO BALL_F29_IS_GPIO
#endif 

#define BALL_F27 PAD_GT0_RX_D3
#define PAD_GT0_RX_D3 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_F27_IS_GPIO
#define BALL_F27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D3_IS_GPIO
#define PAD_GT0_RX_D3_IS_GPIO BALL_F27_IS_GPIO
#endif 

#define BALL_E29 PAD_GT0_RX_D2
#define PAD_GT0_RX_D2 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_E29_IS_GPIO
#define BALL_E29_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D2_IS_GPIO
#define PAD_GT0_RX_D2_IS_GPIO BALL_E29_IS_GPIO
#endif 

#define BALL_E28 PAD_GT0_RX_D1
#define PAD_GT0_RX_D1 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_E28_IS_GPIO
#define BALL_E28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D1_IS_GPIO
#define PAD_GT0_RX_D1_IS_GPIO BALL_E28_IS_GPIO
#endif 

#define BALL_E27 PAD_GT0_RX_D0
#define PAD_GT0_RX_D0 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_E27_IS_GPIO
#define BALL_E27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D0_IS_GPIO
#define PAD_GT0_RX_D0_IS_GPIO BALL_E27_IS_GPIO
#endif 

#define BALL_D28 PAD_GT0_RX_CTL
#define PAD_GT0_RX_CTL 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_D28_IS_GPIO
#define BALL_D28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_CTL_IS_GPIO
#define PAD_GT0_RX_CTL_IS_GPIO BALL_D28_IS_GPIO
#endif 

#define BALL_C25 PAD_GT1_MDIO
#define PAD_GT1_MDIO 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_C25_IS_GPIO
#define BALL_C25_IS_GPIO 0
#endif 
#ifndef PAD_GT1_MDIO_IS_GPIO
#define PAD_GT1_MDIO_IS_GPIO BALL_C25_IS_GPIO
#endif 

#define BALL_B25 PAD_GT1_MDC
#define PAD_GT1_MDC 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_B25_IS_GPIO
#define BALL_B25_IS_GPIO 0
#endif 
#ifndef PAD_GT1_MDC_IS_GPIO
#define PAD_GT1_MDC_IS_GPIO BALL_B25_IS_GPIO
#endif 

#define BALL_C24 PAD_GT1_TX_CTL
#define PAD_GT1_TX_CTL 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_C24_IS_GPIO
#define BALL_C24_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_CTL_IS_GPIO
#define PAD_GT1_TX_CTL_IS_GPIO BALL_C24_IS_GPIO
#endif 

#define BALL_B24 PAD_GT1_TX_D3
#define PAD_GT1_TX_D3 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_B24_IS_GPIO
#define BALL_B24_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D3_IS_GPIO
#define PAD_GT1_TX_D3_IS_GPIO BALL_B24_IS_GPIO
#endif 

#define BALL_A24 PAD_GT1_TX_D2
#define PAD_GT1_TX_D2 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_A24_IS_GPIO
#define BALL_A24_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D2_IS_GPIO
#define PAD_GT1_TX_D2_IS_GPIO BALL_A24_IS_GPIO
#endif 

#define BALL_C23 PAD_GT1_TX_D1
#define PAD_GT1_TX_D1 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_C23_IS_GPIO
#define BALL_C23_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D1_IS_GPIO
#define PAD_GT1_TX_D1_IS_GPIO BALL_C23_IS_GPIO
#endif 

#define BALL_A23 PAD_GT1_TX_D0
#define PAD_GT1_TX_D0 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_A23_IS_GPIO
#define BALL_A23_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_D0_IS_GPIO
#define PAD_GT1_TX_D0_IS_GPIO BALL_A23_IS_GPIO
#endif 

#define BALL_B23 PAD_GT1_TX_CLK
#define PAD_GT1_TX_CLK 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_B23_IS_GPIO
#define BALL_B23_IS_GPIO 0
#endif 
#ifndef PAD_GT1_TX_CLK_IS_GPIO
#define PAD_GT1_TX_CLK_IS_GPIO BALL_B23_IS_GPIO
#endif 

#define BALL_C22 PAD_GT1_RX_CLK
#define PAD_GT1_RX_CLK 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_C22_IS_GPIO
#define BALL_C22_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_CLK_IS_GPIO
#define PAD_GT1_RX_CLK_IS_GPIO BALL_C22_IS_GPIO
#endif 

#define BALL_B22 PAD_GT1_RX_D3
#define PAD_GT1_RX_D3 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_B22_IS_GPIO
#define BALL_B22_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D3_IS_GPIO
#define PAD_GT1_RX_D3_IS_GPIO BALL_B22_IS_GPIO
#endif 

#define BALL_C21 PAD_GT1_RX_D2
#define PAD_GT1_RX_D2 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_C21_IS_GPIO
#define BALL_C21_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D2_IS_GPIO
#define PAD_GT1_RX_D2_IS_GPIO BALL_C21_IS_GPIO
#endif 

#define BALL_A21 PAD_GT1_RX_D0
#define PAD_GT1_RX_D0 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_A21_IS_GPIO
#define BALL_A21_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D0_IS_GPIO
#define PAD_GT1_RX_D0_IS_GPIO BALL_A21_IS_GPIO
#endif 

#define BALL_B21 PAD_GT1_RX_D1
#define PAD_GT1_RX_D1 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_B21_IS_GPIO
#define BALL_B21_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_D1_IS_GPIO
#define PAD_GT1_RX_D1_IS_GPIO BALL_B21_IS_GPIO
#endif 

#define BALL_C20 PAD_GT1_RX_CTL
#define PAD_GT1_RX_CTL 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_C20_IS_GPIO
#define BALL_C20_IS_GPIO 0
#endif 
#ifndef PAD_GT1_RX_CTL_IS_GPIO
#define PAD_GT1_RX_CTL_IS_GPIO BALL_C20_IS_GPIO
#endif 

#define BALL_F22 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_F22_IS_GPIO
#define BALL_F22_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_F22_IS_GPIO
#endif 

#define BALL_F23 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_F23_IS_GPIO
#define BALL_F23_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_F23_IS_GPIO
#endif 

#define BALL_E22 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_E22_IS_GPIO
#define BALL_E22_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_E22_IS_GPIO
#endif 

#define BALL_F21 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_F21_IS_GPIO
#define BALL_F21_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_F21_IS_GPIO
#endif 

#define BALL_E23 PAD_SAR_GPIO4
#define PAD_SAR_GPIO4 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_E23_IS_GPIO
#define BALL_E23_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO4_IS_GPIO
#define PAD_SAR_GPIO4_IS_GPIO BALL_E23_IS_GPIO
#endif 

#define BALL_C28 PAD_PM_GPIO0
#define PAD_PM_GPIO0 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_C28_IS_GPIO
#define BALL_C28_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_C28_IS_GPIO
#endif 

#define BALL_B27 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_B27_IS_GPIO
#define BALL_B27_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_B27_IS_GPIO
#endif 

#define BALL_D27 PAD_PM_GPIO1
#define PAD_PM_GPIO1 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_D27_IS_GPIO
#define BALL_D27_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_D27_IS_GPIO
#endif 

#define BALL_C26 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_C26_IS_GPIO
#define BALL_C26_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_C26_IS_GPIO
#endif 

#define BALL_E21 PAD_PM_GPIO2
#define PAD_PM_GPIO2 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_E21_IS_GPIO
#define BALL_E21_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO BALL_E21_IS_GPIO
#endif 

#define BALL_A26 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_A26_IS_GPIO
#define BALL_A26_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_A26_IS_GPIO
#endif 

#define BALL_D21 PAD_PM_GPIO3
#define PAD_PM_GPIO3 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_D21_IS_GPIO
#define BALL_D21_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO BALL_D21_IS_GPIO
#endif 

#define BALL_A27 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_A27_IS_GPIO
#define BALL_A27_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO BALL_A27_IS_GPIO
#endif 

#define BALL_F20 PAD_PM_GPIO4
#define PAD_PM_GPIO4 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_F20_IS_GPIO
#define BALL_F20_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_F20_IS_GPIO
#endif 

#define BALL_B26 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_B26_IS_GPIO
#define BALL_B26_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_B26_IS_GPIO
#endif 

#define BALL_E20 PAD_PM_GPIO5
#define PAD_PM_GPIO5 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_E20_IS_GPIO
#define BALL_E20_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO BALL_E20_IS_GPIO
#endif 

#define BALL_F18 PAD_PM_GPIO6
#define PAD_PM_GPIO6 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_F18_IS_GPIO
#define BALL_F18_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO BALL_F18_IS_GPIO
#endif 

#define BALL_D20 PAD_PM_GPIO11
#define PAD_PM_GPIO11 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_D20_IS_GPIO
#define BALL_D20_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO11_IS_GPIO
#define PAD_PM_GPIO11_IS_GPIO BALL_D20_IS_GPIO
#endif 

#define BALL_F19 PAD_PM_GPIO7
#define PAD_PM_GPIO7 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_F19_IS_GPIO
#define BALL_F19_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO BALL_F19_IS_GPIO
#endif 

#define BALL_E18 PAD_PM_GPIO12
#define PAD_PM_GPIO12 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_E18_IS_GPIO
#define BALL_E18_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO BALL_E18_IS_GPIO
#endif 

#define BALL_E19 PAD_PM_GPIO8
#define PAD_PM_GPIO8 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_E19_IS_GPIO
#define BALL_E19_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO8_IS_GPIO
#define PAD_PM_GPIO8_IS_GPIO BALL_E19_IS_GPIO
#endif 

#define BALL_D18 PAD_PM_GPIO13
#define PAD_PM_GPIO13 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_D18_IS_GPIO
#define BALL_D18_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO BALL_D18_IS_GPIO
#endif 

#define BALL_F17 PAD_PM_GPIO9
#define PAD_PM_GPIO9 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_F17_IS_GPIO
#define BALL_F17_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO BALL_F17_IS_GPIO
#endif 

#define BALL_D17 PAD_PM_GPIO14
#define PAD_PM_GPIO14 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_D17_IS_GPIO
#define BALL_D17_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO BALL_D17_IS_GPIO
#endif 

#define BALL_E16 PAD_PM_GPIO10
#define PAD_PM_GPIO10 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_E16_IS_GPIO
#define BALL_E16_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO BALL_E16_IS_GPIO
#endif 

#define BALL_E17 PAD_PM_GPIO15
#define PAD_PM_GPIO15 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO15_IS_GPIO
#define PAD_PM_GPIO15_IS_GPIO BALL_E17_IS_GPIO
#endif 

#define BALL_F16 PAD_VID0
#define PAD_VID0 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_F16_IS_GPIO
#define BALL_F16_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_F16_IS_GPIO
#endif 

#define BALL_D15 PAD_VID1
#define PAD_VID1 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_D15_IS_GPIO
#define BALL_D15_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_D15_IS_GPIO
#endif 

#define BALL_B20 PAD_PM_LED0
#define PAD_PM_LED0 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_B20_IS_GPIO
#define BALL_B20_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED0_IS_GPIO
#define PAD_PM_LED0_IS_GPIO BALL_B20_IS_GPIO
#endif 

#define BALL_A20 PAD_PM_LED1
#define PAD_PM_LED1 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_A20_IS_GPIO
#define BALL_A20_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED1_IS_GPIO
#define PAD_PM_LED1_IS_GPIO BALL_A20_IS_GPIO
#endif 

#define BALL_E6 PAD_PM_CEC
#define PAD_PM_CEC 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_PM_CEC_IS_GPIO
#define PAD_PM_CEC_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_F7 PAD_HDMIRX_HPD
#define PAD_HDMIRX_HPD 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_HPD_IS_GPIO
#define PAD_HDMIRX_HPD_IS_GPIO BALL_F7_IS_GPIO
#endif 

#define BALL_F10 PAD_HDMITX_HPD
#define PAD_HDMITX_HPD 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_F10_IS_GPIO
#define BALL_F10_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_HPD_IS_GPIO
#define PAD_HDMITX_HPD_IS_GPIO BALL_F10_IS_GPIO
#endif 

#define BALL_E8 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_D7 PAD_RX_DDCDA_DA
#define PAD_RX_DDCDA_DA 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_RX_DDCDA_DA_IS_GPIO
#define PAD_RX_DDCDA_DA_IS_GPIO BALL_D7_IS_GPIO
#endif 

#define BALL_D6 PAD_RX_DDCDA_CK
#define PAD_RX_DDCDA_CK 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif 
#ifndef PAD_RX_DDCDA_CK_IS_GPIO
#define PAD_RX_DDCDA_CK_IS_GPIO BALL_D6_IS_GPIO
#endif 

#define BALL_AB26 PAD_PM_IRIN
#define PAD_PM_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_AB26_IS_GPIO
#define BALL_AB26_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_AB26_IS_GPIO
#endif 

#define BALL_E4 PAD_PM_SD_CDZ
#define PAD_PM_SD_CDZ 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_PM_SD_CDZ_IS_GPIO
#define PAD_PM_SD_CDZ_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_F9 PAD_HDMITX_ARC
#define PAD_HDMITX_ARC 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_ARC_IS_GPIO
#define PAD_HDMITX_ARC_IS_GPIO BALL_F9_IS_GPIO
#endif 

#define BALL_E7 PAD_HDMIRX_ARC
#define PAD_HDMIRX_ARC 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_ARC_IS_GPIO
#define PAD_HDMIRX_ARC_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_F9 PAD_HDMITX_ARC
#define PAD_HDMITX_ARC 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_ARC_IS_GPIO
#define PAD_HDMITX_ARC_IS_GPIO BALL_F9_IS_GPIO
#endif 

#define BALL_E7 PAD_HDMIRX_ARC
#define PAD_HDMIRX_ARC 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_ARC_IS_GPIO
#define PAD_HDMIRX_ARC_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_D9 PAD_HSYNC_OUT
#define PAD_HSYNC_OUT 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_D9_IS_GPIO
#define BALL_D9_IS_GPIO 0
#endif 
#ifndef PAD_HSYNC_OUT_IS_GPIO
#define PAD_HSYNC_OUT_IS_GPIO BALL_D9_IS_GPIO
#endif 

#define BALL_F8 PAD_VSYNC_OUT
#define PAD_VSYNC_OUT 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_VSYNC_OUT_IS_GPIO
#define PAD_VSYNC_OUT_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define BALL_E9 PAD_HDMITX_SCL
#define PAD_HDMITX_SCL 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SCL_IS_GPIO
#define PAD_HDMITX_SCL_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define BALL_E10 PAD_HDMITX_SDA
#define PAD_HDMITX_SDA 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SDA_IS_GPIO
#define PAD_HDMITX_SDA_IS_GPIO BALL_E10_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256
#define PADS_EMMC_IO16      1257
#define PAD_I2S_OUT_SDO     1258
#define PADS_SM1_IO         1259
#define PAD_EMMC_IO0        1260
#define PAD_EMMC_IO16       1261
#define PAD_EMMC_IO12       1262
#define PAD_SDIO_IO0        1263
#define PAD_EMMC_IO11       1264

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSA8Z17A_H_*/
