////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSO9580AP_H_
#define _MSO9580AP_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_G17 PAD_I2S_OUT_MUTE
#define PAD_I2S_OUT_MUTE 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_G17_IS_GPIO
#define BALL_G17_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO BALL_G17_IS_GPIO
#endif 

#define BALL_D10 PAD_I2S_OUT_SD3
#define PAD_I2S_OUT_SD3 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_D10_IS_GPIO
#define BALL_D10_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO BALL_D10_IS_GPIO
#endif 

#define BALL_F17 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_F17_IS_GPIO
#define BALL_F17_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_F17_IS_GPIO
#endif 

#define BALL_E9 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define BALL_E11 PAD_I2S_OUT_SD0
#define PAD_I2S_OUT_SD0 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_E11_IS_GPIO
#define BALL_E11_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO BALL_E11_IS_GPIO
#endif 

#define BALL_F8 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define BALL_E10 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_E10_IS_GPIO
#endif 

#define BALL_D11 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_D11_IS_GPIO
#define BALL_D11_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_D11_IS_GPIO
#endif 

#define BALL_D6 PAD_GPIO9
#define PAD_GPIO9 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_D6_IS_GPIO
#endif 

#define BALL_D7 PAD_GPIO8
#define PAD_GPIO8 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_D7_IS_GPIO
#endif 

#define BALL_F7 PAD_GPIO7
#define PAD_GPIO7 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_F7_IS_GPIO
#endif 

#define BALL_E6 PAD_GPIO6
#define PAD_GPIO6 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_D1 PAD_SD_D1
#define PAD_SD_D1 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_D1_IS_GPIO
#define BALL_D1_IS_GPIO 0
#endif 
#ifndef PAD_SD_D1_IS_GPIO
#define PAD_SD_D1_IS_GPIO BALL_D1_IS_GPIO
#endif 

#define BALL_D3 PAD_SD_D0
#define PAD_SD_D0 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif 
#ifndef PAD_SD_D0_IS_GPIO
#define PAD_SD_D0_IS_GPIO BALL_D3_IS_GPIO
#endif 

#define BALL_E2 PAD_SD_CLK
#define PAD_SD_CLK 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif 
#ifndef PAD_SD_CLK_IS_GPIO
#define PAD_SD_CLK_IS_GPIO BALL_E2_IS_GPIO
#endif 

#define BALL_E3 PAD_SD_CMD
#define PAD_SD_CMD 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif 
#ifndef PAD_SD_CMD_IS_GPIO
#define PAD_SD_CMD_IS_GPIO BALL_E3_IS_GPIO
#endif 

#define BALL_F1 PAD_SD_D3
#define PAD_SD_D3 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_F1_IS_GPIO
#define BALL_F1_IS_GPIO 0
#endif 
#ifndef PAD_SD_D3_IS_GPIO
#define PAD_SD_D3_IS_GPIO BALL_F1_IS_GPIO
#endif 

#define BALL_F2 PAD_SD_D2
#define PAD_SD_D2 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif 
#ifndef PAD_SD_D2_IS_GPIO
#define PAD_SD_D2_IS_GPIO BALL_F2_IS_GPIO
#endif 

#define BALL_D8 PAD_GPIO5
#define PAD_GPIO5 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_D8_IS_GPIO
#endif 

#define BALL_E5 PAD_GPIO4
#define PAD_GPIO4 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_E7 PAD_GPIO3
#define PAD_GPIO3 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_D5 PAD_GPIO2
#define PAD_GPIO2 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_E8 PAD_GPIO1
#define PAD_GPIO1 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_E4 PAD_GPIO0
#define PAD_GPIO0 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define PAD_CI_CDZ 9999
#ifndef PAD_CI_CDZ_IS_GPIO
#define PAD_CI_CDZ_IS_GPIO 0
#endif 

#define PAD_CI_D3 9999
#ifndef PAD_CI_D3_IS_GPIO
#define PAD_CI_D3_IS_GPIO 0
#endif 

#define PAD_CI_D4 9999
#ifndef PAD_CI_D4_IS_GPIO
#define PAD_CI_D4_IS_GPIO 0
#endif 

#define PAD_CI_D5 9999
#ifndef PAD_CI_D5_IS_GPIO
#define PAD_CI_D5_IS_GPIO 0
#endif 

#define PAD_CI_D6 9999
#ifndef PAD_CI_D6_IS_GPIO
#define PAD_CI_D6_IS_GPIO 0
#endif 

#define PAD_CI_D7 9999
#ifndef PAD_CI_D7_IS_GPIO
#define PAD_CI_D7_IS_GPIO 0
#endif 

#define PAD_CI_CEZ 9999
#ifndef PAD_CI_CEZ_IS_GPIO
#define PAD_CI_CEZ_IS_GPIO 0
#endif 

#define PAD_CI_A10 9999
#ifndef PAD_CI_A10_IS_GPIO
#define PAD_CI_A10_IS_GPIO 0
#endif 

#define PAD_CI_OEZ 9999
#ifndef PAD_CI_OEZ_IS_GPIO
#define PAD_CI_OEZ_IS_GPIO 0
#endif 

#define PAD_CI_IORDZ 9999
#ifndef PAD_CI_IORDZ_IS_GPIO
#define PAD_CI_IORDZ_IS_GPIO 0
#endif 

#define PAD_CI_A11 9999
#ifndef PAD_CI_A11_IS_GPIO
#define PAD_CI_A11_IS_GPIO 0
#endif 

#define PAD_CI_IOWRZ 9999
#ifndef PAD_CI_IOWRZ_IS_GPIO
#define PAD_CI_IOWRZ_IS_GPIO 0
#endif 

#define PAD_CI_A9 9999
#ifndef PAD_CI_A9_IS_GPIO
#define PAD_CI_A9_IS_GPIO 0
#endif 

#define PAD_CI_A8 9999
#ifndef PAD_CI_A8_IS_GPIO
#define PAD_CI_A8_IS_GPIO 0
#endif 

#define PAD_CI_A13 9999
#ifndef PAD_CI_A13_IS_GPIO
#define PAD_CI_A13_IS_GPIO 0
#endif 

#define PAD_CI_A14 9999
#ifndef PAD_CI_A14_IS_GPIO
#define PAD_CI_A14_IS_GPIO 0
#endif 

#define PAD_CI_WEZ 9999
#ifndef PAD_CI_WEZ_IS_GPIO
#define PAD_CI_WEZ_IS_GPIO 0
#endif 

#define PAD_CI_IRQAZ 9999
#ifndef PAD_CI_IRQAZ_IS_GPIO
#define PAD_CI_IRQAZ_IS_GPIO 0
#endif 

#define PAD_CI_A7 9999
#ifndef PAD_CI_A7_IS_GPIO
#define PAD_CI_A7_IS_GPIO 0
#endif 

#define PAD_CI_A12 9999
#ifndef PAD_CI_A12_IS_GPIO
#define PAD_CI_A12_IS_GPIO 0
#endif 

#define PAD_CI_A6 9999
#ifndef PAD_CI_A6_IS_GPIO
#define PAD_CI_A6_IS_GPIO 0
#endif 

#define PAD_CI_A4 9999
#ifndef PAD_CI_A4_IS_GPIO
#define PAD_CI_A4_IS_GPIO 0
#endif 

#define PAD_CI_WAITZ 9999
#ifndef PAD_CI_WAITZ_IS_GPIO
#define PAD_CI_WAITZ_IS_GPIO 0
#endif 

#define PAD_CI_A2 9999
#ifndef PAD_CI_A2_IS_GPIO
#define PAD_CI_A2_IS_GPIO 0
#endif 

#define PAD_CI_RST 9999
#ifndef PAD_CI_RST_IS_GPIO
#define PAD_CI_RST_IS_GPIO 0
#endif 

#define PAD_CI_A5 9999
#ifndef PAD_CI_A5_IS_GPIO
#define PAD_CI_A5_IS_GPIO 0
#endif 

#define PAD_CI_A3 9999
#ifndef PAD_CI_A3_IS_GPIO
#define PAD_CI_A3_IS_GPIO 0
#endif 

#define PAD_CI_REGZ 9999
#ifndef PAD_CI_REGZ_IS_GPIO
#define PAD_CI_REGZ_IS_GPIO 0
#endif 

#define PAD_CI_A1 9999
#ifndef PAD_CI_A1_IS_GPIO
#define PAD_CI_A1_IS_GPIO 0
#endif 

#define PAD_CI_A0 9999
#ifndef PAD_CI_A0_IS_GPIO
#define PAD_CI_A0_IS_GPIO 0
#endif 

#define PAD_CI_D0 9999
#ifndef PAD_CI_D0_IS_GPIO
#define PAD_CI_D0_IS_GPIO 0
#endif 

#define PAD_CI_D1 9999
#ifndef PAD_CI_D1_IS_GPIO
#define PAD_CI_D1_IS_GPIO 0
#endif 

#define PAD_CI_D2 9999
#ifndef PAD_CI_D2_IS_GPIO
#define PAD_CI_D2_IS_GPIO 0
#endif 

#define BALL_AC25 PAD_SM0_IO
#define PAD_SM0_IO 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_AC25_IS_GPIO
#define BALL_AC25_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO BALL_AC25_IS_GPIO
#endif 

#define BALL_AB24 PAD_SM0_RST
#define PAD_SM0_RST 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_AB24_IS_GPIO
#define BALL_AB24_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO BALL_AB24_IS_GPIO
#endif 

#define BALL_Y23 PAD_SM0_VSEL
#define PAD_SM0_VSEL 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_Y23_IS_GPIO
#define BALL_Y23_IS_GPIO 0
#endif 
#ifndef PAD_SM0_VSEL_IS_GPIO
#define PAD_SM0_VSEL_IS_GPIO BALL_Y23_IS_GPIO
#endif 

#define BALL_Y25 PAD_SM0_C4
#define PAD_SM0_C4 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_Y25_IS_GPIO
#define BALL_Y25_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO BALL_Y25_IS_GPIO
#endif 

#define BALL_AD25 PAD_SM0_CLK
#define PAD_SM0_CLK 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_AD25_IS_GPIO
#define BALL_AD25_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO BALL_AD25_IS_GPIO
#endif 

#define BALL_AB25 PAD_SM0_VCC
#define PAD_SM0_VCC 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_AB25_IS_GPIO
#define BALL_AB25_IS_GPIO 0
#endif 
#ifndef PAD_SM0_VCC_IS_GPIO
#define PAD_SM0_VCC_IS_GPIO BALL_AB25_IS_GPIO
#endif 

#define BALL_AC23 PAD_SM0_CD
#define PAD_SM0_CD 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO BALL_AC23_IS_GPIO
#endif 

#define BALL_Y24 PAD_SM0_C8
#define PAD_SM0_C8 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_Y24_IS_GPIO
#define BALL_Y24_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO BALL_Y24_IS_GPIO
#endif 

#define BALL_U26 PAD_TS2_SYNC
#define PAD_TS2_SYNC 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_U26_IS_GPIO
#define BALL_U26_IS_GPIO 0
#endif 
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_U26_IS_GPIO
#endif 

#define BALL_N28 PAD_TS2_D0
#define PAD_TS2_D0 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_N28_IS_GPIO
#define BALL_N28_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_N28_IS_GPIO
#endif 

#define BALL_U27 PAD_TS2_VLD
#define PAD_TS2_VLD 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_U27_IS_GPIO
#define BALL_U27_IS_GPIO 0
#endif 
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_U27_IS_GPIO
#endif 

#define BALL_P26 PAD_TS2_D1
#define PAD_TS2_D1 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_P26_IS_GPIO
#define BALL_P26_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO BALL_P26_IS_GPIO
#endif 

#define BALL_P27 PAD_TS2_D3
#define PAD_TS2_D3 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_P27_IS_GPIO
#define BALL_P27_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO BALL_P27_IS_GPIO
#endif 

#define BALL_P28 PAD_TS2_D2
#define PAD_TS2_D2 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_P28_IS_GPIO
#define BALL_P28_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO BALL_P28_IS_GPIO
#endif 

#define BALL_R27 PAD_TS2_D5
#define PAD_TS2_D5 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_R27_IS_GPIO
#define BALL_R27_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO BALL_R27_IS_GPIO
#endif 

#define BALL_R26 PAD_TS2_D4
#define PAD_TS2_D4 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_R26_IS_GPIO
#define BALL_R26_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO BALL_R26_IS_GPIO
#endif 

#define BALL_T27 PAD_TS2_D7
#define PAD_TS2_D7 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_T27_IS_GPIO
#define BALL_T27_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO BALL_T27_IS_GPIO
#endif 

#define BALL_T26 PAD_TS2_D6
#define PAD_TS2_D6 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_T26_IS_GPIO
#define BALL_T26_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO BALL_T26_IS_GPIO
#endif 

#define BALL_L27 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_L27_IS_GPIO
#define BALL_L27_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_L27_IS_GPIO
#endif 

#define BALL_U28 PAD_TS2_CLK
#define PAD_TS2_CLK 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_U28_IS_GPIO
#define BALL_U28_IS_GPIO 0
#endif 
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_U28_IS_GPIO
#endif 

#define PAD_TS1_VLD 9999
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO 0
#endif 

#define PAD_TS1_SYNC 9999
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO 0
#endif 

#define PAD_TS1_D1 9999
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO 0
#endif 

#define PAD_TS1_D0 9999
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO 0
#endif 

#define PAD_TS1_D3 9999
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO 0
#endif 

#define PAD_TS1_D2 9999
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO 0
#endif 

#define PAD_TS1_D5 9999
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO 0
#endif 

#define PAD_TS1_D4 9999
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO 0
#endif 

#define PAD_TS1_D7 9999
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO 0
#endif 

#define PAD_TS1_D6 9999
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO 0
#endif 

#define PAD_TS0_SYNC 9999
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO 0
#endif 

#define PAD_TS1_CLK 9999
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO 0
#endif 

#define PAD_TS0_D0 9999
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO 0
#endif 

#define PAD_TS0_VLD 9999
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO 0
#endif 

#define PAD_TS0_D2 9999
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO 0
#endif 

#define PAD_TS0_D1 9999
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO 0
#endif 

#define PAD_TS0_D4 9999
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO 0
#endif 

#define PAD_TS0_D3 9999
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO 0
#endif 

#define PAD_TS0_D5 9999
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO 0
#endif 

#define PAD_TS0_D6 9999
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO 0
#endif 

#define PAD_TS0_D7 9999
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO 0
#endif 

#define PAD_TS0_CLK 9999
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO 0
#endif 

#define BALL_M26 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_M26_IS_GPIO
#define BALL_M26_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO BALL_M26_IS_GPIO
#endif 

#define BALL_M27 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_M27_IS_GPIO
#define BALL_M27_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO BALL_M27_IS_GPIO
#endif 

#define BALL_N26 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_N26_IS_GPIO
#define BALL_N26_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO BALL_N26_IS_GPIO
#endif 

#define BALL_N27 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_N27_IS_GPIO
#define BALL_N27_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO BALL_N27_IS_GPIO
#endif 

#define BALL_L26 PAD_GT0_MDIO
#define PAD_GT0_MDIO 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_L26_IS_GPIO
#define BALL_L26_IS_GPIO 0
#endif 
#ifndef PAD_GT0_MDIO_IS_GPIO
#define PAD_GT0_MDIO_IS_GPIO BALL_L26_IS_GPIO
#endif 

#define BALL_K27 PAD_GT0_MDC
#define PAD_GT0_MDC 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_K27_IS_GPIO
#define BALL_K27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_MDC_IS_GPIO
#define PAD_GT0_MDC_IS_GPIO BALL_K27_IS_GPIO
#endif 

#define BALL_K28 PAD_GT0_TX_CTL
#define PAD_GT0_TX_CTL 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_K28_IS_GPIO
#define BALL_K28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_CTL_IS_GPIO
#define PAD_GT0_TX_CTL_IS_GPIO BALL_K28_IS_GPIO
#endif 

#define BALL_K26 PAD_GT0_TX_D3
#define PAD_GT0_TX_D3 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_K26_IS_GPIO
#define BALL_K26_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D3_IS_GPIO
#define PAD_GT0_TX_D3_IS_GPIO BALL_K26_IS_GPIO
#endif 

#define BALL_J28 PAD_GT0_TX_D2
#define PAD_GT0_TX_D2 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_J28_IS_GPIO
#define BALL_J28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D2_IS_GPIO
#define PAD_GT0_TX_D2_IS_GPIO BALL_J28_IS_GPIO
#endif 

#define BALL_J27 PAD_GT0_TX_D1
#define PAD_GT0_TX_D1 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_J27_IS_GPIO
#define BALL_J27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D1_IS_GPIO
#define PAD_GT0_TX_D1_IS_GPIO BALL_J27_IS_GPIO
#endif 

#define BALL_J26 PAD_GT0_TX_D0
#define PAD_GT0_TX_D0 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_J26_IS_GPIO
#define BALL_J26_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_D0_IS_GPIO
#define PAD_GT0_TX_D0_IS_GPIO BALL_J26_IS_GPIO
#endif 

#define BALL_H27 PAD_GT0_TX_CLK
#define PAD_GT0_TX_CLK 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_H27_IS_GPIO
#define BALL_H27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_TX_CLK_IS_GPIO
#define PAD_GT0_TX_CLK_IS_GPIO BALL_H27_IS_GPIO
#endif 

#define BALL_H26 PAD_GT0_RX_CLK
#define PAD_GT0_RX_CLK 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_H26_IS_GPIO
#define BALL_H26_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_CLK_IS_GPIO
#define PAD_GT0_RX_CLK_IS_GPIO BALL_H26_IS_GPIO
#endif 

#define BALL_G27 PAD_GT0_RX_D3
#define PAD_GT0_RX_D3 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_G27_IS_GPIO
#define BALL_G27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D3_IS_GPIO
#define PAD_GT0_RX_D3_IS_GPIO BALL_G27_IS_GPIO
#endif 

#define BALL_G26 PAD_GT0_RX_D2
#define PAD_GT0_RX_D2 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_G26_IS_GPIO
#define BALL_G26_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D2_IS_GPIO
#define PAD_GT0_RX_D2_IS_GPIO BALL_G26_IS_GPIO
#endif 

#define BALL_F27 PAD_GT0_RX_D1
#define PAD_GT0_RX_D1 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_F27_IS_GPIO
#define BALL_F27_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D1_IS_GPIO
#define PAD_GT0_RX_D1_IS_GPIO BALL_F27_IS_GPIO
#endif 

#define BALL_F28 PAD_GT0_RX_D0
#define PAD_GT0_RX_D0 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_F28_IS_GPIO
#define BALL_F28_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_D0_IS_GPIO
#define PAD_GT0_RX_D0_IS_GPIO BALL_F28_IS_GPIO
#endif 

#define BALL_F26 PAD_GT0_RX_CTL
#define PAD_GT0_RX_CTL 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_F26_IS_GPIO
#define BALL_F26_IS_GPIO 0
#endif 
#ifndef PAD_GT0_RX_CTL_IS_GPIO
#define PAD_GT0_RX_CTL_IS_GPIO BALL_F26_IS_GPIO
#endif 

#define BALL_C24 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_C24_IS_GPIO
#define BALL_C24_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_C24_IS_GPIO
#endif 

#define BALL_C25 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_C25_IS_GPIO
#define BALL_C25_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_C25_IS_GPIO
#endif 

#define BALL_D25 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_D25_IS_GPIO
#define BALL_D25_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_D25_IS_GPIO
#endif 

#define BALL_E24 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_E24_IS_GPIO
#define BALL_E24_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_E24_IS_GPIO
#endif 

#define BALL_E25 PAD_SAR_GPIO4
#define PAD_SAR_GPIO4 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_E25_IS_GPIO
#define BALL_E25_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO4_IS_GPIO
#define PAD_SAR_GPIO4_IS_GPIO BALL_E25_IS_GPIO
#endif 

#define BALL_A19 PAD_PM_GPIO0
#define PAD_PM_GPIO0 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_A19_IS_GPIO
#define BALL_A19_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_A19_IS_GPIO
#endif 

#define BALL_A26 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_A26_IS_GPIO
#define BALL_A26_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_A26_IS_GPIO
#endif 

#define BALL_A22 PAD_PM_GPIO1
#define PAD_PM_GPIO1 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_A22_IS_GPIO
#define BALL_A22_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_A22_IS_GPIO
#endif 

#define BALL_B27 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_B27_IS_GPIO
#define BALL_B27_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B27_IS_GPIO
#endif 

#define BALL_B21 PAD_PM_GPIO2
#define PAD_PM_GPIO2 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_B21_IS_GPIO
#define BALL_B21_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO BALL_B21_IS_GPIO
#endif 

#define BALL_A27 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_A27_IS_GPIO
#define BALL_A27_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_A27_IS_GPIO
#endif 

#define BALL_D24 PAD_PM_GPIO3
#define PAD_PM_GPIO3 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_D24_IS_GPIO
#define BALL_D24_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO BALL_D24_IS_GPIO
#endif 

#define BALL_B28 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_B28_IS_GPIO
#define BALL_B28_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO BALL_B28_IS_GPIO
#endif 

#define BALL_B22 PAD_PM_GPIO4
#define PAD_PM_GPIO4 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_B22_IS_GPIO
#define BALL_B22_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_B22_IS_GPIO
#endif 

#define BALL_B26 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_B26_IS_GPIO
#define BALL_B26_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_B26_IS_GPIO
#endif 

#define BALL_D23 PAD_PM_GPIO5
#define PAD_PM_GPIO5 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_D23_IS_GPIO
#define BALL_D23_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO BALL_D23_IS_GPIO
#endif 

#define BALL_J23 PAD_PM_GPIO6
#define PAD_PM_GPIO6 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_J23_IS_GPIO
#define BALL_J23_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO BALL_J23_IS_GPIO
#endif 

#define BALL_J22 PAD_PM_GPIO11
#define PAD_PM_GPIO11 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_J22_IS_GPIO
#define BALL_J22_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO11_IS_GPIO
#define PAD_PM_GPIO11_IS_GPIO BALL_J22_IS_GPIO
#endif 

#define BALL_J24 PAD_PM_GPIO7
#define PAD_PM_GPIO7 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_J24_IS_GPIO
#define BALL_J24_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO BALL_J24_IS_GPIO
#endif 

#define BALL_M25 PAD_PM_GPIO12
#define PAD_PM_GPIO12 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_M25_IS_GPIO
#define BALL_M25_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO BALL_M25_IS_GPIO
#endif 

#define BALL_K23 PAD_PM_GPIO8
#define PAD_PM_GPIO8 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_K23_IS_GPIO
#define BALL_K23_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO8_IS_GPIO
#define PAD_PM_GPIO8_IS_GPIO BALL_K23_IS_GPIO
#endif 

#define BALL_H24 PAD_PM_GPIO13
#define PAD_PM_GPIO13 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_H24_IS_GPIO
#define BALL_H24_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO BALL_H24_IS_GPIO
#endif 

#define BALL_J25 PAD_PM_GPIO9
#define PAD_PM_GPIO9 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_J25_IS_GPIO
#define BALL_J25_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO BALL_J25_IS_GPIO
#endif 

#define BALL_H25 PAD_PM_GPIO14
#define PAD_PM_GPIO14 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_H25_IS_GPIO
#define BALL_H25_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO BALL_H25_IS_GPIO
#endif 

#define BALL_K24 PAD_PM_GPIO10
#define PAD_PM_GPIO10 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_K24_IS_GPIO
#define BALL_K24_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO BALL_K24_IS_GPIO
#endif 

#define BALL_M22 PAD_PM_GPIO15
#define PAD_PM_GPIO15 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_M22_IS_GPIO
#define BALL_M22_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO15_IS_GPIO
#define PAD_PM_GPIO15_IS_GPIO BALL_M22_IS_GPIO
#endif 

#define BALL_M23 PAD_VID0
#define PAD_VID0 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_M23_IS_GPIO
#define BALL_M23_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_M23_IS_GPIO
#endif 

#define BALL_M24 PAD_VID1
#define PAD_VID1 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_M24_IS_GPIO
#define BALL_M24_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_M24_IS_GPIO
#endif 

#define BALL_A25 PAD_PM_LED0
#define PAD_PM_LED0 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_A25_IS_GPIO
#define BALL_A25_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED0_IS_GPIO
#define PAD_PM_LED0_IS_GPIO BALL_A25_IS_GPIO
#endif 

#define BALL_B25 PAD_PM_LED1
#define PAD_PM_LED1 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_B25_IS_GPIO
#define BALL_B25_IS_GPIO 0
#endif 
#ifndef PAD_PM_LED1_IS_GPIO
#define PAD_PM_LED1_IS_GPIO BALL_B25_IS_GPIO
#endif 

#define BALL_E19 PAD_PM_CEC
#define PAD_PM_CEC 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_E19_IS_GPIO
#define BALL_E19_IS_GPIO 0
#endif 
#ifndef PAD_PM_CEC_IS_GPIO
#define PAD_PM_CEC_IS_GPIO BALL_E19_IS_GPIO
#endif 

#define BALL_E23 PAD_HDMIRX_HPD
#define PAD_HDMIRX_HPD 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_E23_IS_GPIO
#define BALL_E23_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_HPD_IS_GPIO
#define PAD_HDMIRX_HPD_IS_GPIO BALL_E23_IS_GPIO
#endif 

#define BALL_F19 PAD_HDMITX_HPD
#define PAD_HDMITX_HPD 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_F19_IS_GPIO
#define BALL_F19_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_HPD_IS_GPIO
#define PAD_HDMITX_HPD_IS_GPIO BALL_F19_IS_GPIO
#endif 

#define BALL_D19 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_D19_IS_GPIO
#define BALL_D19_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_D19_IS_GPIO
#endif 

#define BALL_E18 PAD_RX_DDCDA_DA
#define PAD_RX_DDCDA_DA 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_E18_IS_GPIO
#define BALL_E18_IS_GPIO 0
#endif 
#ifndef PAD_RX_DDCDA_DA_IS_GPIO
#define PAD_RX_DDCDA_DA_IS_GPIO BALL_E18_IS_GPIO
#endif 

#define BALL_E22 PAD_RX_DDCDA_CK
#define PAD_RX_DDCDA_CK 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_E22_IS_GPIO
#define BALL_E22_IS_GPIO 0
#endif 
#ifndef PAD_RX_DDCDA_CK_IS_GPIO
#define PAD_RX_DDCDA_CK_IS_GPIO BALL_E22_IS_GPIO
#endif 

#define BALL_AB28 PAD_PM_IRIN
#define PAD_PM_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_AB28_IS_GPIO
#define BALL_AB28_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_AB28_IS_GPIO
#endif 

#define BALL_G20 PAD_PM_SD_CDZ
#define PAD_PM_SD_CDZ 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_G20_IS_GPIO
#define BALL_G20_IS_GPIO 0
#endif 
#ifndef PAD_PM_SD_CDZ_IS_GPIO
#define PAD_PM_SD_CDZ_IS_GPIO BALL_G20_IS_GPIO
#endif 

#define BALL_B19 PAD_HDMITX_ARC
#define PAD_HDMITX_ARC 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_B19_IS_GPIO
#define BALL_B19_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_ARC_IS_GPIO
#define PAD_HDMITX_ARC_IS_GPIO BALL_B19_IS_GPIO
#endif 

#define BALL_E17 PAD_HDMIRX_ARC
#define PAD_HDMIRX_ARC 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_ARC_IS_GPIO
#define PAD_HDMIRX_ARC_IS_GPIO BALL_E17_IS_GPIO
#endif 

#define BALL_B19 PAD_HDMITX_ARC
#define PAD_HDMITX_ARC 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_B19_IS_GPIO
#define BALL_B19_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_ARC_IS_GPIO
#define PAD_HDMITX_ARC_IS_GPIO BALL_B19_IS_GPIO
#endif 

#define BALL_E17 PAD_HDMIRX_ARC
#define PAD_HDMIRX_ARC 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_ARC_IS_GPIO
#define PAD_HDMIRX_ARC_IS_GPIO BALL_E17_IS_GPIO
#endif 

#define BALL_AE21 PAD_HSYNC_OUT
#define PAD_HSYNC_OUT 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif 
#ifndef PAD_HSYNC_OUT_IS_GPIO
#define PAD_HSYNC_OUT_IS_GPIO BALL_AE21_IS_GPIO
#endif 

#define BALL_AF21 PAD_VSYNC_OUT
#define PAD_VSYNC_OUT 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_AF21_IS_GPIO
#define BALL_AF21_IS_GPIO 0
#endif 
#ifndef PAD_VSYNC_OUT_IS_GPIO
#define PAD_VSYNC_OUT_IS_GPIO BALL_AF21_IS_GPIO
#endif 

#define BALL_F18 PAD_HDMITX_SCL
#define PAD_HDMITX_SCL 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_F18_IS_GPIO
#define BALL_F18_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SCL_IS_GPIO
#define PAD_HDMITX_SCL_IS_GPIO BALL_F18_IS_GPIO
#endif 

#define BALL_D18 PAD_HDMITX_SDA
#define PAD_HDMITX_SDA 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_D18_IS_GPIO
#define BALL_D18_IS_GPIO 0
#endif 
#ifndef PAD_HDMITX_SDA_IS_GPIO
#define PAD_HDMITX_SDA_IS_GPIO BALL_D18_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256
#define PADS_EMMC_IO16      1257
#define PAD_I2S_OUT_SDO     1258
#define PADS_SM1_IO         1259
#define PAD_EMMC_IO0        1260
#define PAD_EMMC_IO16       1261
#define PAD_EMMC_IO12       1262
#define PAD_SDIO_IO0        1263
#define PAD_EMMC_IO11       1264

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSO9580AP_H_*/
